// Code generated by ent, DO NOT EDIT.

package subscriptionentitlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldGroupID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldPlanID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldPaymentOrderID, v))
}

// QuotaMode applies equality check predicate on the "quota_mode" field. It's identical to QuotaModeEQ.
func QuotaMode(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaMode, v))
}

// QuotaLimitUsd applies equality check predicate on the "quota_limit_usd" field. It's identical to QuotaLimitUsdEQ.
func QuotaLimitUsd(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaLimitUsd, v))
}

// QuotaUsedUsd applies equality check predicate on the "quota_used_usd" field. It's identical to QuotaUsedUsdEQ.
func QuotaUsedUsd(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaUsedUsd, v))
}

// QuotaReservedUsd applies equality check predicate on the "quota_reserved_usd" field. It's identical to QuotaReservedUsdEQ.
func QuotaReservedUsd(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaReservedUsd, v))
}

// DurationHours applies equality check predicate on the "duration_hours" field. It's identical to DurationHoursEQ.
func DurationHours(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldDurationHours, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldStatus, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldActivatedAt, v))
}

// ExhaustedAt applies equality check predicate on the "exhausted_at" field. It's identical to ExhaustedAtEQ.
func ExhaustedAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldExhaustedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldEndedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldGroupID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldPlanID, v))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotNull(FieldPlanID))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldPaymentOrderID, v))
}

// QuotaModeEQ applies the EQ predicate on the "quota_mode" field.
func QuotaModeEQ(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaMode, v))
}

// QuotaModeNEQ applies the NEQ predicate on the "quota_mode" field.
func QuotaModeNEQ(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldQuotaMode, v))
}

// QuotaModeIn applies the In predicate on the "quota_mode" field.
func QuotaModeIn(vs ...string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldQuotaMode, vs...))
}

// QuotaModeNotIn applies the NotIn predicate on the "quota_mode" field.
func QuotaModeNotIn(vs ...string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldQuotaMode, vs...))
}

// QuotaModeGT applies the GT predicate on the "quota_mode" field.
func QuotaModeGT(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldQuotaMode, v))
}

// QuotaModeGTE applies the GTE predicate on the "quota_mode" field.
func QuotaModeGTE(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldQuotaMode, v))
}

// QuotaModeLT applies the LT predicate on the "quota_mode" field.
func QuotaModeLT(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldQuotaMode, v))
}

// QuotaModeLTE applies the LTE predicate on the "quota_mode" field.
func QuotaModeLTE(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldQuotaMode, v))
}

// QuotaModeContains applies the Contains predicate on the "quota_mode" field.
func QuotaModeContains(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldContains(FieldQuotaMode, v))
}

// QuotaModeHasPrefix applies the HasPrefix predicate on the "quota_mode" field.
func QuotaModeHasPrefix(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldHasPrefix(FieldQuotaMode, v))
}

// QuotaModeHasSuffix applies the HasSuffix predicate on the "quota_mode" field.
func QuotaModeHasSuffix(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldHasSuffix(FieldQuotaMode, v))
}

// QuotaModeEqualFold applies the EqualFold predicate on the "quota_mode" field.
func QuotaModeEqualFold(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEqualFold(FieldQuotaMode, v))
}

// QuotaModeContainsFold applies the ContainsFold predicate on the "quota_mode" field.
func QuotaModeContainsFold(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldContainsFold(FieldQuotaMode, v))
}

// QuotaLimitUsdEQ applies the EQ predicate on the "quota_limit_usd" field.
func QuotaLimitUsdEQ(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaLimitUsd, v))
}

// QuotaLimitUsdNEQ applies the NEQ predicate on the "quota_limit_usd" field.
func QuotaLimitUsdNEQ(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldQuotaLimitUsd, v))
}

// QuotaLimitUsdIn applies the In predicate on the "quota_limit_usd" field.
func QuotaLimitUsdIn(vs ...float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldQuotaLimitUsd, vs...))
}

// QuotaLimitUsdNotIn applies the NotIn predicate on the "quota_limit_usd" field.
func QuotaLimitUsdNotIn(vs ...float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldQuotaLimitUsd, vs...))
}

// QuotaLimitUsdGT applies the GT predicate on the "quota_limit_usd" field.
func QuotaLimitUsdGT(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldQuotaLimitUsd, v))
}

// QuotaLimitUsdGTE applies the GTE predicate on the "quota_limit_usd" field.
func QuotaLimitUsdGTE(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldQuotaLimitUsd, v))
}

// QuotaLimitUsdLT applies the LT predicate on the "quota_limit_usd" field.
func QuotaLimitUsdLT(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldQuotaLimitUsd, v))
}

// QuotaLimitUsdLTE applies the LTE predicate on the "quota_limit_usd" field.
func QuotaLimitUsdLTE(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldQuotaLimitUsd, v))
}

// QuotaUsedUsdEQ applies the EQ predicate on the "quota_used_usd" field.
func QuotaUsedUsdEQ(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaUsedUsd, v))
}

// QuotaUsedUsdNEQ applies the NEQ predicate on the "quota_used_usd" field.
func QuotaUsedUsdNEQ(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldQuotaUsedUsd, v))
}

// QuotaUsedUsdIn applies the In predicate on the "quota_used_usd" field.
func QuotaUsedUsdIn(vs ...float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldQuotaUsedUsd, vs...))
}

// QuotaUsedUsdNotIn applies the NotIn predicate on the "quota_used_usd" field.
func QuotaUsedUsdNotIn(vs ...float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldQuotaUsedUsd, vs...))
}

// QuotaUsedUsdGT applies the GT predicate on the "quota_used_usd" field.
func QuotaUsedUsdGT(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldQuotaUsedUsd, v))
}

// QuotaUsedUsdGTE applies the GTE predicate on the "quota_used_usd" field.
func QuotaUsedUsdGTE(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldQuotaUsedUsd, v))
}

// QuotaUsedUsdLT applies the LT predicate on the "quota_used_usd" field.
func QuotaUsedUsdLT(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldQuotaUsedUsd, v))
}

// QuotaUsedUsdLTE applies the LTE predicate on the "quota_used_usd" field.
func QuotaUsedUsdLTE(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldQuotaUsedUsd, v))
}

// QuotaReservedUsdEQ applies the EQ predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdEQ(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldQuotaReservedUsd, v))
}

// QuotaReservedUsdNEQ applies the NEQ predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdNEQ(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldQuotaReservedUsd, v))
}

// QuotaReservedUsdIn applies the In predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdIn(vs ...float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldQuotaReservedUsd, vs...))
}

// QuotaReservedUsdNotIn applies the NotIn predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdNotIn(vs ...float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldQuotaReservedUsd, vs...))
}

// QuotaReservedUsdGT applies the GT predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdGT(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldQuotaReservedUsd, v))
}

// QuotaReservedUsdGTE applies the GTE predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdGTE(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldQuotaReservedUsd, v))
}

// QuotaReservedUsdLT applies the LT predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdLT(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldQuotaReservedUsd, v))
}

// QuotaReservedUsdLTE applies the LTE predicate on the "quota_reserved_usd" field.
func QuotaReservedUsdLTE(v float64) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldQuotaReservedUsd, v))
}

// DurationHoursEQ applies the EQ predicate on the "duration_hours" field.
func DurationHoursEQ(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldDurationHours, v))
}

// DurationHoursNEQ applies the NEQ predicate on the "duration_hours" field.
func DurationHoursNEQ(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldDurationHours, v))
}

// DurationHoursIn applies the In predicate on the "duration_hours" field.
func DurationHoursIn(vs ...int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldDurationHours, vs...))
}

// DurationHoursNotIn applies the NotIn predicate on the "duration_hours" field.
func DurationHoursNotIn(vs ...int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldDurationHours, vs...))
}

// DurationHoursGT applies the GT predicate on the "duration_hours" field.
func DurationHoursGT(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldDurationHours, v))
}

// DurationHoursGTE applies the GTE predicate on the "duration_hours" field.
func DurationHoursGTE(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldDurationHours, v))
}

// DurationHoursLT applies the LT predicate on the "duration_hours" field.
func DurationHoursLT(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldDurationHours, v))
}

// DurationHoursLTE applies the LTE predicate on the "duration_hours" field.
func DurationHoursLTE(v int) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldDurationHours, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldContainsFold(FieldStatus, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldStartsAt, v))
}

// StartsAtIsNil applies the IsNil predicate on the "starts_at" field.
func StartsAtIsNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIsNull(FieldStartsAt))
}

// StartsAtNotNil applies the NotNil predicate on the "starts_at" field.
func StartsAtNotNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotNull(FieldStartsAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotNull(FieldExpiresAt))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotNull(FieldActivatedAt))
}

// ExhaustedAtEQ applies the EQ predicate on the "exhausted_at" field.
func ExhaustedAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldExhaustedAt, v))
}

// ExhaustedAtNEQ applies the NEQ predicate on the "exhausted_at" field.
func ExhaustedAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldExhaustedAt, v))
}

// ExhaustedAtIn applies the In predicate on the "exhausted_at" field.
func ExhaustedAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldExhaustedAt, vs...))
}

// ExhaustedAtNotIn applies the NotIn predicate on the "exhausted_at" field.
func ExhaustedAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldExhaustedAt, vs...))
}

// ExhaustedAtGT applies the GT predicate on the "exhausted_at" field.
func ExhaustedAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldExhaustedAt, v))
}

// ExhaustedAtGTE applies the GTE predicate on the "exhausted_at" field.
func ExhaustedAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldExhaustedAt, v))
}

// ExhaustedAtLT applies the LT predicate on the "exhausted_at" field.
func ExhaustedAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldExhaustedAt, v))
}

// ExhaustedAtLTE applies the LTE predicate on the "exhausted_at" field.
func ExhaustedAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldExhaustedAt, v))
}

// ExhaustedAtIsNil applies the IsNil predicate on the "exhausted_at" field.
func ExhaustedAtIsNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIsNull(FieldExhaustedAt))
}

// ExhaustedAtNotNil applies the NotNil predicate on the "exhausted_at" field.
func ExhaustedAtNotNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotNull(FieldExhaustedAt))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotNull(FieldEndedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionEntitlement) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionEntitlement) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionEntitlement) predicate.SubscriptionEntitlement {
	return predicate.SubscriptionEntitlement(sql.NotPredicates(p))
}
