-- Prompt Library default Chinese taxonomy and first review-pool import batch.
-- Seeded external-inspired items stay in pending review and are not published
-- until an administrator verifies quality, source evidence, and authorization.

WITH seed_categories(slug, name_zh, description_zh, dimension, sort_order) AS (
    VALUES
        ('profile-avatar', '头像写真', '头像、个人形象、社交账号头像与资料图。', 'purpose', 10),
        ('social-media-post', '社交图文', '小红书、微博、公众号、朋友圈等社交封面与配图。', 'purpose', 20),
        ('infographic-edu-visual', '信息图与科普图', '信息图、知识卡片、流程说明和教学视觉。', 'purpose', 30),
        ('youtube-thumbnail', '视频封面', '视频封面、直播封面、栏目主视觉和点击缩略图。', 'purpose', 40),
        ('comic-storyboard', '漫画分镜', '漫画页、连续分镜、故事板和角色叙事图。', 'purpose', 50),
        ('product-marketing', '产品营销', '产品广告、卖点图、品牌活动图和推广素材。', 'purpose', 60),
        ('ecommerce-main-image', '电商主图', '白底主图、场景主图、套装图和货架缩略图。', 'purpose', 70),
        ('game-asset', '游戏素材', '角色、道具、图标、场景和像素素材。', 'purpose', 80),
        ('poster-flyer', '海报传单', '活动海报、展会传单、节日促销和公告视觉。', 'purpose', 90),
        ('app-web-design', '应用与网页设计', '应用界面、网页首屏、产品截图和运营落地页。', 'purpose', 100),
        ('free-creation', '自由创作', '概念创作、艺术实验、风格探索和灵感草案。', 'purpose', 110),
        ('packaging-design', '包装设计', '包装盒、瓶贴、袋装、礼盒和包装系列视觉。', 'purpose', 120),
        ('brand-identity', '品牌视觉', '标志延展、品牌板、吉祥物、图标和视觉识别。', 'purpose', 130),
        ('interior-redesign', '室内改造', '家装、店装、办公空间、展厅和空间改造方案。', 'purpose', 140),
        ('photo-retouching', '照片修复与编辑', '老照片修复、换背景、局部替换和画面增强。', 'purpose', 150),
        ('virtual-try-on', '虚拟试穿', '服装、眼镜、珠宝、美妆和发型试穿预览。', 'purpose', 160),
        ('book-album-cover', '书籍与唱片封面', '图书封面、专辑封面、播客封面和栏目包装。', 'purpose', 170),
        ('local-life-map', '本地生活地图', '城市美食地图、旅行路线、商圈导览和地点推荐。', 'purpose', 180),
        ('education-course', '课程与培训', '课程封面、知识卡、培训海报和教学配图。', 'purpose', 190),
        ('healthcare-visual', '健康医疗', '健康科普、医疗服务、护理指南和器械展示。', 'purpose', 200),
        ('wedding-event', '婚礼与庆典', '婚礼请柬、生日派对、年会庆典和仪式主视觉。', 'purpose', 210),
        ('brand-mascot', '品牌角色', '品牌吉祥物、虚拟人、IP 角色和表情动作。', 'purpose', 220),
        ('ad-creative', '广告投放', '信息流广告、搜索广告、展示广告和多版本投放素材。', 'purpose', 230),
        ('live-commerce', '直播电商', '直播间背景、商品讲解图、挂车封面和促销视觉。', 'purpose', 240),
        ('product-photography', '商品摄影', '棚拍、场景摄影、细节特写和商品图片精修。', 'purpose', 250),
        ('mockup-scene', '样机展示', '手机、包装、海报、服装、屏幕和实体物料样机。', 'purpose', 260),
        ('wallpaper-background', '壁纸背景', '手机壁纸、电脑壁纸、直播背景和视觉底图。', 'purpose', 270),
        ('document-presentation', '文档与演示', 'PPT、报告封面、白皮书、方案页和演示视觉。', 'purpose', 280),
        ('resume-id-photo', '证件与简历', '证件照、简历头像、职业形象和个人名片视觉。', 'purpose', 290),
        ('festival-campaign', '节日营销', '节日海报、节点营销、礼品促销和祝福视觉。', 'purpose', 300),
        ('meme-sticker', '表情与贴图', '表情包、贴纸、社群素材和趣味互动图。', 'purpose', 310),
        ('print-merchandise', '文创周边', 'T 恤、帆布袋、贴纸、徽章、明信片和周边图案。', 'purpose', 320),
        ('real-estate-visual', '房产建筑', '楼盘、租赁、园区、酒店、民宿和建筑宣传视觉。', 'purpose', 330),
        ('public-service', '公益政务', '公益宣传、城市服务、政务公告和公共安全视觉。', 'purpose', 340),
        ('financial-business', '金融商务', '金融科技、商务报告、企业服务和数据安全视觉。', 'purpose', 350),
        ('automotive-visual', '汽车交通', '汽车广告、维修服务、出行路线和交通工具展示。', 'purpose', 360),
        ('luxury-fashion', '奢品时尚', '奢侈品、美妆大片、时尚活动和高级造型视觉。', 'purpose', 370),
        ('beauty-salon', '美业门店', '美甲、美发、皮肤管理、医美门店和服务展示。', 'purpose', 380),
        ('agriculture-food', '农产品食品', '农产品、生鲜、地方特产、食品溯源和产地视觉。', 'purpose', 390),
        ('industrial-manufacturing', '工业制造', '机械设备、工厂、零部件、生产线和 B2B 宣传。', 'purpose', 400),
        ('creative-variants', '创意变体', '同一主题的多风格、多构图、多颜色和投放变体。', 'purpose', 410),
        ('parent-child', '亲子家庭', '母婴、玩具、亲子活动、家庭教育和儿童友好视觉。', 'purpose', 420),

        ('photography', '摄影质感', '真实摄影、商业棚拍、自然光和产品摄影。', 'style', 10),
        ('cinematic-film-still', '电影剧照', '电影感灯光、镜头语言、色彩分级和叙事画面。', 'style', 20),
        ('anime-manga', '动漫漫画', '日系动画、漫画构图、角色立绘和二次元表达。', 'style', 30),
        ('illustration', '商业插画', '品牌插画、编辑插画、扁平插画和故事插画。', 'style', 40),
        ('sketch-line-art', '线稿草图', '线稿、手绘草图、结构草图和黑白稿。', 'style', 50),
        ('comic-graphic-novel', '图像小说', '美漫、欧漫、分镜叙事和强对比画格。', 'style', 60),
        ('3d-render', '三维渲染', '三维模型、产品渲染、材质展示和立体场景。', 'style', 70),
        ('chibi-q-style', 'Q版萌系', 'Q版角色、可爱比例、贴纸头像和萌系插画。', 'style', 80),
        ('isometric', '等距视角', '等距城市、产品流程、微缩场景和结构拆解。', 'style', 90),
        ('pixel-art', '像素艺术', '复古像素、游戏精灵、像素场景和低分辨率风格。', 'style', 100),
        ('oil-painting', '油画质感', '厚涂、经典油画、画布纹理和艺术肖像。', 'style', 110),
        ('watercolor', '水彩质感', '透明水彩、柔和晕染、纸张纹理和轻盈色彩。', 'style', 120),
        ('ink-chinese-style', '水墨国风', '水墨、国风、书画留白和东方构图。', 'style', 130),
        ('retro-vintage', '复古怀旧', '复古海报、胶片颗粒、旧印刷和年代色彩。', 'style', 140),
        ('cyberpunk-sci-fi', '赛博科幻', '霓虹、未来城市、机械细节和科幻材质。', 'style', 150),
        ('minimalism', '极简主义', '留白、简洁排版、低噪视觉和克制色彩。', 'style', 160),
        ('clay-render', '粘土质感', '柔软粘土、手作模型、低饱和材质和亲和视觉。', 'style', 170),
        ('paper-cut', '纸艺剪影', '纸雕层次、剪纸边缘、立体纸艺和柔和阴影。', 'style', 180),
        ('luxury-editorial', '高级大片', '奢侈品大片、时尚棚拍、高级材质和精修质感。', 'style', 190),
        ('blueprint-technical', '蓝图技术', '蓝图线框、技术说明、精密结构和工程草图。', 'style', 200),
        ('flat-vector', '扁平矢量', '清晰形状、低噪色块、品牌插画和图标化表达。', 'style', 210),
        ('children-book', '绘本童趣', '亲子绘本、温柔角色、柔软笔触和儿童友好画面。', 'style', 220),
        ('fashion-editorial', '时装大片', '杂志大片、走秀姿态、服饰层次和高级造型。', 'style', 230),
        ('sticker-icon', '贴纸图标', '贴纸边框、表情包、图标套组和清晰小图。', 'style', 240),
        ('editorial-layout', '杂志排版', '编辑设计、网格排版、栏目封面和高信息密度页面。', 'style', 250),
        ('clean-ui', '清爽界面', '清晰控件、产品界面、信息层级和软件截图质感。', 'style', 260),
        ('neon-glow', '霓虹发光', '发光边缘、暗场对比、夜景氛围和高能视觉。', 'style', 270),
        ('macro-detail', '微距细节', '极近距离、纹理细节、材质特写和浅景深表现。', 'style', 280),
        ('product-render', '产品渲染', '商业产品渲染、精确材质、棚拍光影和高端质感。', 'style', 290),
        ('document-clean', '清爽文档', '报告封面、演示页面、留白版式和商务信息视觉。', 'style', 300),
        ('photorealistic-portrait', '真实人像', '真实人物光影、自然肤色、商业肖像和生活感照片。', 'style', 310),
        ('handmade-craft', '手作质感', '手工纸张、手作物料、布料纹理和温暖手感。', 'style', 320),
        ('low-poly', '低多边形', '低面数造型、几何块面、游戏风格和简化三维。', 'style', 330),
        ('poster-typography', '海报字体', '大标题、字形构成、版式主导和强视觉文字区域。', 'style', 340),

        ('portrait-selfie', '肖像自拍', '人物肖像、自拍风格、证件形象和半身照。', 'subject', 10),
        ('influencer-model', '达人模特', '达人、模特、种草人物和生活方式主体。', 'subject', 20),
        ('character', '角色形象', '虚拟角色、IP 角色、职业人物和表情设定。', 'subject', 30),
        ('group-couple', '多人组合', '情侣、团队、家庭、朋友和群像构图。', 'subject', 40),
        ('product', '商品产品', '实物商品、包装、数码、日用品和消费品。', 'subject', 50),
        ('food-drink', '食品饮品', '餐食、饮品、甜点、包装食品和餐饮视觉。', 'subject', 60),
        ('fashion-item', '服饰配件', '服装、鞋包、首饰、美妆和穿搭配件。', 'subject', 70),
        ('animal-creature', '动物生物', '动物、幻想生物、宠物和拟人角色。', 'subject', 80),
        ('vehicle', '交通工具', '汽车、机车、飞行器、船只和载具概念。', 'subject', 90),
        ('architecture-interior', '建筑室内', '建筑、室内空间、展厅、店铺和家居场景。', 'subject', 100),
        ('landscape-nature', '自然风景', '自然景观、户外、山海、植物和天气氛围。', 'subject', 110),
        ('cityscape-street', '城市街景', '街头、城市天际线、商业街和生活场景。', 'subject', 120),
        ('diagram-chart', '图表结构', '图表、流程、结构说明、拆解图和数据视觉。', 'subject', 130),
        ('text-typography', '文字排版', '标题字、海报字、标语、标牌和排版设计。', 'subject', 140),
        ('abstract-background', '抽象背景', '纹理、渐变、图案、视觉背景和无主体画面。', 'subject', 150),
        ('beauty-cosmetics', '美妆护肤', '彩妆、护肤品、香水、美甲和美妆工具。', 'subject', 160),
        ('electronics-gadget', '数码设备', '手机、耳机、电脑、智能硬件和消费电子。', 'subject', 170),
        ('furniture-home', '家具家居', '家具、灯具、软装、收纳和家居用品。', 'subject', 180),
        ('jewelry-watch', '珠宝腕表', '珠宝、腕表、首饰、礼品和精致配件。', 'subject', 190),
        ('map-location', '地图位置', '地图、路线、地点、商圈和城市导览。', 'subject', 200),
        ('baby-child', '儿童亲子', '儿童、亲子、玩具、绘本和家庭场景。', 'subject', 210),
        ('sports-fitness', '运动健身', '运动装备、健身动作、户外训练和健康生活。', 'subject', 220),
        ('medical-health', '医疗健康', '医疗器械、护理服务、身体健康和科普说明。', 'subject', 230),
        ('music-stage', '音乐舞台', '舞台、乐器、演出、唱片和声音视觉。', 'subject', 240),
        ('wedding-party', '婚礼庆典', '婚礼、派对、仪式、花艺和庆典布置。', 'subject', 250),
        ('logo-symbol', '标志符号', '品牌标志、图形符号、徽章和识别系统。', 'subject', 260),
        ('packaging-label', '包装标签', '瓶贴、盒面、包装结构、标签和产品包装版式。', 'subject', 270),
        ('business-person', '商务人物', '职场人士、创始人、顾问、销售和企业团队形象。', 'subject', 280),
        ('document-slide', '文档页面', '演示页、报告页、白皮书、方案页和简历页面。', 'subject', 290),
        ('phone-device', '手机设备', '手机、平板、屏幕、应用样机和移动设备展示。', 'subject', 300),
        ('cosmetic-bottle', '美妆瓶罐', '护肤瓶、彩妆盘、香水瓶、膏霜罐和套装。', 'subject', 310),
        ('apparel-model', '服装模特', '服装上身、模特展示、鞋包搭配和时装造型。', 'subject', 320),
        ('farm-produce', '农产品生鲜', '水果、蔬菜、粮油、生鲜、产地和地方特产。', 'subject', 330),
        ('machinery-part', '机械零部件', '设备、零部件、工具、工业材料和生产线。', 'subject', 340),
        ('signage-storefront', '门店招牌', '门头、招牌、橱窗、导视、展架和线下空间入口。', 'subject', 350),
        ('gift-flower', '鲜花礼品', '花束、礼盒、节日礼品、伴手礼和庆典装饰。', 'subject', 360),
        ('home-appliance', '家用电器', '小家电、厨房电器、清洁电器和智能家居设备。', 'subject', 370),
        ('currency-card', '支付卡券', '银行卡、会员卡、礼品卡、优惠券和支付界面。', 'subject', 380),
        ('public-service-icon', '公共服务符号', '公益符号、城市服务、提示牌、安全图标和政务视觉。', 'subject', 390),

        ('gpt-image-2', 'GPT Image 2', '适合文字、商业插画、产品系列和高一致性画面。', 'model', 10),
        ('gpt-image-1', 'GPT Image 1', '适合通用图像生成、编辑和商业视觉。', 'model', 20),
        ('gemini-2.5-flash-image', 'Gemini 2.5 Flash Image', '适合快速多风格草案、参考图理解和轻量生成。', 'model', 30),
        ('grok-2-image', 'Grok 2 Image', '适合社交内容、快速创意图和高频迭代。', 'model', 40),
        ('seedream-4.5', 'Seedream 4.5', '适合中文设计图、海报和商业视觉。', 'model', 50),

        ('1024x1024', '方形 1:1', '适合电商主图、头像、图标和通用方图。', 'size', 10),
        ('1024x1536', '竖版 2:3', '适合人物海报、竖版社交图和穿搭图。', 'size', 20),
        ('1536x1024', '横版 3:2', '适合横幅、网页首屏、产品场景和宽图。', 'size', 30),
        ('1024x1792', '竖屏 9:16', '适合手机壁纸、短视频封面和竖屏海报。', 'size', 40),
        ('1792x1024', '宽屏 16:9', '适合视频封面、展示页头图和宽屏场景。', 'size', 50)
)
INSERT INTO prompt_categories (slug, name_zh, description_zh, dimension, sort_order)
SELECT slug, name_zh, description_zh, dimension, sort_order
FROM seed_categories
ON CONFLICT (slug) DO UPDATE SET
    name_zh = EXCLUDED.name_zh,
    description_zh = EXCLUDED.description_zh,
    dimension = EXCLUDED.dimension,
    sort_order = EXCLUDED.sort_order,
    enabled = TRUE,
    updated_at = NOW();

WITH existing_job AS (
    SELECT id
    FROM prompt_import_jobs
    WHERE source_key = 'jisudeng-gpt-image-2-curated-seed-20260717'
    ORDER BY id
    LIMIT 1
),
created_job AS (
    INSERT INTO prompt_import_jobs (source_key, status, raw_payload)
    SELECT
        'jisudeng-gpt-image-2-curated-seed-20260717',
        'pending_review',
        jsonb_build_object(
            'brand', '极速蹬提示词库',
            'source_url', 'https://github.com/YouMind-OpenLab/awesome-gpt-image-2',
            'source_head', '51a031c7874169621688d77adb98b5efd20dd10d',
            'captured_at', '2026-07-17T04:00:00Z',
            'policy', '自动整理内容进入待审核队列，不直接发布'
        )
    WHERE NOT EXISTS (SELECT 1 FROM existing_job)
    RETURNING id
),
job AS (
    SELECT id FROM existing_job
    UNION ALL
    SELECT id FROM created_job
    LIMIT 1
),
seed_items(
    external_id, title_zh, description_zh, prompt_text, purpose, style, subject,
    model, size, reference_requirement, requires_reference, reference_instructions, media_url
) AS (
    VALUES
        ('seed-001', '白底零食主图', '适合食品零食、礼盒和商超缩略图的干净白底主图。', 'Create a clean e-commerce hero image for {{subject}} on a seamless white background, accurate edges, soft commercial lighting, subtle grounding shadow, no extra text, ready for marketplace thumbnail.', 'ecommerce-main-image', 'photography', 'food-drink', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传商品包装参考图以保持包装细节。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-002', '美妆瓶身套装图', '突出瓶身材质、容量层次和套装高级感。', 'Create a premium e-commerce product image for {{subject}}, arranged as a three-piece skincare set, glossy caps, translucent bottle material, bright white studio floor, elegant shadow, no text.', 'ecommerce-main-image', 'photography', 'product', 'gpt-image-2', '1024x1024', 'required', TRUE, '需要上传商品正面或包装参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-003', '鞋包穿搭主图', '适合服饰配件类商品，强调材质与搭配场景。', 'Create a marketplace main image for {{subject}}, fashion editorial styling, clean beige gray background, realistic fabric and leather texture, balanced composition, no extra props that hide the product.', 'ecommerce-main-image', 'photography', 'fashion-item', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传商品参考图以锁定款式。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-004', '数码产品反射主图', '用于耳机、键盘、智能硬件等数码产品展示。', 'Create a sharp product render for {{subject}}, reflective black acrylic base, crisp rim light, clean gray background, precise edges, subtle tech mood, no text, commercial catalog quality.', 'ecommerce-main-image', '3d-render', 'product', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传外观参考图以保持结构准确。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-005', '家居小物场景主图', '用于香薰、杯具、摆件等家居产品的生活方式主图。', 'Create a cozy lifestyle e-commerce image for {{subject}}, morning window light, warm home interior, product clearly centered, shallow depth of field, natural props, no text overlay.', 'ecommerce-main-image', 'photography', 'architecture-interior', 'gpt-image-1', '1024x1024', 'optional', FALSE, '可上传产品参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-006', '食品包装货架图', '适合电商多口味、多规格食品套装。', 'Create an organized product lineup for {{subject}}, multiple flavors arranged in a neat row, bright commercial lighting, readable package front, white background, realistic shadows, no floating text.', 'ecommerce-main-image', 'photography', 'food-drink', 'gpt-image-2', '1536x1024', 'required', TRUE, '需要参考图以保持包装文字和版式。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-007', '户外装备主图', '用于运动、露营和户外产品场景化展示。', 'Create a clean hero image for {{subject}} in a natural outdoor setting, morning sunlight, product in focus, rugged texture, spacious composition, no brand logo replacement, no text.', 'ecommerce-main-image', 'photography', 'landscape-nature', 'gpt-image-1', '1536x1024', 'optional', FALSE, '可上传商品参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-008', '汽车配件主图', '突出金属、橡胶、机械结构等材质细节。', 'Create a high-detail e-commerce main image for {{subject}}, clean studio garage background, metallic detail, accurate mechanical form, three-quarter view, subtle shadow, no text.', 'ecommerce-main-image', '3d-render', 'vehicle', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传结构参考图。', '/image-studio/templates/ecom-white-bg.webp'),

        ('seed-009', '产品卖点海报', '适合新品上市、核心卖点和详情页首屏广告。', 'Design a premium product marketing poster for {{subject}}, one clear hero product, three visual benefit zones without readable small text, elegant lighting, brand color {{color}}, polished commercial layout.', 'product-marketing', 'minimalism', 'product', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传商品图和品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-010', '节日促销视觉', '用于大促、节日折扣和活动首图。', 'Create a festive product promotion image for {{subject}}, celebratory composition, bright ribbons and gift elements, strong center focus, space for Chinese headline {{text}}, high conversion e-commerce style.', 'product-marketing', 'illustration', 'product', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传商品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-011', '新品发布横幅', '适合官网和广告投放的新品发布宽屏图。', 'Create a wide launch banner for {{subject}}, cinematic product reveal, soft gradient studio background, precise highlights, large empty headline area, premium technology brand mood.', 'product-marketing', 'cinematic-film-still', 'product', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传产品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-012', '品牌视觉大片', '把品牌调性和产品氛围做成可投放的主视觉。', 'Create a brand campaign visual for {{subject}}, aspirational lifestyle scene, refined composition, controlled color palette {{color}}, commercial photography, emotional but not cluttered.', 'product-marketing', 'photography', 'influencer-model', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传人物或产品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-013', '功能拆解图', '适合数码、家电、工具类产品说明卖点。', 'Create an exploded view marketing visual for {{subject}}, clean isometric technical layout, labeled callout zones as blank panels, precise components, soft white background, premium industrial design.', 'product-marketing', 'isometric', 'diagram-chart', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传产品结构参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-014', '质感材质特写', '用于展示布料、金属、玻璃、皮革等产品材质。', 'Create a macro material hero shot for {{subject}}, extreme close-up texture detail, shallow depth of field, elegant studio lighting, commercial luxury mood, no text.', 'product-marketing', 'photography', 'fashion-item', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传材质参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-015', '餐饮新品广告', '适合饮品、甜品、轻食新品宣传。', 'Create a mouthwatering food marketing poster for {{subject}}, fresh ingredients in motion, bright appetizing lighting, clean background, space for Chinese headline {{text}}, no distorted text.', 'product-marketing', 'photography', 'food-drink', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传菜品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-016', '环保理念广告', '适合可持续、绿色生活方式产品宣传。', 'Create a product marketing image for {{subject}}, natural materials, leaves and soft daylight, clean minimal composition, sustainability feeling, blank area for short Chinese slogan {{text}}.', 'product-marketing', 'minimalism', 'landscape-nature', 'gpt-image-1', '1536x1024', 'optional', FALSE, '可上传产品或品牌色参考。', '/image-studio/templates/free-create.webp'),

        ('seed-017', '小红书封面图', '适合种草笔记、清单推荐和生活方式封面。', 'Create a Xiaohongshu style cover image for {{subject}}, clean lifestyle composition, warm natural light, tidy product flat lay, large readable Chinese title area {{text}}, polished social media look.', 'social-media-post', 'photography', 'product', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传商品或参考图。', '/image-studio/templates/xhs-cover.webp'),
        ('seed-018', '社交 quote 卡片', '适合观点金句、个人品牌和内容号配图。', 'Create a refined quote card background for {{text}}, elegant typography space, subtle paper texture, warm neutral colors, minimal decorative lines, no random letters.', 'social-media-post', 'minimalism', 'text-typography', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/xhs-cover.webp'),
        ('seed-019', '城市探店封面', '适合本地生活、咖啡店、餐厅和街区推荐。', 'Create a social media cover for {{subject}}, cozy city street storefront, cinematic dusk lighting, inviting atmosphere, clean space for Chinese title {{text}}, editorial travel style.', 'social-media-post', 'cinematic-film-still', 'cityscape-street', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传店铺或街景参考图。', '/image-studio/templates/xhs-cover.webp'),
        ('seed-020', '穿搭种草封面', '适合服饰穿搭、鞋包推荐和达人账号封面。', 'Create a fashion social post cover for {{subject}}, full outfit composition, clean urban background, stylish model pose, soft editorial lighting, space for Chinese title {{text}}.', 'social-media-post', 'photography', 'influencer-model', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传服饰参考图。', '/image-studio/templates/xhs-cover.webp'),
        ('seed-021', '知识清单封面', '适合教程、清单、复盘和方法论内容。', 'Create an educational social cover for {{subject}}, neat checklist layout, soft pastel blocks, icons and blank text cards, clear hierarchy, Chinese title area {{text}}, modern editorial style.', 'social-media-post', 'illustration', 'diagram-chart', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/xhs-cover.webp'),
        ('seed-022', '宠物账号封面', '适合宠物日常、用品推荐和萌宠内容。', 'Create a cute social media cover for {{subject}}, pet centered, bright home setting, playful props, soft natural light, clean title space {{text}}, warm friendly mood.', 'social-media-post', 'photography', 'animal-creature', 'grok-2-image', '1024x1024', 'optional', FALSE, '可上传宠物参考图。', '/image-studio/templates/xhs-cover.webp'),
        ('seed-023', '宽屏视频封面', '适合知识视频、测评视频和栏目封面。', 'Create a high-click video thumbnail for {{subject}}, bold central object, cinematic contrast, large blank area for Chinese headline {{text}}, energetic composition, no tiny unreadable details.', 'youtube-thumbnail', 'cinematic-film-still', 'product', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传产品或人物参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-024', '人物访谈封面', '适合播客、访谈、课程和纪录片视频。', 'Create a video thumbnail for an interview about {{subject}}, expressive portrait, dramatic side lighting, clean dark background, bold space for Chinese title {{text}}, premium media style.', 'youtube-thumbnail', 'cinematic-film-still', 'portrait-selfie', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传人物参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-025', '游戏解说封面', '适合游戏视频、直播预告和攻略缩略图。', 'Create a dynamic gaming video thumbnail for {{subject}}, dramatic character action, glowing effects, high contrast, wide composition, space for Chinese title {{text}}, no copyrighted logos.', 'youtube-thumbnail', 'cyberpunk-sci-fi', 'character', 'grok-2-image', '1792x1024', 'optional', FALSE, '可上传角色或场景参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-026', '活动竖版海报', '适合线下活动、讲座、展会、沙龙宣传。', 'Design a vertical event poster for {{subject}}, strong visual hierarchy, expressive hero scene, clean blank zones for Chinese title {{text}} and date, print ready composition.', 'poster-flyer', 'illustration', 'text-typography', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-027', '复古音乐海报', '适合音乐会、派对、演出和文化活动。', 'Create a retro music event poster for {{subject}}, vintage print texture, bold shapes, warm limited color palette, large Chinese headline area {{text}}, energetic but readable.', 'poster-flyer', 'retro-vintage', 'text-typography', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-028', '国风节气海报', '适合节气、节日、文化宣传和文旅活动。', 'Create a Chinese ink style poster for {{subject}}, elegant negative space, ink mountains and seasonal object, subtle seal-like accent, large blank Chinese title area {{text}}.', 'poster-flyer', 'ink-chinese-style', 'landscape-nature', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),

        ('seed-029', '职业头像照', '适合个人主页、简历、商务头像和平台头像。', 'Create a professional profile portrait for {{subject}}, clean studio background, confident expression, soft key light, realistic skin texture, cropped for avatar, no text.', 'profile-avatar', 'photography', 'portrait-selfie', 'gpt-image-2', '1024x1024', 'required', TRUE, '需要上传人物参考图以保持相似度。', '/demo-gpt-image.webp'),
        ('seed-030', 'Q版头像贴纸', '适合社交头像、会员头像和社区形象。', 'Create a chibi avatar sticker for {{subject}}, cute rounded proportions, bright eyes, simple background, crisp outline, expressive pose, high quality icon style.', 'profile-avatar', 'chibi-q-style', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传人物或角色参考图。', '/demo-gpt-image.webp'),
        ('seed-031', '动漫人物头像', '适合二次元头像、角色设定和社群头像。', 'Create an anime profile avatar for {{subject}}, clean linework, soft cel shading, expressive eyes, simple gradient background, shoulder-up composition, polished character art.', 'profile-avatar', 'anime-manga', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传角色参考图。', '/demo-gpt-image.webp'),
        ('seed-032', '油画人物肖像', '适合艺术头像、纪念图和高级人物形象。', 'Create an oil painting style portrait for {{subject}}, classical lighting, rich brush texture, dignified composition, warm muted palette, realistic face structure, no text.', 'profile-avatar', 'oil-painting', 'portrait-selfie', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传人物参考图。', '/demo-gpt-image.webp'),
        ('seed-033', '水彩宠物头像', '适合宠物纪念、账号头像和礼品图。', 'Create a watercolor pet portrait for {{subject}}, soft paper texture, gentle washes, clean white margin, expressive eyes, charming avatar crop, no text.', 'profile-avatar', 'watercolor', 'animal-creature', 'gpt-image-1', '1024x1024', 'required', TRUE, '需要上传宠物参考图。', '/demo-gpt-image.webp'),
        ('seed-034', '赛博角色头像', '适合游戏账号、科幻角色和虚拟人头像。', 'Create a cyberpunk avatar for {{subject}}, neon rim light, futuristic accessories, dark city background, sharp facial silhouette, high contrast, square profile crop.', 'profile-avatar', 'cyberpunk-sci-fi', 'character', 'grok-2-image', '1024x1024', 'optional', FALSE, '可上传角色参考图。', '/demo-gpt-image.webp'),

        ('seed-035', '产品对比信息图', '适合卖点对比、规格对比和选择指南。', 'Create a clean infographic for {{subject}}, three comparison columns, icon placeholders, clear visual hierarchy, Chinese title area {{text}}, minimal palette, no tiny unreadable text.', 'infographic-edu-visual', 'minimalism', 'diagram-chart', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-036', '流程步骤图', '适合教程、SOP、产品流程和服务说明。', 'Create an isometric process infographic for {{subject}}, four connected steps, simple icons, soft shadows, clean white background, blank Chinese labels, business presentation quality.', 'infographic-edu-visual', 'isometric', 'diagram-chart', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-037', '知识科普长图', '适合课程、科普、教育账号和内容营销。', 'Create an educational long poster for {{subject}}, friendly illustrated sections, simple charts, readable empty text zones, soft colors, vertical mobile-first layout.', 'infographic-edu-visual', 'illustration', 'diagram-chart', 'seedream-4.5', '1024x1792', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-038', '城市数据地图', '适合城市报告、出行数据和地理主题内容。', 'Create a stylized city data map for {{subject}}, clean map blocks, subtle route lines, infographic labels as blank cards, blue green palette, professional report style.', 'infographic-edu-visual', 'isometric', 'cityscape-street', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-039', '医学健康说明图', '适合健康科普、护理指南和服务介绍。', 'Create a friendly medical educational visual for {{subject}}, simple anatomical icons, clean cards, soft blue and green palette, no frightening imagery, blank Chinese caption areas.', 'infographic-edu-visual', 'illustration', 'diagram-chart', 'gemini-2.5-flash-image', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-040', '结构拆解说明图', '适合机械、数码、工具和空间结构解释。', 'Create a technical exploded diagram for {{subject}}, precise parts separated in layers, thin guide lines, neutral background, blank callout boxes, professional manual style.', 'infographic-edu-visual', 'sketch-line-art', 'diagram-chart', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传结构参考图。', '/image-studio/templates/free-create.webp'),

        ('seed-041', '三格漫画分镜', '适合产品故事、角色日常和社媒漫画。', 'Create a three-panel comic storyboard for {{subject}}, clear panel borders, consistent character design, expressive actions, simple Chinese dialogue blank bubbles, clean graphic novel style.', 'comic-storyboard', 'comic-graphic-novel', 'character', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传角色参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-042', '产品使用故事板', '适合详情页、广告脚本和短视频分镜预演。', 'Create a six-frame storyboard showing {{subject}} being used, consistent product appearance, clear camera angles, simple sketch line art, blank note area under each frame.', 'comic-storyboard', 'sketch-line-art', 'product', 'gpt-image-2', '1536x1024', 'required', TRUE, '需要上传产品参考图以保持一致。', '/image-studio/templates/free-create.webp'),
        ('seed-043', '校园漫画场景', '适合青春、教育、课程和轻剧情内容。', 'Create a manga storyboard scene about {{subject}}, school corridor background, two characters interacting, expressive facial reactions, clean black and white manga linework.', 'comic-storyboard', 'anime-manga', 'group-couple', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传角色参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-044', '科幻分镜概念', '适合短片、游戏剧情和世界观设定。', 'Create a cinematic sci-fi storyboard for {{subject}}, wide panels, futuristic city, neon atmosphere, dramatic silhouettes, consistent vehicle design, no readable text.', 'comic-storyboard', 'cyberpunk-sci-fi', 'vehicle', 'grok-2-image', '1792x1024', 'optional', FALSE, '可上传场景或载具参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-045', '儿童绘本分镜', '适合亲子故事、绘本和教育内容。', 'Create a gentle picture book storyboard for {{subject}}, four soft watercolor panels, friendly characters, warm colors, simple scene progression, no random text.', 'comic-storyboard', 'watercolor', 'animal-creature', 'gpt-image-1', '1536x1024', 'optional', FALSE, '可上传角色参考图。', '/image-studio/templates/free-create.webp'),

        ('seed-046', '像素游戏道具', '适合游戏背包图标、道具图标和像素素材。', 'Create pixel art game item icons for {{subject}}, 16-bit style, transparent-feeling simple background, crisp silhouette, four variations, readable small scale, no text.', 'game-asset', 'pixel-art', 'product', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-047', 'Q版游戏角色', '适合休闲游戏、头像、贴纸和角色立绘。', 'Create a chibi game character for {{subject}}, full body, clear silhouette, joyful expression, simple equipment, soft cel shading, neutral background, ready as character asset.', 'game-asset', 'chibi-q-style', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传角色参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-048', '等距游戏建筑', '适合模拟经营、地图建筑和场景组件。', 'Create an isometric game building asset for {{subject}}, clean geometry, stylized materials, visible roof and facade, soft shadow, isolated on light background, no text.', 'game-asset', 'isometric', 'architecture-interior', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-049', '幻想生物设定', '适合卡牌、RPG、怪物设计和概念图。', 'Create a fantasy creature concept for {{subject}}, full body pose, detailed silhouette, material notes as blank side panels, dramatic but readable design, concept art quality.', 'game-asset', 'illustration', 'animal-creature', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传风格或生物参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-050', '载具概念设计', '适合赛车、科幻载具、机甲和交通工具设定。', 'Create a game vehicle concept for {{subject}}, three-quarter view, clean orthographic detail, futuristic materials, neutral background, side detail sketches, no text.', 'game-asset', '3d-render', 'vehicle', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传造型参考图。', '/image-studio/templates/free-create.webp'),

        ('seed-051', 'SaaS 首屏视觉', '适合官网首屏、产品宣传和转化落地页。', 'Create a SaaS website hero visual for {{subject}}, realistic dashboard preview, clean typography zones as blanks, subtle product UI depth, professional B2B style, no fake readable data.', 'app-web-design', 'minimalism', 'diagram-chart', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传产品界面参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-052', '移动应用展示图', '适合应用商店、官网和功能介绍图。', 'Create a mobile app showcase image for {{subject}}, three phone mockups, clean interface cards, brand color {{color}}, bright background, polished product marketing style.', 'app-web-design', '3d-render', 'diagram-chart', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传界面截图参考。', '/image-studio/templates/free-create.webp'),
        ('seed-053', '后台系统界面图', '适合管理系统、数据看板和企业产品展示。', 'Create a professional admin dashboard visual for {{subject}}, dense but organized data panels, restrained colors, crisp UI layout, no random text, enterprise software style.', 'app-web-design', 'minimalism', 'diagram-chart', 'gemini-2.5-flash-image', '1536x1024', 'optional', FALSE, '可上传界面风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-054', '电商落地页首图', '适合促销页、品牌官网和产品系列页面。', 'Create an e-commerce landing page hero image for {{subject}}, product family display, clean module-like layout, premium lighting, space for Chinese headline {{text}}, high conversion visual.', 'app-web-design', 'photography', 'product', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传商品或页面风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-055', '应用图标套组', '适合功能图标、组件库和轻量品牌视觉。', 'Create a set of app icons for {{subject}}, consistent rounded square grid, minimal vector-like shapes, five icons, clean color system {{color}}, no letters or text.', 'app-web-design', 'illustration', 'abstract-background', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),

        ('seed-056', '抽象品牌背景', '适合封面背景、活动背景和品牌氛围图。', 'Create an abstract brand background for {{subject}}, layered translucent shapes, sophisticated color palette {{color}}, subtle grain, high resolution, no text, flexible crop.', 'free-creation', 'minimalism', 'abstract-background', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-057', '电影概念场景', '适合概念图、剧本氛围、故事世界观。', 'Create a cinematic concept scene for {{subject}}, wide establishing shot, dramatic light, strong atmosphere, detailed environment, realistic film still mood, no text.', 'free-creation', 'cinematic-film-still', 'landscape-nature', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传场景参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-058', '国风水墨意境', '适合诗意海报、文旅视觉和艺术封面。', 'Create a Chinese ink painting inspired image for {{subject}}, layered mountains, mist, elegant negative space, subtle red accent, poetic composition, no random text.', 'free-creation', 'ink-chinese-style', 'landscape-nature', 'seedream-4.5', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-059', '复古未来城市', '适合科幻设定、音乐封面和概念艺术。', 'Create a retro futuristic cityscape for {{subject}}, neon signs, rainy street reflections, vintage sci-fi palette, cinematic perspective, atmospheric depth, no readable logo.', 'free-creation', 'cyberpunk-sci-fi', 'cityscape-street', 'grok-2-image', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-060', '手绘线稿构思', '适合快速构图、草图灵感和产品概念草案。', 'Create a clean sketch sheet for {{subject}}, multiple hand drawn concept thumbnails, line art, annotations as blank boxes, design exploration mood, white paper background.', 'free-creation', 'sketch-line-art', 'abstract-background', 'gemini-2.5-flash-image', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),

        ('seed-061', '包装盒正面设计', '适合食品、美妆、日用品包装正面方案。', 'Design a front-facing packaging box concept for {{subject}}, clean dieline-aware layout, hero product illustration, blank Chinese brand and benefit zones, realistic cardboard texture, retail shelf ready.', 'packaging-design', 'flat-vector', 'packaging-label', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传品牌色、现有包装或产品参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-062', '瓶贴包装样机', '适合饮品、香薰、护肤品等瓶身标签展示。', 'Create a bottle label mockup for {{subject}}, cylindrical product centered, clean label area, premium paper texture, realistic reflections, soft studio light, blank Chinese text zones.', 'packaging-design', 'photography', 'packaging-label', 'gpt-image-2', '1024x1536', 'required', TRUE, '建议上传瓶型或现有标签参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-063', '咖啡袋包装系列', '适合咖啡、茶叶、零食等袋装产品系列。', 'Create a packaging series visual for {{subject}}, three standing pouches, consistent brand system, distinct flavor color bands {{color}}, realistic kraft and foil texture, no random small text.', 'packaging-design', 'photography', 'food-drink', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传包装正面或品牌参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-064', '高端礼盒开箱图', '适合礼品、茶礼、月饼、美妆套装和会员礼盒。', 'Create a premium gift box unboxing visual for {{subject}}, open rigid box, layered insert tray, elegant ribbon, refined shadows, luxury editorial composition, blank logo area.', 'packaging-design', 'luxury-editorial', 'packaging-label', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传礼盒结构或品牌色参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-065', '环保纸袋包装', '适合文创、餐饮、服饰和线下门店包装袋。', 'Create an eco paper bag packaging mockup for {{subject}}, natural kraft material, clean logo placeholder, small tag and handle detail, warm daylight, sustainable retail mood.', 'packaging-design', 'minimalism', 'packaging-label', 'gpt-image-1', '1024x1536', 'optional', FALSE, '可上传标志或门店风格参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-066', '品牌视觉板', '适合新品牌、活动主视觉和风格提案。', 'Create a brand identity moodboard for {{subject}}, logo symbol placeholder, color swatches {{color}}, typography blocks without readable filler text, product photo tiles, clean presentation layout.', 'brand-identity', 'minimalism', 'logo-symbol', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传标志、色卡或产品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-067', '标志延展图形', '适合把品牌关键词转成可用图形符号方向。', 'Create logo symbol exploration for {{subject}}, six clean vector-like marks, consistent grid, black and accent color {{color}}, no readable letters, professional identity design sheet.', 'brand-identity', 'flat-vector', 'logo-symbol', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-068', '品牌吉祥物设定', '适合平台、店铺、活动和会员体系角色。', 'Create a brand mascot design sheet for {{subject}}, front view and three expressive poses, friendly proportions, consistent outfit, clean white background, blank name area.', 'brand-mascot', 'chibi-q-style', 'character', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传品牌标志或角色参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-069', '表情包贴纸套组', '适合社群、会员、客服和品牌角色运营。', 'Create a sticker pack for {{subject}}, eight expressive mascot emotions, thick white sticker outline, consistent character design, transparent-feeling light background, no text.', 'brand-mascot', 'sticker-icon', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传角色参考图以保持一致。', '/image-studio/templates/free-create.webp'),
        ('seed-070', '客服虚拟人形象', '适合客服助手、智能体、社群运营和产品角色。', 'Create a friendly virtual assistant character for {{subject}}, half-body pose, modern work outfit, approachable expression, clean product UI background, brand color {{color}}, no text.', 'brand-mascot', 'illustration', 'character', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传品牌色或角色风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-071', '应用空状态插画', '适合应用缺省页、加载页、空列表和错误页。', 'Create a mobile app empty state illustration for {{subject}}, simple flat vector scene, clear central metaphor, soft color system {{color}}, no readable interface text.', 'app-web-design', 'flat-vector', 'diagram-chart', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-072', '三维功能图标', '适合官网、应用、价格页和功能介绍模块。', 'Create a set of five 3D feature icons for {{subject}}, consistent material and lighting, rounded shapes, clear silhouettes, brand color {{color}}, isolated on light background.', 'app-web-design', '3d-render', 'abstract-background', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-073', '企业数据看板首图', '适合 SaaS、CRM、财务系统和运营后台展示。', 'Create an enterprise analytics hero visual for {{subject}}, dense but readable dashboard panels, realistic product screenshot style, neutral palette, no fake sensitive data, professional B2B mood.', 'app-web-design', 'minimalism', 'diagram-chart', 'gemini-2.5-flash-image', '1792x1024', 'optional', FALSE, '可上传真实界面截图作为结构参考。', '/image-studio/templates/free-create.webp'),
        ('seed-074', 'AI 助手产品界面', '适合智能助手、知识库、客服机器人和自动化产品展示。', 'Create a polished AI assistant product interface visual for {{subject}}, chat panel, action cards, workflow sidebar, clean Chinese UI placeholders, soft depth, modern SaaS style.', 'app-web-design', 'minimalism', 'diagram-chart', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传产品界面或品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-075', '金融科技首屏视觉', '适合支付、理财、数据风控和金融 SaaS 官网。', 'Create a fintech website hero image for {{subject}}, secure data visualization, card and chart elements, deep trust feeling, clear headline space, polished commercial UI visual.', 'app-web-design', '3d-render', 'diagram-chart', 'gpt-image-2', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-076', '在线课程封面', '适合课程页、训练营、知识付费和学习栏目。', 'Create an online course cover for {{subject}}, teacher or topic object centered, structured learning cards, warm trustworthy palette, large Chinese title space {{text}}, education marketing style.', 'education-course', 'illustration', 'diagram-chart', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传讲师照片或课程视觉参考。', '/image-studio/templates/free-create.webp'),
        ('seed-077', '招聘岗位海报', '适合招聘、雇主品牌、社群招募和校园宣讲。', 'Design a recruitment poster for {{subject}}, confident workplace scene, clean hierarchy, blank Chinese title and role zones {{text}}, professional but energetic, no random letters.', 'education-course', 'illustration', 'group-couple', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-078', '房地产项目海报', '适合楼盘、租赁、民宿和商业空间招商视觉。', 'Create a real estate marketing poster for {{subject}}, elegant architecture exterior, warm evening light, premium landscape, blank Chinese headline area {{text}}, clean sales layout.', 'poster-flyer', 'luxury-editorial', 'architecture-interior', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传建筑外观或户型参考。', '/image-studio/templates/free-create.webp'),
        ('seed-079', '旅行路线长图', '适合城市攻略、景区路线、假期计划和本地推荐。', 'Create a travel itinerary long poster for {{subject}}, route line across illustrated landmarks, numbered blank stop cards, friendly map style, vertical mobile layout, no tiny text.', 'local-life-map', 'illustration', 'map-location', 'gpt-image-2', '1024x1792', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-080', '婚礼请柬主视觉', '适合婚礼邀请、电子请柬、迎宾牌和仪式物料。', 'Design a wedding invitation visual for {{subject}}, elegant floral frame, refined paper texture, soft romantic light, blank Chinese names and date area {{text}}, premium stationery mood.', 'wedding-event', 'watercolor', 'wedding-party', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传新人照片、花艺或配色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-081', '生日派对海报', '适合生日会、亲子派对、门店活动和社区庆典。', 'Create a birthday party poster for {{subject}}, joyful decorations, layered balloons, cake centerpiece, bright friendly colors {{color}}, blank Chinese title area {{text}}, no random text.', 'wedding-event', 'children-book', 'wedding-party', 'gpt-image-1', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-082', '餐厅菜单封面', '适合餐厅菜单、外卖页、餐饮品牌和新品栏目。', 'Create a restaurant menu cover for {{subject}}, appetizing hero dish, clean editorial layout, warm table light, blank Chinese menu title area {{text}}, premium food photography.', 'product-marketing', 'photography', 'food-drink', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传菜品或餐厅风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-083', '城市美食地图', '适合本地生活账号、城市指南和商圈推荐。', 'Create a city food map for {{subject}}, illustrated streets and landmarks, food icons, numbered blank location labels, cheerful local guide style, mobile friendly composition.', 'local-life-map', 'flat-vector', 'map-location', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-084', '展览活动海报', '适合艺术展、博物馆、发布会和品牌快闪。', 'Design an exhibition poster for {{subject}}, strong curatorial composition, one symbolic artwork object, refined grid, blank Chinese title and venue areas {{text}}, print poster quality.', 'poster-flyer', 'minimalism', 'text-typography', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传作品或展陈风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-085', '客厅软装改造', '适合家装、软装、家具搭配和空间灵感图。', 'Create an interior redesign concept for {{subject}}, modern living room, improved furniture layout, coherent color palette {{color}}, natural light, realistic materials, no text overlay.', 'interior-redesign', 'photography', 'furniture-home', 'gpt-image-2', '1536x1024', 'required', TRUE, '建议上传原始空间照片，便于保持房间结构。', '/image-studio/templates/free-create.webp'),
        ('seed-086', '卧室氛围改造', '适合卧室、民宿、样板间和家居内容。', 'Create a bedroom makeover concept for {{subject}}, cozy layered bedding, warm lamps, tidy storage, realistic proportions, calm color palette {{color}}, editorial interior photography.', 'interior-redesign', 'photography', 'furniture-home', 'gpt-image-2', '1536x1024', 'required', TRUE, '建议上传原始空间或户型参考。', '/image-studio/templates/free-create.webp'),
        ('seed-087', '门店陈列设计', '适合零售店、快闪店、展台和橱窗陈列。', 'Create a retail store display concept for {{subject}}, clear customer path, product shelves, hero display table, warm commercial lighting, brand color accents {{color}}, no random signs.', 'interior-redesign', '3d-render', 'architecture-interior', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传店铺照片或品牌参考。', '/image-studio/templates/free-create.webp'),
        ('seed-088', '办公空间概念', '适合联合办公、团队办公室、会议室和企业空间。', 'Create an office interior concept for {{subject}}, efficient desk layout, meeting pod, plants, balanced lighting, modern professional atmosphere, realistic perspective, no text.', 'interior-redesign', 'photography', 'architecture-interior', 'gemini-2.5-flash-image', '1536x1024', 'optional', FALSE, '可上传平面图或现场照片。', '/image-studio/templates/free-create.webp'),
        ('seed-089', '露台花园改造', '适合阳台、花园、民宿庭院和户外休闲空间。', 'Create a terrace garden makeover for {{subject}}, layered plants, outdoor seating, warm string lights, realistic weathered materials, inviting evening mood, no text.', 'interior-redesign', 'photography', 'landscape-nature', 'gpt-image-1', '1536x1024', 'optional', FALSE, '可上传原始露台或花园照片。', '/image-studio/templates/free-create.webp'),
        ('seed-090', '建筑外立面概念', '适合店铺门头、民宿外观、建筑改造和空间提案。', 'Create an architectural facade concept for {{subject}}, clear entrance, material palette, signage blank area, realistic street context, evening commercial lighting, premium renovation mood.', 'interior-redesign', '3d-render', 'architecture-interior', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传建筑外观或门头照片。', '/image-studio/templates/free-create.webp'),
        ('seed-091', '服装虚拟试穿', '适合服饰店、穿搭预览、款式上身和电商转化。', 'Create a virtual try-on image for {{subject}}, model wearing the clothing accurately, natural standing pose, clean studio background, realistic fabric drape, no body distortion, no text.', 'virtual-try-on', 'fashion-editorial', 'fashion-item', 'gpt-image-2', '1024x1536', 'required', TRUE, '需要上传服装或人物参考图以保持款式。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-092', '珠宝佩戴大片', '适合首饰、腕表、礼品和高端配饰推广。', 'Create a luxury jewelry wearing shot for {{subject}}, elegant hand or neck close-up, sparkling detail, soft premium lighting, refined background, commercial editorial crop.', 'virtual-try-on', 'luxury-editorial', 'jewelry-watch', 'gpt-image-2', '1024x1536', 'required', TRUE, '建议上传珠宝产品或佩戴参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-093', '眼镜试戴预览', '适合眼镜、墨镜、镜框款式和个人形象参考。', 'Create a realistic eyewear try-on portrait for {{subject}}, glasses aligned naturally on face, clean lighting, accurate frame shape, friendly expression, no text.', 'virtual-try-on', 'photography', 'portrait-selfie', 'gpt-image-2', '1024x1024', 'required', TRUE, '需要上传人物正脸和眼镜参考图。', '/demo-gpt-image.webp'),
        ('seed-094', '发型改造预览', '适合理发、美发、造型咨询和头像改造。', 'Create a hairstyle makeover preview for {{subject}}, natural hair texture, flattering face framing, realistic salon lighting, before-after style composition with blank labels, no random text.', 'photo-retouching', 'photography', 'portrait-selfie', 'gpt-image-2', '1536x1024', 'required', TRUE, '需要上传人物照片作为参考。', '/demo-gpt-image.webp'),
        ('seed-095', '妆容风格预览', '适合彩妆种草、妆容提案、美业门店和个人形象。', 'Create a makeup style preview for {{subject}}, clean beauty portrait, accurate skin texture, balanced color palette {{color}}, glossy editorial lighting, no heavy distortion.', 'virtual-try-on', 'luxury-editorial', 'beauty-cosmetics', 'gpt-image-2', '1024x1536', 'required', TRUE, '需要上传人物或妆容参考图。', '/demo-gpt-image.webp'),
        ('seed-096', '老照片修复上色', '适合家庭老照片、纪念照和历史影像修复。', 'Restore and colorize {{subject}}, preserve original facial structure and clothing details, remove scratches and stains, natural skin tones, respectful documentary quality, no invented text.', 'photo-retouching', 'photography', 'portrait-selfie', 'gpt-image-2', '1024x1536', 'required', TRUE, '需要上传待修复照片。', '/demo-gpt-image.webp'),
        ('seed-097', '家庭合影写真', '适合家庭纪念、节日祝福、亲子内容和相册封面。', 'Create a warm family portrait for {{subject}}, natural smiles, balanced group composition, soft studio light, elegant neutral background, realistic proportions, no text.', 'profile-avatar', 'photography', 'group-couple', 'gpt-image-2', '1536x1024', 'required', TRUE, '需要上传人物参考图以保持相似度。', '/demo-gpt-image.webp'),
        ('seed-098', '儿童绘本头像', '适合亲子账号、儿童角色、课程头像和绘本人物。', 'Create a children book style portrait for {{subject}}, gentle expression, soft rounded shapes, warm colors, paper texture, friendly avatar crop, no text.', 'profile-avatar', 'children-book', 'baby-child', 'gpt-image-1', '1024x1024', 'optional', FALSE, '可上传儿童或角色参考图。', '/demo-gpt-image.webp'),
        ('seed-099', '婚纱写真概念', '适合婚纱样片、情侣纪念、旅拍灵感和婚礼物料。', 'Create a wedding portrait concept for {{subject}}, romantic couple pose, elegant dress details, soft natural scenery, premium photography, graceful composition, no text.', 'wedding-event', 'luxury-editorial', 'wedding-party', 'gpt-image-2', '1024x1536', 'required', TRUE, '建议上传人物或服装参考图。', '/demo-gpt-image.webp'),
        ('seed-100', '宠物商品场景图', '适合宠物用品、零食、玩具和服务宣传。', 'Create a pet product lifestyle photo for {{subject}}, pet interacting naturally with the product, cozy home background, clear product visibility, warm commercial lighting, no text.', 'product-marketing', 'photography', 'animal-creature', 'grok-2-image', '1536x1024', 'optional', FALSE, '可上传宠物或商品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-101', '健身课程海报', '适合健身房、瑜伽课、训练营和运动社群。', 'Create a fitness course poster for {{subject}}, energetic athletic pose, clean studio or outdoor setting, strong hierarchy, blank Chinese title area {{text}}, motivational mood.', 'education-course', 'photography', 'sports-fitness', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传教练或课程视觉参考。', '/image-studio/templates/free-create.webp'),
        ('seed-102', '运动鞋动态广告', '适合鞋履、运动装备、潮流新品和广告投放。', 'Create a dynamic sneaker advertising image for {{subject}}, shoe in sharp focus, motion trail, textured court floor, dramatic lighting, brand color accents {{color}}, no text.', 'product-marketing', 'fashion-editorial', 'sports-fitness', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传鞋款参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-103', '瑜伽冥想视觉', '适合健康生活、心理疗愈、课程和社区内容。', 'Create a calm yoga wellness visual for {{subject}}, balanced pose, soft daylight, natural materials, spacious composition, soothing palette {{color}}, no text.', 'healthcare-visual', 'photography', 'sports-fitness', 'gpt-image-1', '1536x1024', 'optional', FALSE, '可上传人物或场景参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-104', '医疗器械展示', '适合医疗设备、健康硬件、护理产品和服务介绍。', 'Create a clean medical device product image for {{subject}}, sterile bright background, accurate device structure, soft blue green accents, professional healthcare lighting, no text.', 'healthcare-visual', 'photography', 'medical-health', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传设备外观参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-105', '诊所服务海报', '适合口腔、皮肤、体检、康复和护理门店宣传。', 'Design a healthcare service poster for {{subject}}, trustworthy clinic environment, friendly professional staff, clean blank Chinese title area {{text}}, calm blue green palette.', 'healthcare-visual', 'illustration', 'medical-health', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-106', '幻想小说封面', '适合小说、故事专栏、角色世界观和书封提案。', 'Create a fantasy book cover for {{subject}}, dramatic central character silhouette, rich environment, elegant blank title area {{text}}, cinematic lighting, professional cover composition.', 'book-album-cover', 'illustration', 'character', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-107', '音乐专辑封面', '适合单曲、播客、歌单、音乐人和栏目包装。', 'Create an album cover for {{subject}}, strong square composition, emotional abstract scene, refined color palette {{color}}, space for short Chinese title {{text}}, no random letters.', 'book-album-cover', 'retro-vintage', 'music-stage', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传歌手或情绪参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-108', '播客栏目封面', '适合访谈、知识音频、视频号栏目和电台视觉。', 'Create a podcast cover for {{subject}}, clear central symbol, balanced host portrait or microphone motif, clean Chinese title area {{text}}, modern media brand style.', 'book-album-cover', 'minimalism', 'music-stage', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传主持人照片或栏目标志。', '/image-studio/templates/free-create.webp'),
        ('seed-109', '桌游卡牌插画', '适合桌游、卡牌、角色技能和收藏卡。', 'Create a board game card illustration for {{subject}}, central character or object, decorative border, blank stat and title zones, rich fantasy detail, no readable fake text.', 'game-asset', 'illustration', 'character', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传角色或卡牌风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-110', '塔罗牌风格图', '适合占卜卡、品牌活动、文创周边和艺术卡。', 'Create a tarot card inspired image for {{subject}}, symbolic central figure, ornate border, mystical but tasteful palette, blank title banner, high detail illustration.', 'free-creation', 'retro-vintage', 'character', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-111', '动漫角色三视图', '适合角色设计、IP 设定、游戏立绘和动画前期。', 'Create an anime character turnaround sheet for {{subject}}, front side and back views, consistent outfit, clean white background, small expression row, no text.', 'brand-mascot', 'anime-manga', 'character', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传角色设定或服装参考。', '/image-studio/templates/free-create.webp'),
        ('seed-112', '等距城市导览图', '适合园区、商圈、景区、城市活动和地图视觉。', 'Create an isometric city guide map for {{subject}}, landmarks, roads, tiny people and vehicles, clean route path, blank label cards, bright informative style.', 'local-life-map', 'isometric', 'map-location', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-113', '地铁路线信息图', '适合交通指南、活动路线、商圈动线和城市说明。', 'Create a metro route infographic for {{subject}}, simplified colored transit lines, station dots, blank label areas, clean diagram style, high readability, no fake station names.', 'infographic-edu-visual', 'flat-vector', 'map-location', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-114', '食谱步骤卡', '适合菜谱、烘焙、营养餐和厨房教程。', 'Create a recipe step card for {{subject}}, four illustrated cooking steps, ingredient icons, blank Chinese instruction areas, warm kitchen palette, clean mobile layout.', 'infographic-edu-visual', 'illustration', 'food-drink', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-115', '茶饮国风海报', '适合茶饮、文旅、餐饮新品和节气营销。', 'Create a Chinese style tea poster for {{subject}}, elegant tea set, ink wash background, seasonal plant, poetic negative space, blank Chinese title area {{text}}, refined mood.', 'product-marketing', 'ink-chinese-style', 'food-drink', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传饮品或品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-116', '古镇文旅海报', '适合城市文旅、景区宣传、民宿推广和活动封面。', 'Create a cultural travel poster for {{subject}}, ancient town street, lanterns, misty morning light, elegant Chinese title space {{text}}, refined tourism campaign quality.', 'poster-flyer', 'ink-chinese-style', 'architecture-interior', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传景区或建筑参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-117', '课堂黑板知识图', '适合教育机构、课程推广、知识点总结和学习社群。', 'Create a classroom blackboard educational visual for {{subject}}, hand drawn diagrams, blank chalk label zones, friendly teacher desk props, warm school atmosphere, readable composition.', 'education-course', 'sketch-line-art', 'diagram-chart', 'gpt-image-1', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-118', '实验室科普图', '适合科学课程、实验说明、研究报告和机构宣传。', 'Create a science lab educational illustration for {{subject}}, glassware and instruments, clean process panels, blank Chinese caption areas, bright trustworthy palette, no random formulas.', 'infographic-edu-visual', 'illustration', 'diagram-chart', 'gemini-2.5-flash-image', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-119', '气候报告图表', '适合 ESG、环保报告、公益传播和数据科普。', 'Create a climate report infographic for {{subject}}, globe and weather layers, simple charts, blank data cards, professional green blue palette, clear editorial hierarchy.', 'infographic-edu-visual', 'flat-vector', 'diagram-chart', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-120', '太空科幻海报', '适合科幻活动、课程封面、游戏宣发和概念创作。', 'Create a space sci-fi poster for {{subject}}, astronaut or spacecraft focal point, deep star field, dramatic light, bold blank Chinese title area {{text}}, cinematic poster composition.', 'free-creation', 'cyberpunk-sci-fi', 'landscape-nature', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-121', '信息流广告三图套组', '适合广告投放前快速生成三种点击角度。', 'Create three coordinated social ad creatives for {{subject}}, each with a different hook, clean product focus, blank Chinese headline zones {{text}}, consistent brand color {{color}}, high conversion layout.', 'ad-creative', 'editorial-layout', 'product', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传产品图和品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-122', '搜索广告横幅', '适合品牌词、品类词和活动投放横幅。', 'Create a search display banner for {{subject}}, compact product and benefit composition, strong left to right hierarchy, blank Chinese copy area {{text}}, clean performance marketing style.', 'ad-creative', 'clean-ui', 'product', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传商品或活动主视觉参考。', '/image-studio/templates/free-create.webp'),
        ('seed-123', '广告配色变体', '适合同一卖点快速测试不同颜色和氛围。', 'Create four A B creative variants for {{subject}}, same composition, different color moods {{color}}, product remains consistent, clear blank headline area, comparison grid, no random letters.', 'creative-variants', 'flat-vector', 'product', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传商品参考图以保持主体一致。', '/image-studio/templates/free-create.webp'),
        ('seed-124', '点击率封面变体', '适合视频号、短视频和广告落地页封面测试。', 'Create a high click cover image for {{subject}}, bold focal subject, strong contrast, emotional expression, large blank Chinese headline space {{text}}, energetic but uncluttered.', 'ad-creative', 'poster-typography', 'text-typography', 'seedream-4.5', '1792x1024', 'optional', FALSE, '可上传人物或商品参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-125', '再营销折扣图', '适合购物车召回、优惠券、会员复购和限时折扣。', 'Create a remarketing discount creative for {{subject}}, product centered, coupon card motif, urgency feeling, blank Chinese offer area {{text}}, bright commercial layout, no fake readable numbers.', 'ad-creative', 'illustration', 'currency-card', 'seedream-4.5', '1024x1024', 'optional', FALSE, '可上传商品或优惠样式参考。', '/image-studio/templates/free-create.webp'),
        ('seed-126', '直播间背景板', '适合直播带货、课程直播和发布会直播背景。', 'Create a livestream studio background for {{subject}}, product shelves and brand panels, clean host area, warm commercial lighting, brand color {{color}}, no readable random text.', 'live-commerce', '3d-render', 'signage-storefront', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传品牌色、直播间或商品参考。', '/image-studio/templates/free-create.webp'),
        ('seed-127', '直播商品讲解卡', '适合直播间弹窗、讲解卡和卖点提示图。', 'Create a livestream product explanation card for {{subject}}, one product image area, three benefit blocks, blank Chinese text fields {{text}}, high readability, clean commerce style.', 'live-commerce', 'clean-ui', 'diagram-chart', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传商品或直播间风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-128', '直播倒计时海报', '适合开播预告、预约提醒和秒杀倒计时。', 'Design a livestream countdown poster for {{subject}}, dramatic time card motif, product and host silhouette, blank Chinese schedule area {{text}}, energetic retail atmosphere.', 'live-commerce', 'poster-typography', 'text-typography', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传主播或商品参考。', '/image-studio/templates/free-create.webp'),
        ('seed-129', '主播形象贴片', '适合直播间角标、主播介绍和活动贴片。', 'Create a livestream host sticker for {{subject}}, friendly half body host portrait, bold outline, brand color accent {{color}}, blank name tag area, transparent-feeling background.', 'live-commerce', 'sticker-icon', 'business-person', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传主播照片以保持形象。', '/demo-gpt-image.webp'),
        ('seed-130', '直播福袋促销图', '适合抽奖、福袋、限量赠品和粉丝福利。', 'Create a livestream lucky bag promotion visual for {{subject}}, gift boxes, sparkling accents, product peeking out, blank Chinese promo area {{text}}, joyful e-commerce style.', 'live-commerce', 'illustration', 'gift-flower', 'seedream-4.5', '1024x1024', 'optional', FALSE, '可上传礼品或商品参考。', '/image-studio/templates/free-create.webp'),
        ('seed-131', '商品棚拍精修图', '适合常规商品图、目录图和投放主图。', 'Create a refined studio product photo for {{subject}}, clean seamless background, softbox reflections, accurate material texture, subtle shadow, catalog quality, no text.', 'product-photography', 'photography', 'product', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传商品参考图以保持外观。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-132', '微距材质卖点图', '适合布料、金属、食品、护肤质地和工艺细节。', 'Create a macro detail image for {{subject}}, extreme close-up, rich material texture, shallow depth of field, premium commercial lighting, tactile detail, no text.', 'product-photography', 'macro-detail', 'product', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传材质或产品参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-133', '商品组合陈列图', '适合套装、系列、家庭装和多 SKU 商品。', 'Create a product bundle arrangement for {{subject}}, several SKUs in a balanced pyramid composition, consistent scale, bright studio light, clean retail backdrop, no text.', 'product-photography', 'photography', 'product', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传多款商品参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-134', '透明亚克力展示台', '适合美妆、数码、小家电和高级商品场景。', 'Create a product hero image for {{subject}} on transparent acrylic display blocks, soft reflections, premium studio lighting, clean pastel background {{color}}, no text.', 'product-photography', 'product-render', 'product', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传产品图以保持造型。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-135', '商品换背景清洁图', '适合把参考商品放入更干净的商业场景。', 'Edit {{subject}} into a clean commercial background, preserve exact product shape and proportions, remove clutter, add soft realistic shadow, marketplace ready, no extra text.', 'photo-retouching', 'photography', 'product', 'gpt-image-2', '1024x1024', 'required', TRUE, '需要上传待处理商品图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-136', '手机应用样机图', '适合应用商店、官网首屏和功能宣传。', 'Create a mobile app mockup for {{subject}}, three phone devices showing clean interface placeholders, soft depth, brand color {{color}}, polished product marketing composition.', 'mockup-scene', 'clean-ui', 'phone-device', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传应用截图或界面风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-137', '海报墙样机', '适合展览海报、品牌海报、活动物料展示。', 'Create a poster wall mockup for {{subject}}, framed posters on a gallery wall, realistic paper and glass reflections, blank poster areas, refined interior lighting.', 'mockup-scene', 'photography', 'text-typography', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传海报图或展厅参考。', '/image-studio/templates/free-create.webp'),
        ('seed-138', 'T 恤印花样机', '适合服装周边、社群文化衫和活动物料。', 'Create a T shirt mockup for {{subject}}, front garment on a natural model or hanger, clear print area, realistic cotton texture, neutral studio background, no random text.', 'mockup-scene', 'fashion-editorial', 'apparel-model', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传图案或服装款式参考。', '/image-studio/templates/free-create.webp'),
        ('seed-139', '包装上架样机', '适合商超货架、集合店、药妆店和线下陈列。', 'Create a retail shelf mockup for {{subject}}, repeated packages aligned on shelf, clear front faces, realistic store lighting, premium merchandising, no fake readable labels.', 'mockup-scene', 'photography', 'packaging-label', 'gpt-image-2', '1536x1024', 'required', TRUE, '建议上传包装正面参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-140', '名片品牌样机', '适合品牌识别、个人名片和线下物料展示。', 'Create a business card and stationery mockup for {{subject}}, cards, letterhead, envelope, subtle paper texture, brand color {{color}}, blank logo and contact zones.', 'mockup-scene', 'minimalism', 'document-slide', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传标志或品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-141', '手机壁纸', '适合手机桌面、会员福利、社群素材和品牌活动。', 'Create a vertical mobile wallpaper for {{subject}}, immersive composition, clean focal area, rich but not noisy details, suitable for lock screen, no text.', 'wallpaper-background', 'illustration', 'abstract-background', 'gpt-image-2', '1024x1792', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-142', '电脑桌面壁纸', '适合品牌电脑壁纸、活动背景和工作空间视觉。', 'Create a desktop wallpaper for {{subject}}, wide cinematic composition, spacious negative area for icons, refined color palette {{color}}, high resolution, no text.', 'wallpaper-background', 'cinematic-film-still', 'landscape-nature', 'gpt-image-2', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-143', '直播虚拟背景', '适合视频会议、课程直播、播客和线上活动。', 'Create a virtual background for {{subject}}, professional room depth, tasteful shelves or brand panel, clear center area for speaker, soft lighting, no text.', 'wallpaper-background', 'photography', 'architecture-interior', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传品牌或房间风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-144', '渐变纹理底图', '适合封面、海报、PPT 和社交配图底图。', 'Create a sophisticated gradient texture background for {{subject}}, layered mesh color {{color}}, subtle grain, clean depth, flexible crop, no symbols or text.', 'wallpaper-background', 'minimalism', 'abstract-background', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-145', '品牌图案背景', '适合包装内衬、活动背景、社群物料和网站底纹。', 'Create a seamless brand pattern background for {{subject}}, repeated simple motifs, consistent spacing, brand color {{color}}, subtle premium texture, no readable words.', 'brand-identity', 'flat-vector', 'abstract-background', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传标志或图案参考。', '/image-studio/templates/free-create.webp'),
        ('seed-146', 'PPT 封面视觉', '适合项目汇报、路演、课程和商业提案。', 'Create a presentation cover visual for {{subject}}, clean business composition, strong title area {{text}}, subtle data or product motif, professional palette {{color}}, no random text.', 'document-presentation', 'document-clean', 'document-slide', 'gpt-image-2', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-147', '白皮书封面', '适合行业报告、技术白皮书、趋势洞察和下载页。', 'Create a white paper cover for {{subject}}, abstract industry motif, clean grid, large Chinese title area {{text}}, restrained professional color {{color}}, no fake small text.', 'document-presentation', 'document-clean', 'document-slide', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-148', '商业计划书封面', '适合融资路演、项目计划、招商方案和内部提案。', 'Create a business plan cover for {{subject}}, confident enterprise visual, subtle charts and city lights, clean title block {{text}}, polished corporate presentation style.', 'document-presentation', 'editorial-layout', 'business-person', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传企业标志或行业参考。', '/image-studio/templates/free-create.webp'),
        ('seed-149', '数据报告内页', '适合运营周报、市场分析、仪表盘截图和研究报告。', 'Create a data report page visual for {{subject}}, charts, KPI cards and clean annotations as blank areas, high information clarity, professional report layout.', 'document-presentation', 'clean-ui', 'diagram-chart', 'gemini-2.5-flash-image', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-150', '会议演示开场图', '适合峰会、培训、发布会和内部会议开场页。', 'Create a conference opening slide visual for {{subject}}, stage light feeling, large blank title zone {{text}}, subtle abstract background, professional event atmosphere.', 'document-presentation', 'minimalism', 'text-typography', 'seedream-4.5', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-151', '标准证件照', '适合证件、报名、简历和职业资料头像。', 'Create a standard ID photo for {{subject}}, neutral background, even lighting, front-facing portrait, natural skin tone, formal clothing, accurate head crop, no text.', 'resume-id-photo', 'photorealistic-portrait', 'portrait-selfie', 'gpt-image-2', '1024x1024', 'required', TRUE, '需要上传人物正脸照片。', '/demo-gpt-image.webp'),
        ('seed-152', '简历头像', '适合中文简历、求职平台、个人主页和作品集。', 'Create a resume profile portrait for {{subject}}, professional but friendly expression, clean office background, soft natural light, realistic face structure, square crop.', 'resume-id-photo', 'photorealistic-portrait', 'business-person', 'gpt-image-2', '1024x1024', 'required', TRUE, '需要上传人物参考图。', '/demo-gpt-image.webp'),
        ('seed-153', '职场主页形象', '适合商务社交主页、顾问介绍、创始人页面和个人品牌。', 'Create a professional personal brand portrait for {{subject}}, confident pose, modern workspace, refined wardrobe, clean depth of field, premium business photography.', 'resume-id-photo', 'luxury-editorial', 'business-person', 'gpt-image-2', '1024x1536', 'required', TRUE, '建议上传人物参考图以保持相似度。', '/demo-gpt-image.webp'),
        ('seed-154', '个人名片背景', '适合自由职业者、顾问、设计师和个人品牌名片。', 'Create a personal business card background for {{subject}}, subtle identity symbol, clean typography zones, paper texture, brand color {{color}}, no random letters.', 'resume-id-photo', 'minimalism', 'document-slide', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传个人标志或品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-155', '团队成员形象照', '适合官网团队页、招聘页、企业宣传和组织介绍。', 'Create a consistent team portrait style for {{subject}}, professional lighting, clean background, unified crop and wardrobe direction, approachable enterprise mood, no text.', 'resume-id-photo', 'photorealistic-portrait', 'group-couple', 'gpt-image-2', '1536x1024', 'required', TRUE, '需要上传团队成员参考图。', '/demo-gpt-image.webp'),
        ('seed-156', '春节节日海报', '适合春节祝福、门店活动、年货促销和品牌问候。', 'Create a Chinese New Year campaign poster for {{subject}}, festive red and gold accents, elegant lanterns and gift motifs, blank Chinese blessing area {{text}}, premium composition.', 'festival-campaign', 'ink-chinese-style', 'gift-flower', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传品牌色或商品参考。', '/image-studio/templates/free-create.webp'),
        ('seed-157', '中秋礼盒视觉', '适合月饼、茶礼、企业礼品和节日送礼。', 'Create a Mid Autumn gift campaign image for {{subject}}, moonlight, refined gift box, tea or pastry detail, elegant Chinese title area {{text}}, warm premium mood.', 'festival-campaign', 'luxury-editorial', 'packaging-label', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传礼盒或商品参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-158', '情人节礼物广告', '适合鲜花、珠宝、香水、甜品和礼品促销。', 'Create a Valentine gift advertising image for {{subject}}, romantic lighting, flowers and ribbon, product clearly visible, soft premium palette {{color}}, blank Chinese headline area.', 'festival-campaign', 'luxury-editorial', 'gift-flower', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传礼品或商品参考。', '/image-studio/templates/free-create.webp'),
        ('seed-159', '大促主会场视觉', '适合 618、双 11、周年庆和平台活动主图。', 'Create a major shopping festival hero visual for {{subject}}, energetic stage, product and coupon elements, strong blank Chinese headline area {{text}}, high conversion retail style.', 'festival-campaign', 'poster-typography', 'currency-card', 'seedream-4.5', '1792x1024', 'optional', FALSE, '可上传商品、品牌色或活动 KV 参考。', '/image-studio/templates/free-create.webp'),
        ('seed-160', '年会主视觉', '适合企业年会、颁奖典礼、周年庆和内部活动。', 'Create an annual gala key visual for {{subject}}, elegant stage, lights, abstract brand motif, large blank Chinese event title area {{text}}, premium corporate celebration mood.', 'festival-campaign', 'cinematic-film-still', 'music-stage', 'gpt-image-2', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-161', '表情包四宫格', '适合品牌角色、社群运营、客服互动和活动传播。', 'Create a four panel meme sticker grid for {{subject}}, same character in four emotions, thick sticker outline, clean background, no readable text, expressive and friendly.', 'meme-sticker', 'sticker-icon', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传角色参考图以保持一致。', '/image-studio/templates/free-create.webp'),
        ('seed-162', '社群贴纸套装', '适合会员群、粉丝群、客服话术和活动互动。', 'Create a community sticker set for {{subject}}, eight small stickers, simple gestures, consistent style, bright outline, transparent-feeling background, no text.', 'meme-sticker', 'sticker-icon', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传品牌角色参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-163', '评论区梗图', '适合社交运营、活动评论、幽默互动和账号人设。', 'Create a funny reaction image for {{subject}}, exaggerated but friendly expression, simple composition, blank Chinese caption area {{text}}, high shareability, no random text.', 'meme-sticker', 'comic-graphic-novel', 'portrait-selfie', 'grok-2-image', '1024x1024', 'optional', FALSE, '可上传人物或角色参考图。', '/image-studio/templates/free-create.webp'),
        ('seed-164', '可爱提醒贴图', '适合产品提示、客服提醒、学习打卡和社群公告。', 'Create a cute reminder sticker for {{subject}}, friendly mascot holding a small sign, clean blank Chinese message area {{text}}, soft colors {{color}}, readable sticker shape.', 'meme-sticker', 'chibi-q-style', 'character', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传角色或品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-165', '店铺会员贴纸', '适合会员等级、积分权益、社群身份和门店活动。', 'Create a membership badge sticker for {{subject}}, clean emblem shape, premium small icon, blank level text area {{text}}, brand color {{color}}, no random letters.', 'meme-sticker', 'sticker-icon', 'logo-symbol', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-166', 'T 恤图案设计', '适合活动服、品牌周边、社群文化衫和潮流印花。', 'Create a T shirt print design for {{subject}}, centered graphic, limited color palette {{color}}, screen print friendly, bold silhouette, no tiny text.', 'print-merchandise', 'flat-vector', 'text-typography', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-167', '帆布袋插画', '适合文创周边、环保袋、门店礼品和社群赠品。', 'Create a tote bag illustration for {{subject}}, simple charming line art, balanced central composition, two color print friendly, handmade warmth, no random letters.', 'print-merchandise', 'handmade-craft', 'abstract-background', 'gpt-image-1', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-168', '徽章贴纸设计', '适合活动徽章、品牌贴纸、手账素材和礼品包装。', 'Create a badge and sticker sheet for {{subject}}, ten small designs, consistent border, clear silhouettes, brand color {{color}}, ready for print, no tiny text.', 'print-merchandise', 'sticker-icon', 'logo-symbol', 'gpt-image-2', '1024x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-169', '明信片插画', '适合城市文旅、品牌礼品、节日祝福和收藏卡。', 'Create a postcard illustration for {{subject}}, charming landmark or object, balanced border, warm print texture, blank message space, refined travel souvenir style.', 'print-merchandise', 'retro-vintage', 'cityscape-street', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-170', '手机壳图案', '适合个性周边、IP 授权、品牌礼品和电商定制。', 'Create a phone case pattern for {{subject}}, vertical composition, safe central motif, repeated small elements, clear crop area, durable print feeling, no text.', 'print-merchandise', 'flat-vector', 'abstract-background', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-171', '楼盘鸟瞰视觉', '适合楼盘推广、园区展示、商业综合体和招商材料。', 'Create an aerial real estate visual for {{subject}}, modern buildings, landscaped paths, warm golden hour, clear property focal point, premium sales brochure style.', 'real-estate-visual', '3d-render', 'architecture-interior', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传建筑规划或效果图参考。', '/image-studio/templates/free-create.webp'),
        ('seed-172', '民宿房源首图', '适合民宿、酒店房源、租赁平台和本地生活推广。', 'Create a cozy guesthouse listing hero image for {{subject}}, inviting bedroom and window view, clean natural light, tidy decor, realistic travel booking style, no text.', 'real-estate-visual', 'photography', 'architecture-interior', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传房间照片作为参考。', '/image-studio/templates/free-create.webp'),
        ('seed-173', '产业园招商图', '适合园区招商、企业服务、城市更新和政企宣传。', 'Create an industrial park investment visual for {{subject}}, clean campus buildings, business people silhouettes, subtle data lines, professional city development mood, title area {{text}}.', 'real-estate-visual', 'clean-ui', 'architecture-interior', 'gpt-image-2', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-174', '酒店大堂视觉', '适合酒店官网、会务空间、宴会厅和高端服务介绍。', 'Create a luxury hotel lobby visual for {{subject}}, elegant interior, warm lighting, marble and wood materials, refined hospitality atmosphere, no people blocking the space.', 'real-estate-visual', 'luxury-editorial', 'architecture-interior', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传空间照片或风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-175', '城市更新概念图', '适合街区改造、公共空间、城市规划和文旅项目。', 'Create an urban renewal concept for {{subject}}, before-after inspired composition, walkable street, greenery, storefronts, warm civic atmosphere, no readable signs.', 'real-estate-visual', 'isometric', 'cityscape-street', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传街区或规划参考。', '/image-studio/templates/free-create.webp'),
        ('seed-176', '环保公益海报', '适合低碳、回收、公益活动和校园宣传。', 'Create a public service poster for {{subject}}, hopeful environmental imagery, clear symbolic focus, blank Chinese slogan area {{text}}, friendly green blue palette, no guilt-heavy imagery.', 'public-service', 'illustration', 'public-service-icon', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-177', '公共安全提示图', '适合消防、交通、校园安全和社区公告。', 'Create a public safety notice visual for {{subject}}, clear icon-like scene, high readability, calm authority, blank Chinese instruction area {{text}}, no frightening detail.', 'public-service', 'flat-vector', 'public-service-icon', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-178', '政务服务指南图', '适合办事指南、城市服务、社区服务和便民宣传。', 'Create a government service guide visual for {{subject}}, friendly service desk, simple process cards, blank Chinese label areas, trustworthy clean design, civic blue palette.', 'public-service', 'clean-ui', 'diagram-chart', 'seedream-4.5', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-179', '校园公益活动图', '适合志愿活动、社团招募、公益课堂和校园宣传。', 'Create a campus public welfare campaign image for {{subject}}, students working together, warm daylight, simple poster hierarchy, blank Chinese headline area {{text}}, positive energy.', 'public-service', 'illustration', 'group-couple', 'gpt-image-1', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-180', '健康公益科普图', '适合健康日、疫苗、义诊、护理科普和社区宣传。', 'Create a health awareness public service visual for {{subject}}, friendly medical icons, diverse people, clear blank Chinese information cards, calm trustworthy palette.', 'public-service', 'illustration', 'medical-health', 'seedream-4.5', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-181', '金融安全科普图', '适合反诈、风控、支付安全和用户教育。', 'Create a financial safety educational visual for {{subject}}, secure shield and card motifs, simple warning cards as blanks, trustworthy blue palette, modern clean infographic.', 'financial-business', 'flat-vector', 'currency-card', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-182', '信用卡广告图', '适合银行卡、会员卡、权益卡和支付产品推广。', 'Create a premium card advertising image for {{subject}}, card floating with subtle reflections, benefit icons as blank zones, luxurious lighting, brand color {{color}}, no fake numbers.', 'financial-business', 'product-render', 'currency-card', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传卡面或品牌色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-183', '企业服务宣传图', '适合 B2B SaaS、咨询服务、企业培训和解决方案展示。', 'Create a B2B service marketing visual for {{subject}}, business team, clean workflow cards, subtle data connections, professional trust mood, blank Chinese title area {{text}}.', 'financial-business', 'clean-ui', 'business-person', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传企业标志或界面参考。', '/image-studio/templates/free-create.webp'),
        ('seed-184', '数据隐私视觉', '适合安全产品、合规说明、隐私政策和企业可信宣传。', 'Create a data privacy visual for {{subject}}, secure vault and abstract data streams, calm professional lighting, clean empty headline area, no sensitive readable data.', 'financial-business', 'cyberpunk-sci-fi', 'diagram-chart', 'gpt-image-2', '1792x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-185', '投资报告封面', '适合基金报告、市场观察、企业财报和商业洞察。', 'Create an investment report cover for {{subject}}, refined chart motif, city skyline or abstract finance object, clean Chinese title area {{text}}, premium document design.', 'financial-business', 'document-clean', 'document-slide', 'gpt-image-2', '1024x1536', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-186', '汽车广告大片', '适合新车发布、汽车服务、经销商活动和品牌广告。', 'Create a car advertising hero image for {{subject}}, three-quarter vehicle view, dramatic road lighting, clean reflections, premium automotive campaign quality, no logo replacement.', 'automotive-visual', 'luxury-editorial', 'vehicle', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传车型或颜色参考。', '/image-studio/templates/free-create.webp'),
        ('seed-187', '摩托车潮流海报', '适合机车品牌、骑行活动、装备推广和社群活动。', 'Create a motorcycle lifestyle poster for {{subject}}, rider silhouette, urban night or mountain road, strong motion energy, blank Chinese event area {{text}}, no brand infringement.', 'automotive-visual', 'cinematic-film-still', 'vehicle', 'grok-2-image', '1024x1536', 'optional', FALSE, '可上传车辆或活动风格参考。', '/image-studio/templates/free-create.webp'),
        ('seed-188', '汽车维修服务图', '适合门店保养、售后服务、配件推广和预约页面。', 'Create an automotive service visual for {{subject}}, clean workshop, mechanic hands, car detail in focus, trustworthy lighting, blank Chinese service cards, professional local business style.', 'automotive-visual', 'photography', 'vehicle', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传门店或服务项目参考。', '/image-studio/templates/free-create.webp'),
        ('seed-189', '出行路线地图图', '适合自驾游、网约车、城市通勤和交通服务说明。', 'Create a transport route map visual for {{subject}}, simplified city roads, route line, vehicle icon, blank station cards, clear navigation style, no real map copyright look.', 'automotive-visual', 'flat-vector', 'map-location', 'gpt-image-2', '1536x1024', 'none', FALSE, '', '/image-studio/templates/free-create.webp'),
        ('seed-190', '新能源车科技图', '适合新能源车、电池技术、充电服务和智能座舱宣传。', 'Create a new energy vehicle technology visual for {{subject}}, car with subtle energy lines, charging station, clean future city background, premium tech palette {{color}}, no text.', 'automotive-visual', 'cyberpunk-sci-fi', 'vehicle', 'gpt-image-2', '1792x1024', 'optional', FALSE, '可上传车型或充电设备参考。', '/image-studio/templates/free-create.webp'),
        ('seed-191', '奢侈腕表大片', '适合腕表、珠宝、礼品和高端商城推广。', 'Create a luxury watch hero image for {{subject}}, macro dial detail, polished metal, elegant dark or cream background, premium reflections, no text.', 'luxury-fashion', 'macro-detail', 'jewelry-watch', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传腕表或材质参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-192', '高定时装大片', '适合服装品牌、秀场预告、穿搭内容和高端电商。', 'Create a couture fashion editorial for {{subject}}, full-body model, dramatic fabric movement, refined lighting, magazine composition, brand color hint {{color}}, no text.', 'luxury-fashion', 'fashion-editorial', 'apparel-model', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传服装或模特姿态参考。', '/demo-gpt-image.webp'),
        ('seed-193', '香水广告大片', '适合香水、美妆、礼品和节日营销。', 'Create a luxury perfume advertising image for {{subject}}, glass bottle, mist and floral notes, refined reflections, elegant background {{color}}, blank Chinese headline area {{text}}.', 'luxury-fashion', 'luxury-editorial', 'cosmetic-bottle', 'gpt-image-2', '1024x1536', 'optional', FALSE, '可上传瓶身参考图。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-194', '美甲作品展示', '适合美甲门店、作品集、预约页和社交种草。', 'Create a nail art showcase for {{subject}}, elegant hand pose, detailed manicure, soft beauty lighting, clean background, blank Chinese style name area {{text}}, no extra fingers.', 'beauty-salon', 'photography', 'beauty-cosmetics', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传美甲样式或手部参考。', '/demo-gpt-image.webp'),
        ('seed-195', '美发门店海报', '适合发型设计、理发店、美发活动和造型案例。', 'Create a hair salon campaign poster for {{subject}}, stylish hairstyle portrait, salon lighting, elegant blank Chinese offer area {{text}}, premium beauty service mood.', 'beauty-salon', 'photorealistic-portrait', 'portrait-selfie', 'seedream-4.5', '1024x1536', 'optional', FALSE, '可上传发型或人物参考。', '/demo-gpt-image.webp'),
        ('seed-196', '皮肤管理服务图', '适合美容院、护理服务、仪器项目和预约页。', 'Create a skincare service visual for {{subject}}, calm treatment room, clean tools, soft skin-care lighting, trustworthy blank Chinese service cards, gentle premium palette.', 'beauty-salon', 'luxury-editorial', 'beauty-cosmetics', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传门店或仪器参考。', '/image-studio/templates/free-create.webp'),
        ('seed-197', '农产品产地图', '适合生鲜、地方特产、农旅、溯源和电商详情页。', 'Create an agricultural origin visual for {{subject}}, fresh produce in foreground, farm landscape, morning light, honest natural mood, blank Chinese origin label area {{text}}.', 'agriculture-food', 'photography', 'farm-produce', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传产地或产品参考。', '/image-studio/templates/free-create.webp'),
        ('seed-198', '生鲜包装图', '适合水果、蔬菜、肉禽、水产和社区团购商品图。', 'Create a fresh food packaging image for {{subject}}, clean tray or box, visible freshness, cold chain retail feeling, simple label area, bright appetizing light, no fake text.', 'agriculture-food', 'photography', 'farm-produce', 'gpt-image-2', '1024x1024', 'optional', FALSE, '可上传包装或产品参考。', '/image-studio/templates/ecom-white-bg.webp'),
        ('seed-199', '工业设备宣传图', '适合机械设备、B2B 展会、工厂官网和招商资料。', 'Create an industrial equipment marketing image for {{subject}}, machine in clean factory environment, precise metal details, professional lighting, blank technical callout zones, no random labels.', 'industrial-manufacturing', 'product-render', 'machinery-part', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传设备外观或工厂照片。', '/image-studio/templates/free-create.webp'),
        ('seed-200', '机械零件爆炸图', '适合零部件、五金工具、工业说明和维修手册。', 'Create an exploded technical visual for {{subject}}, separated mechanical parts, clean guide lines, neutral background, blank annotation boxes, precise engineering style, no text.', 'industrial-manufacturing', 'blueprint-technical', 'machinery-part', 'gpt-image-2', '1536x1024', 'optional', FALSE, '可上传零件或设备结构参考。', '/image-studio/templates/free-create.webp')
),
inserted_items AS (
    INSERT INTO prompt_import_items (
        job_id, source_key, external_id, normalized_hash, status,
        normalized_payload, source_payload, evidence, authorization_status
    )
    SELECT
        job.id,
        'jisudeng-gpt-image-2-curated-seed-20260717',
        seed_items.external_id,
        md5('jisudeng-gpt-image-2-curated-seed-20260717:' || seed_items.external_id || ':' || seed_items.prompt_text),
        'pending_review',
        jsonb_build_object(
            'external_id', seed_items.external_id,
            'title_zh', seed_items.title_zh,
            'description_zh', seed_items.description_zh,
            'prompt_text', seed_items.prompt_text,
            'variables', jsonb_build_object(
                'subject', jsonb_build_object('label', '主体', 'description', '要生成的核心对象、人物或主题', 'required', TRUE),
                'text', jsonb_build_object('label', '中文文案', 'description', '画面中需要预留或生成的短文案', 'required', FALSE),
                'color', jsonb_build_object('label', '品牌颜色', 'description', '主色或色彩倾向，例如科技蓝、奶油白、黑金', 'required', FALSE),
                'scene', jsonb_build_object('label', '场景补充', 'description', '补充使用环境、氛围或构图要求', 'required', FALSE)
            ),
            'models', jsonb_build_array(seed_items.model),
            'sizes', jsonb_build_array(seed_items.size),
            'reference_requirement', seed_items.reference_requirement,
            'reference_instructions', seed_items.reference_instructions,
            'requires_reference', seed_items.requires_reference,
            'media', CASE
                WHEN seed_items.media_url <> '' THEN jsonb_build_array(jsonb_build_object(
                    'media_type', 'image',
                    'url', seed_items.media_url,
                    'alt_zh', seed_items.title_zh || '示例效果',
                    'sort_order', 0
                ))
                ELSE '[]'::jsonb
            END,
            'purpose', seed_items.purpose,
            'style', seed_items.style,
            'subject', seed_items.subject,
            'brand_type', 'curated',
            'authorization_status', 'curated',
            'evidence_verified', TRUE,
            'source_url', 'https://github.com/YouMind-OpenLab/awesome-gpt-image-2',
            'original_author', 'YouMind OpenLab community collection',
            'source_payload', jsonb_build_object(
                'category_basis', jsonb_build_array(seed_items.purpose, seed_items.style, seed_items.subject),
                'source_head', '51a031c7874169621688d77adb98b5efd20dd10d',
                'adapted_by', '极速蹬内容团队'
            ),
            'evidence', jsonb_build_object(
                'summary', '基于公开 GPT Image 2 提示词分类资源进行人工整理、中文化与模型适配，待管理员逐条复核后发布。',
                'captured_at', '2026-07-17T04:00:00Z',
                'source_commit', '51a031c7874169621688d77adb98b5efd20dd10d',
                'license_notice', '源仓库 README 展示 CC BY 4.0 许可徽章，仍需管理员确认具体条目的授权状态。',
                'review_requirement', '自动整理内容不得直接发布。'
            )
        ),
        jsonb_build_object(
            'source_url', 'https://github.com/YouMind-OpenLab/awesome-gpt-image-2',
            'source_head', '51a031c7874169621688d77adb98b5efd20dd10d',
            'source_categories', jsonb_build_array(seed_items.purpose, seed_items.style, seed_items.subject),
            'adaptation_scope', '分类、中文标题、中文说明、英文生成提示词与模型尺寸建议'
        ),
        jsonb_build_object(
            'summary', '基于公开 GPT Image 2 提示词分类资源进行人工整理、中文化与模型适配，待管理员逐条复核后发布。',
            'captured_at', '2026-07-17T04:00:00Z',
            'source_commit', '51a031c7874169621688d77adb98b5efd20dd10d',
            'license_notice', '源仓库 README 展示 CC BY 4.0 许可徽章，仍需管理员确认具体条目的授权状态。',
            'review_requirement', '自动整理内容不得直接发布。'
        ),
        'curated'
    FROM seed_items
    CROSS JOIN job
    ON CONFLICT DO NOTHING
    RETURNING 1
)
UPDATE prompt_import_jobs
SET item_count = (
        SELECT COUNT(*)
        FROM prompt_import_items
        WHERE job_id = prompt_import_jobs.id
    ),
    updated_at = NOW()
WHERE id = (SELECT id FROM job);
