// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mobileskill"
	"github.com/Wei-Shaw/sub2api/ent/mobileskillversion"
)

// MobileSkillVersion is the model entity for the MobileSkillVersion schema.
type MobileSkillVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID int64 `json:"skill_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// PromptID holds the value of the "prompt_id" field.
	PromptID int64 `json:"prompt_id,omitempty"`
	// PromptVersion holds the value of the "prompt_version" field.
	PromptVersion int `json:"prompt_version,omitempty"`
	// SystemPromptOverride holds the value of the "system_prompt_override" field.
	SystemPromptOverride *string `json:"system_prompt_override,omitempty"`
	// InputSchema holds the value of the "input_schema" field.
	InputSchema map[string]interface{} `json:"input_schema,omitempty"`
	// Examples holds the value of the "examples" field.
	Examples []map[string]interface{} `json:"examples,omitempty"`
	// ToolConfig holds the value of the "tool_config" field.
	ToolConfig map[string]interface{} `json:"tool_config,omitempty"`
	// ModelPolicy holds the value of the "model_policy" field.
	ModelPolicy map[string]interface{} `json:"model_policy,omitempty"`
	// ConsumptionNoteZh holds the value of the "consumption_note_zh" field.
	ConsumptionNoteZh string `json:"consumption_note_zh,omitempty"`
	// ChangelogZh holds the value of the "changelog_zh" field.
	ChangelogZh string `json:"changelog_zh,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MobileSkillVersionQuery when eager-loading is set.
	Edges        MobileSkillVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MobileSkillVersionEdges holds the relations/edges for other nodes in the graph.
type MobileSkillVersionEdges struct {
	// Skill holds the value of the skill edge.
	Skill *MobileSkill `json:"skill,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SkillOrErr returns the Skill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MobileSkillVersionEdges) SkillOrErr() (*MobileSkill, error) {
	if e.Skill != nil {
		return e.Skill, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: mobileskill.Label}
	}
	return nil, &NotLoadedError{edge: "skill"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MobileSkillVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mobileskillversion.FieldInputSchema, mobileskillversion.FieldExamples, mobileskillversion.FieldToolConfig, mobileskillversion.FieldModelPolicy:
			values[i] = new([]byte)
		case mobileskillversion.FieldID, mobileskillversion.FieldSkillID, mobileskillversion.FieldVersion, mobileskillversion.FieldPromptID, mobileskillversion.FieldPromptVersion:
			values[i] = new(sql.NullInt64)
		case mobileskillversion.FieldSystemPromptOverride, mobileskillversion.FieldConsumptionNoteZh, mobileskillversion.FieldChangelogZh:
			values[i] = new(sql.NullString)
		case mobileskillversion.FieldCreatedAt, mobileskillversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MobileSkillVersion fields.
func (_m *MobileSkillVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mobileskillversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case mobileskillversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mobileskillversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mobileskillversion.FieldSkillID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value.Valid {
				_m.SkillID = value.Int64
			}
		case mobileskillversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case mobileskillversion.FieldPromptID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_id", values[i])
			} else if value.Valid {
				_m.PromptID = value.Int64
			}
		case mobileskillversion.FieldPromptVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_version", values[i])
			} else if value.Valid {
				_m.PromptVersion = int(value.Int64)
			}
		case mobileskillversion.FieldSystemPromptOverride:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_prompt_override", values[i])
			} else if value.Valid {
				_m.SystemPromptOverride = new(string)
				*_m.SystemPromptOverride = value.String
			}
		case mobileskillversion.FieldInputSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.InputSchema); err != nil {
					return fmt.Errorf("unmarshal field input_schema: %w", err)
				}
			}
		case mobileskillversion.FieldExamples:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field examples", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Examples); err != nil {
					return fmt.Errorf("unmarshal field examples: %w", err)
				}
			}
		case mobileskillversion.FieldToolConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tool_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ToolConfig); err != nil {
					return fmt.Errorf("unmarshal field tool_config: %w", err)
				}
			}
		case mobileskillversion.FieldModelPolicy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_policy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelPolicy); err != nil {
					return fmt.Errorf("unmarshal field model_policy: %w", err)
				}
			}
		case mobileskillversion.FieldConsumptionNoteZh:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field consumption_note_zh", values[i])
			} else if value.Valid {
				_m.ConsumptionNoteZh = value.String
			}
		case mobileskillversion.FieldChangelogZh:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field changelog_zh", values[i])
			} else if value.Valid {
				_m.ChangelogZh = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MobileSkillVersion.
// This includes values selected through modifiers, order, etc.
func (_m *MobileSkillVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySkill queries the "skill" edge of the MobileSkillVersion entity.
func (_m *MobileSkillVersion) QuerySkill() *MobileSkillQuery {
	return NewMobileSkillVersionClient(_m.config).QuerySkill(_m)
}

// Update returns a builder for updating this MobileSkillVersion.
// Note that you need to call MobileSkillVersion.Unwrap() before calling this method if this MobileSkillVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MobileSkillVersion) Update() *MobileSkillVersionUpdateOne {
	return NewMobileSkillVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MobileSkillVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MobileSkillVersion) Unwrap() *MobileSkillVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MobileSkillVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MobileSkillVersion) String() string {
	var builder strings.Builder
	builder.WriteString("MobileSkillVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("prompt_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptID))
	builder.WriteString(", ")
	builder.WriteString("prompt_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptVersion))
	builder.WriteString(", ")
	if v := _m.SystemPromptOverride; v != nil {
		builder.WriteString("system_prompt_override=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("input_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputSchema))
	builder.WriteString(", ")
	builder.WriteString("examples=")
	builder.WriteString(fmt.Sprintf("%v", _m.Examples))
	builder.WriteString(", ")
	builder.WriteString("tool_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolConfig))
	builder.WriteString(", ")
	builder.WriteString("model_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelPolicy))
	builder.WriteString(", ")
	builder.WriteString("consumption_note_zh=")
	builder.WriteString(_m.ConsumptionNoteZh)
	builder.WriteString(", ")
	builder.WriteString("changelog_zh=")
	builder.WriteString(_m.ChangelogZh)
	builder.WriteByte(')')
	return builder.String()
}

// MobileSkillVersions is a parsable slice of MobileSkillVersion.
type MobileSkillVersions []*MobileSkillVersion
