// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mobiledevice"
	"github.com/google/uuid"
)

// MobileDevice is the model entity for the MobileDevice schema.
type MobileDevice struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// InstallationID holds the value of the "installation_id" field.
	InstallationID uuid.UUID `json:"installation_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// PushProvider holds the value of the "push_provider" field.
	PushProvider string `json:"push_provider,omitempty"`
	// TokenCiphertext holds the value of the "token_ciphertext" field.
	TokenCiphertext string `json:"-"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"-"`
	// AppVersion holds the value of the "app_version" field.
	AppVersion string `json:"app_version,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt    *time.Time `json:"revoked_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MobileDevice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mobiledevice.FieldEnabled:
			values[i] = new(sql.NullBool)
		case mobiledevice.FieldUserID:
			values[i] = new(sql.NullInt64)
		case mobiledevice.FieldPlatform, mobiledevice.FieldPushProvider, mobiledevice.FieldTokenCiphertext, mobiledevice.FieldTokenHash, mobiledevice.FieldAppVersion, mobiledevice.FieldLocale:
			values[i] = new(sql.NullString)
		case mobiledevice.FieldCreatedAt, mobiledevice.FieldUpdatedAt, mobiledevice.FieldLastSeenAt, mobiledevice.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case mobiledevice.FieldID, mobiledevice.FieldInstallationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MobileDevice fields.
func (_m *MobileDevice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mobiledevice.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mobiledevice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mobiledevice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mobiledevice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case mobiledevice.FieldInstallationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id", values[i])
			} else if value != nil {
				_m.InstallationID = *value
			}
		case mobiledevice.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case mobiledevice.FieldPushProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field push_provider", values[i])
			} else if value.Valid {
				_m.PushProvider = value.String
			}
		case mobiledevice.FieldTokenCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_ciphertext", values[i])
			} else if value.Valid {
				_m.TokenCiphertext = value.String
			}
		case mobiledevice.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case mobiledevice.FieldAppVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_version", values[i])
			} else if value.Valid {
				_m.AppVersion = value.String
			}
		case mobiledevice.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case mobiledevice.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case mobiledevice.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case mobiledevice.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MobileDevice.
// This includes values selected through modifiers, order, etc.
func (_m *MobileDevice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MobileDevice.
// Note that you need to call MobileDevice.Unwrap() before calling this method if this MobileDevice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MobileDevice) Update() *MobileDeviceUpdateOne {
	return NewMobileDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MobileDevice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MobileDevice) Unwrap() *MobileDevice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MobileDevice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MobileDevice) String() string {
	var builder strings.Builder
	builder.WriteString("MobileDevice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("installation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstallationID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("push_provider=")
	builder.WriteString(_m.PushProvider)
	builder.WriteString(", ")
	builder.WriteString("token_ciphertext=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("app_version=")
	builder.WriteString(_m.AppVersion)
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MobileDevices is a parsable slice of MobileDevice.
type MobileDevices []*MobileDevice
