// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mobilepushoutbox"
	"github.com/google/uuid"
)

// MobilePushOutboxCreate is the builder for creating a MobilePushOutbox entity.
type MobilePushOutboxCreate struct {
	config
	mutation *MobilePushOutboxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MobilePushOutboxCreate) SetCreatedAt(v time.Time) *MobilePushOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableCreatedAt(v *time.Time) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MobilePushOutboxCreate) SetUpdatedAt(v time.Time) *MobilePushOutboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableUpdatedAt(v *time.Time) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MobilePushOutboxCreate) SetUserID(v int64) *MobilePushOutboxCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDedupeKeyHash sets the "dedupe_key_hash" field.
func (_c *MobilePushOutboxCreate) SetDedupeKeyHash(v string) *MobilePushOutboxCreate {
	_c.mutation.SetDedupeKeyHash(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *MobilePushOutboxCreate) SetEventType(v string) *MobilePushOutboxCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *MobilePushOutboxCreate) SetSourceType(v string) *MobilePushOutboxCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableSourceType(v *string) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetSourceType(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *MobilePushOutboxCreate) SetSourceID(v string) *MobilePushOutboxCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableSourceID(v *string) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetTitleZh sets the "title_zh" field.
func (_c *MobilePushOutboxCreate) SetTitleZh(v string) *MobilePushOutboxCreate {
	_c.mutation.SetTitleZh(v)
	return _c
}

// SetBodyZh sets the "body_zh" field.
func (_c *MobilePushOutboxCreate) SetBodyZh(v string) *MobilePushOutboxCreate {
	_c.mutation.SetBodyZh(v)
	return _c
}

// SetData sets the "data" field.
func (_c *MobilePushOutboxCreate) SetData(v map[string]string) *MobilePushOutboxCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MobilePushOutboxCreate) SetStatus(v string) *MobilePushOutboxCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableStatus(v *string) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *MobilePushOutboxCreate) SetAttempts(v int) *MobilePushOutboxCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableAttempts(v *int) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *MobilePushOutboxCreate) SetLastErrorCode(v string) *MobilePushOutboxCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableLastErrorCode(v *string) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *MobilePushOutboxCreate) SetAvailableAt(v time.Time) *MobilePushOutboxCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *MobilePushOutboxCreate) SetSentAt(v time.Time) *MobilePushOutboxCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableSentAt(v *time.Time) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetClaimToken sets the "claim_token" field.
func (_c *MobilePushOutboxCreate) SetClaimToken(v uuid.UUID) *MobilePushOutboxCreate {
	_c.mutation.SetClaimToken(v)
	return _c
}

// SetNillableClaimToken sets the "claim_token" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableClaimToken(v *uuid.UUID) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetClaimToken(*v)
	}
	return _c
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_c *MobilePushOutboxCreate) SetLeaseExpiresAt(v time.Time) *MobilePushOutboxCreate {
	_c.mutation.SetLeaseExpiresAt(v)
	return _c
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_c *MobilePushOutboxCreate) SetNillableLeaseExpiresAt(v *time.Time) *MobilePushOutboxCreate {
	if v != nil {
		_c.SetLeaseExpiresAt(*v)
	}
	return _c
}

// Mutation returns the MobilePushOutboxMutation object of the builder.
func (_c *MobilePushOutboxCreate) Mutation() *MobilePushOutboxMutation {
	return _c.mutation
}

// Save creates the MobilePushOutbox in the database.
func (_c *MobilePushOutboxCreate) Save(ctx context.Context) (*MobilePushOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MobilePushOutboxCreate) SaveX(ctx context.Context) *MobilePushOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MobilePushOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MobilePushOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MobilePushOutboxCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mobilepushoutbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mobilepushoutbox.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		v := mobilepushoutbox.DefaultSourceType
		_c.mutation.SetSourceType(v)
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		v := mobilepushoutbox.DefaultSourceID
		_c.mutation.SetSourceID(v)
	}
	if _, ok := _c.mutation.Data(); !ok {
		v := mobilepushoutbox.DefaultData()
		_c.mutation.SetData(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mobilepushoutbox.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := mobilepushoutbox.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MobilePushOutboxCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MobilePushOutbox.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MobilePushOutbox.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MobilePushOutbox.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := mobilepushoutbox.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DedupeKeyHash(); !ok {
		return &ValidationError{Name: "dedupe_key_hash", err: errors.New(`ent: missing required field "MobilePushOutbox.dedupe_key_hash"`)}
	}
	if v, ok := _c.mutation.DedupeKeyHash(); ok {
		if err := mobilepushoutbox.DedupeKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "dedupe_key_hash", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.dedupe_key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "MobilePushOutbox.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := mobilepushoutbox.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "MobilePushOutbox.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := mobilepushoutbox.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "MobilePushOutbox.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := mobilepushoutbox.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TitleZh(); !ok {
		return &ValidationError{Name: "title_zh", err: errors.New(`ent: missing required field "MobilePushOutbox.title_zh"`)}
	}
	if v, ok := _c.mutation.TitleZh(); ok {
		if err := mobilepushoutbox.TitleZhValidator(v); err != nil {
			return &ValidationError{Name: "title_zh", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.title_zh": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BodyZh(); !ok {
		return &ValidationError{Name: "body_zh", err: errors.New(`ent: missing required field "MobilePushOutbox.body_zh"`)}
	}
	if v, ok := _c.mutation.BodyZh(); ok {
		if err := mobilepushoutbox.BodyZhValidator(v); err != nil {
			return &ValidationError{Name: "body_zh", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.body_zh": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "MobilePushOutbox.data"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MobilePushOutbox.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mobilepushoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "MobilePushOutbox.attempts"`)}
	}
	if v, ok := _c.mutation.Attempts(); ok {
		if err := mobilepushoutbox.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.attempts": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastErrorCode(); ok {
		if err := mobilepushoutbox.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "MobilePushOutbox.last_error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "MobilePushOutbox.available_at"`)}
	}
	return nil
}

func (_c *MobilePushOutboxCreate) sqlSave(ctx context.Context) (*MobilePushOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MobilePushOutboxCreate) createSpec() (*MobilePushOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &MobilePushOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mobilepushoutbox.Table, sqlgraph.NewFieldSpec(mobilepushoutbox.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mobilepushoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mobilepushoutbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(mobilepushoutbox.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DedupeKeyHash(); ok {
		_spec.SetField(mobilepushoutbox.FieldDedupeKeyHash, field.TypeString, value)
		_node.DedupeKeyHash = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(mobilepushoutbox.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(mobilepushoutbox.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(mobilepushoutbox.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.TitleZh(); ok {
		_spec.SetField(mobilepushoutbox.FieldTitleZh, field.TypeString, value)
		_node.TitleZh = value
	}
	if value, ok := _c.mutation.BodyZh(); ok {
		_spec.SetField(mobilepushoutbox.FieldBodyZh, field.TypeString, value)
		_node.BodyZh = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(mobilepushoutbox.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mobilepushoutbox.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(mobilepushoutbox.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(mobilepushoutbox.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = &value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(mobilepushoutbox.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(mobilepushoutbox.FieldSentAt, field.TypeTime, value)
		_node.SentAt = &value
	}
	if value, ok := _c.mutation.ClaimToken(); ok {
		_spec.SetField(mobilepushoutbox.FieldClaimToken, field.TypeUUID, value)
		_node.ClaimToken = &value
	}
	if value, ok := _c.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(mobilepushoutbox.FieldLeaseExpiresAt, field.TypeTime, value)
		_node.LeaseExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MobilePushOutbox.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MobilePushOutboxUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MobilePushOutboxCreate) OnConflict(opts ...sql.ConflictOption) *MobilePushOutboxUpsertOne {
	_c.conflict = opts
	return &MobilePushOutboxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MobilePushOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MobilePushOutboxCreate) OnConflictColumns(columns ...string) *MobilePushOutboxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MobilePushOutboxUpsertOne{
		create: _c,
	}
}

type (
	// MobilePushOutboxUpsertOne is the builder for "upsert"-ing
	//  one MobilePushOutbox node.
	MobilePushOutboxUpsertOne struct {
		create *MobilePushOutboxCreate
	}

	// MobilePushOutboxUpsert is the "OnConflict" setter.
	MobilePushOutboxUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MobilePushOutboxUpsert) SetUpdatedAt(v time.Time) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateUpdatedAt() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldUpdatedAt)
	return u
}

// SetTitleZh sets the "title_zh" field.
func (u *MobilePushOutboxUpsert) SetTitleZh(v string) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldTitleZh, v)
	return u
}

// UpdateTitleZh sets the "title_zh" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateTitleZh() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldTitleZh)
	return u
}

// SetBodyZh sets the "body_zh" field.
func (u *MobilePushOutboxUpsert) SetBodyZh(v string) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldBodyZh, v)
	return u
}

// UpdateBodyZh sets the "body_zh" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateBodyZh() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldBodyZh)
	return u
}

// SetData sets the "data" field.
func (u *MobilePushOutboxUpsert) SetData(v map[string]string) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateData() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldData)
	return u
}

// SetStatus sets the "status" field.
func (u *MobilePushOutboxUpsert) SetStatus(v string) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateStatus() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldStatus)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *MobilePushOutboxUpsert) SetAttempts(v int) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateAttempts() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *MobilePushOutboxUpsert) AddAttempts(v int) *MobilePushOutboxUpsert {
	u.Add(mobilepushoutbox.FieldAttempts, v)
	return u
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *MobilePushOutboxUpsert) SetLastErrorCode(v string) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldLastErrorCode, v)
	return u
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateLastErrorCode() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldLastErrorCode)
	return u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *MobilePushOutboxUpsert) ClearLastErrorCode() *MobilePushOutboxUpsert {
	u.SetNull(mobilepushoutbox.FieldLastErrorCode)
	return u
}

// SetAvailableAt sets the "available_at" field.
func (u *MobilePushOutboxUpsert) SetAvailableAt(v time.Time) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldAvailableAt, v)
	return u
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateAvailableAt() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldAvailableAt)
	return u
}

// SetSentAt sets the "sent_at" field.
func (u *MobilePushOutboxUpsert) SetSentAt(v time.Time) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldSentAt, v)
	return u
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateSentAt() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldSentAt)
	return u
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *MobilePushOutboxUpsert) ClearSentAt() *MobilePushOutboxUpsert {
	u.SetNull(mobilepushoutbox.FieldSentAt)
	return u
}

// SetClaimToken sets the "claim_token" field.
func (u *MobilePushOutboxUpsert) SetClaimToken(v uuid.UUID) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldClaimToken, v)
	return u
}

// UpdateClaimToken sets the "claim_token" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateClaimToken() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldClaimToken)
	return u
}

// ClearClaimToken clears the value of the "claim_token" field.
func (u *MobilePushOutboxUpsert) ClearClaimToken() *MobilePushOutboxUpsert {
	u.SetNull(mobilepushoutbox.FieldClaimToken)
	return u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *MobilePushOutboxUpsert) SetLeaseExpiresAt(v time.Time) *MobilePushOutboxUpsert {
	u.Set(mobilepushoutbox.FieldLeaseExpiresAt, v)
	return u
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsert) UpdateLeaseExpiresAt() *MobilePushOutboxUpsert {
	u.SetExcluded(mobilepushoutbox.FieldLeaseExpiresAt)
	return u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *MobilePushOutboxUpsert) ClearLeaseExpiresAt() *MobilePushOutboxUpsert {
	u.SetNull(mobilepushoutbox.FieldLeaseExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MobilePushOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MobilePushOutboxUpsertOne) UpdateNewValues() *MobilePushOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mobilepushoutbox.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(mobilepushoutbox.FieldUserID)
		}
		if _, exists := u.create.mutation.DedupeKeyHash(); exists {
			s.SetIgnore(mobilepushoutbox.FieldDedupeKeyHash)
		}
		if _, exists := u.create.mutation.EventType(); exists {
			s.SetIgnore(mobilepushoutbox.FieldEventType)
		}
		if _, exists := u.create.mutation.SourceType(); exists {
			s.SetIgnore(mobilepushoutbox.FieldSourceType)
		}
		if _, exists := u.create.mutation.SourceID(); exists {
			s.SetIgnore(mobilepushoutbox.FieldSourceID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MobilePushOutbox.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MobilePushOutboxUpsertOne) Ignore() *MobilePushOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MobilePushOutboxUpsertOne) DoNothing() *MobilePushOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MobilePushOutboxCreate.OnConflict
// documentation for more info.
func (u *MobilePushOutboxUpsertOne) Update(set func(*MobilePushOutboxUpsert)) *MobilePushOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MobilePushOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MobilePushOutboxUpsertOne) SetUpdatedAt(v time.Time) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateUpdatedAt() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTitleZh sets the "title_zh" field.
func (u *MobilePushOutboxUpsertOne) SetTitleZh(v string) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetTitleZh(v)
	})
}

// UpdateTitleZh sets the "title_zh" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateTitleZh() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateTitleZh()
	})
}

// SetBodyZh sets the "body_zh" field.
func (u *MobilePushOutboxUpsertOne) SetBodyZh(v string) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetBodyZh(v)
	})
}

// UpdateBodyZh sets the "body_zh" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateBodyZh() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateBodyZh()
	})
}

// SetData sets the "data" field.
func (u *MobilePushOutboxUpsertOne) SetData(v map[string]string) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateData() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateData()
	})
}

// SetStatus sets the "status" field.
func (u *MobilePushOutboxUpsertOne) SetStatus(v string) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateStatus() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *MobilePushOutboxUpsertOne) SetAttempts(v int) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *MobilePushOutboxUpsertOne) AddAttempts(v int) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateAttempts() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *MobilePushOutboxUpsertOne) SetLastErrorCode(v string) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateLastErrorCode() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *MobilePushOutboxUpsertOne) ClearLastErrorCode() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *MobilePushOutboxUpsertOne) SetAvailableAt(v time.Time) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateAvailableAt() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *MobilePushOutboxUpsertOne) SetSentAt(v time.Time) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateSentAt() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *MobilePushOutboxUpsertOne) ClearSentAt() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearSentAt()
	})
}

// SetClaimToken sets the "claim_token" field.
func (u *MobilePushOutboxUpsertOne) SetClaimToken(v uuid.UUID) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetClaimToken(v)
	})
}

// UpdateClaimToken sets the "claim_token" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateClaimToken() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateClaimToken()
	})
}

// ClearClaimToken clears the value of the "claim_token" field.
func (u *MobilePushOutboxUpsertOne) ClearClaimToken() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearClaimToken()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *MobilePushOutboxUpsertOne) SetLeaseExpiresAt(v time.Time) *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertOne) UpdateLeaseExpiresAt() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *MobilePushOutboxUpsertOne) ClearLeaseExpiresAt() *MobilePushOutboxUpsertOne {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearLeaseExpiresAt()
	})
}

// Exec executes the query.
func (u *MobilePushOutboxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MobilePushOutboxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MobilePushOutboxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MobilePushOutboxUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MobilePushOutboxUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MobilePushOutboxCreateBulk is the builder for creating many MobilePushOutbox entities in bulk.
type MobilePushOutboxCreateBulk struct {
	config
	err      error
	builders []*MobilePushOutboxCreate
	conflict []sql.ConflictOption
}

// Save creates the MobilePushOutbox entities in the database.
func (_c *MobilePushOutboxCreateBulk) Save(ctx context.Context) ([]*MobilePushOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MobilePushOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MobilePushOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MobilePushOutboxCreateBulk) SaveX(ctx context.Context) []*MobilePushOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MobilePushOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MobilePushOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MobilePushOutbox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MobilePushOutboxUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MobilePushOutboxCreateBulk) OnConflict(opts ...sql.ConflictOption) *MobilePushOutboxUpsertBulk {
	_c.conflict = opts
	return &MobilePushOutboxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MobilePushOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MobilePushOutboxCreateBulk) OnConflictColumns(columns ...string) *MobilePushOutboxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MobilePushOutboxUpsertBulk{
		create: _c,
	}
}

// MobilePushOutboxUpsertBulk is the builder for "upsert"-ing
// a bulk of MobilePushOutbox nodes.
type MobilePushOutboxUpsertBulk struct {
	create *MobilePushOutboxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MobilePushOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MobilePushOutboxUpsertBulk) UpdateNewValues() *MobilePushOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mobilepushoutbox.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(mobilepushoutbox.FieldUserID)
			}
			if _, exists := b.mutation.DedupeKeyHash(); exists {
				s.SetIgnore(mobilepushoutbox.FieldDedupeKeyHash)
			}
			if _, exists := b.mutation.EventType(); exists {
				s.SetIgnore(mobilepushoutbox.FieldEventType)
			}
			if _, exists := b.mutation.SourceType(); exists {
				s.SetIgnore(mobilepushoutbox.FieldSourceType)
			}
			if _, exists := b.mutation.SourceID(); exists {
				s.SetIgnore(mobilepushoutbox.FieldSourceID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MobilePushOutbox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MobilePushOutboxUpsertBulk) Ignore() *MobilePushOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MobilePushOutboxUpsertBulk) DoNothing() *MobilePushOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MobilePushOutboxCreateBulk.OnConflict
// documentation for more info.
func (u *MobilePushOutboxUpsertBulk) Update(set func(*MobilePushOutboxUpsert)) *MobilePushOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MobilePushOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MobilePushOutboxUpsertBulk) SetUpdatedAt(v time.Time) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateUpdatedAt() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTitleZh sets the "title_zh" field.
func (u *MobilePushOutboxUpsertBulk) SetTitleZh(v string) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetTitleZh(v)
	})
}

// UpdateTitleZh sets the "title_zh" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateTitleZh() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateTitleZh()
	})
}

// SetBodyZh sets the "body_zh" field.
func (u *MobilePushOutboxUpsertBulk) SetBodyZh(v string) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetBodyZh(v)
	})
}

// UpdateBodyZh sets the "body_zh" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateBodyZh() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateBodyZh()
	})
}

// SetData sets the "data" field.
func (u *MobilePushOutboxUpsertBulk) SetData(v map[string]string) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateData() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateData()
	})
}

// SetStatus sets the "status" field.
func (u *MobilePushOutboxUpsertBulk) SetStatus(v string) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateStatus() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *MobilePushOutboxUpsertBulk) SetAttempts(v int) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *MobilePushOutboxUpsertBulk) AddAttempts(v int) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateAttempts() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *MobilePushOutboxUpsertBulk) SetLastErrorCode(v string) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateLastErrorCode() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateLastErrorCode()
	})
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (u *MobilePushOutboxUpsertBulk) ClearLastErrorCode() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearLastErrorCode()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *MobilePushOutboxUpsertBulk) SetAvailableAt(v time.Time) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateAvailableAt() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *MobilePushOutboxUpsertBulk) SetSentAt(v time.Time) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateSentAt() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *MobilePushOutboxUpsertBulk) ClearSentAt() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearSentAt()
	})
}

// SetClaimToken sets the "claim_token" field.
func (u *MobilePushOutboxUpsertBulk) SetClaimToken(v uuid.UUID) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetClaimToken(v)
	})
}

// UpdateClaimToken sets the "claim_token" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateClaimToken() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateClaimToken()
	})
}

// ClearClaimToken clears the value of the "claim_token" field.
func (u *MobilePushOutboxUpsertBulk) ClearClaimToken() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearClaimToken()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *MobilePushOutboxUpsertBulk) SetLeaseExpiresAt(v time.Time) *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *MobilePushOutboxUpsertBulk) UpdateLeaseExpiresAt() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *MobilePushOutboxUpsertBulk) ClearLeaseExpiresAt() *MobilePushOutboxUpsertBulk {
	return u.Update(func(s *MobilePushOutboxUpsert) {
		s.ClearLeaseExpiresAt()
	})
}

// Exec executes the query.
func (u *MobilePushOutboxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MobilePushOutboxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MobilePushOutboxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MobilePushOutboxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
