// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mobileskill"
	"github.com/Wei-Shaw/sub2api/ent/mobileskillversion"
	"github.com/Wei-Shaw/sub2api/ent/usermobileskill"
)

// MobileSkillCreate is the builder for creating a MobileSkill entity.
type MobileSkillCreate struct {
	config
	mutation *MobileSkillMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MobileSkillCreate) SetCreatedAt(v time.Time) *MobileSkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableCreatedAt(v *time.Time) *MobileSkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MobileSkillCreate) SetUpdatedAt(v time.Time) *MobileSkillCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableUpdatedAt(v *time.Time) *MobileSkillCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *MobileSkillCreate) SetSlug(v string) *MobileSkillCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MobileSkillCreate) SetStatus(v mobileskill.Status) *MobileSkillCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableStatus(v *mobileskill.Status) *MobileSkillCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNameZh sets the "name_zh" field.
func (_c *MobileSkillCreate) SetNameZh(v string) *MobileSkillCreate {
	_c.mutation.SetNameZh(v)
	return _c
}

// SetDescriptionZh sets the "description_zh" field.
func (_c *MobileSkillCreate) SetDescriptionZh(v string) *MobileSkillCreate {
	_c.mutation.SetDescriptionZh(v)
	return _c
}

// SetNillableDescriptionZh sets the "description_zh" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableDescriptionZh(v *string) *MobileSkillCreate {
	if v != nil {
		_c.SetDescriptionZh(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *MobileSkillCreate) SetCategory(v string) *MobileSkillCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableCategory(v *string) *MobileSkillCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetIconURL sets the "icon_url" field.
func (_c *MobileSkillCreate) SetIconURL(v string) *MobileSkillCreate {
	_c.mutation.SetIconURL(v)
	return _c
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableIconURL(v *string) *MobileSkillCreate {
	if v != nil {
		_c.SetIconURL(*v)
	}
	return _c
}

// SetCoverURL sets the "cover_url" field.
func (_c *MobileSkillCreate) SetCoverURL(v string) *MobileSkillCreate {
	_c.mutation.SetCoverURL(v)
	return _c
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableCoverURL(v *string) *MobileSkillCreate {
	if v != nil {
		_c.SetCoverURL(*v)
	}
	return _c
}

// SetCurrentVersion sets the "current_version" field.
func (_c *MobileSkillCreate) SetCurrentVersion(v int) *MobileSkillCreate {
	_c.mutation.SetCurrentVersion(v)
	return _c
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableCurrentVersion(v *int) *MobileSkillCreate {
	if v != nil {
		_c.SetCurrentVersion(*v)
	}
	return _c
}

// SetPublishedVersion sets the "published_version" field.
func (_c *MobileSkillCreate) SetPublishedVersion(v int) *MobileSkillCreate {
	_c.mutation.SetPublishedVersion(v)
	return _c
}

// SetNillablePublishedVersion sets the "published_version" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillablePublishedVersion(v *int) *MobileSkillCreate {
	if v != nil {
		_c.SetPublishedVersion(*v)
	}
	return _c
}

// SetFeatured sets the "featured" field.
func (_c *MobileSkillCreate) SetFeatured(v bool) *MobileSkillCreate {
	_c.mutation.SetFeatured(v)
	return _c
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableFeatured(v *bool) *MobileSkillCreate {
	if v != nil {
		_c.SetFeatured(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *MobileSkillCreate) SetSortOrder(v int) *MobileSkillCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *MobileSkillCreate) SetNillableSortOrder(v *int) *MobileSkillCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddVersionIDs adds the "versions" edge to the MobileSkillVersion entity by IDs.
func (_c *MobileSkillCreate) AddVersionIDs(ids ...int64) *MobileSkillCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the MobileSkillVersion entity.
func (_c *MobileSkillCreate) AddVersions(v ...*MobileSkillVersion) *MobileSkillCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// AddUserInstallIDs adds the "user_installs" edge to the UserMobileSkill entity by IDs.
func (_c *MobileSkillCreate) AddUserInstallIDs(ids ...int64) *MobileSkillCreate {
	_c.mutation.AddUserInstallIDs(ids...)
	return _c
}

// AddUserInstalls adds the "user_installs" edges to the UserMobileSkill entity.
func (_c *MobileSkillCreate) AddUserInstalls(v ...*UserMobileSkill) *MobileSkillCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserInstallIDs(ids...)
}

// Mutation returns the MobileSkillMutation object of the builder.
func (_c *MobileSkillCreate) Mutation() *MobileSkillMutation {
	return _c.mutation
}

// Save creates the MobileSkill in the database.
func (_c *MobileSkillCreate) Save(ctx context.Context) (*MobileSkill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MobileSkillCreate) SaveX(ctx context.Context) *MobileSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MobileSkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MobileSkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MobileSkillCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mobileskill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mobileskill.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mobileskill.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DescriptionZh(); !ok {
		v := mobileskill.DefaultDescriptionZh
		_c.mutation.SetDescriptionZh(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := mobileskill.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.IconURL(); !ok {
		v := mobileskill.DefaultIconURL
		_c.mutation.SetIconURL(v)
	}
	if _, ok := _c.mutation.CoverURL(); !ok {
		v := mobileskill.DefaultCoverURL
		_c.mutation.SetCoverURL(v)
	}
	if _, ok := _c.mutation.CurrentVersion(); !ok {
		v := mobileskill.DefaultCurrentVersion
		_c.mutation.SetCurrentVersion(v)
	}
	if _, ok := _c.mutation.Featured(); !ok {
		v := mobileskill.DefaultFeatured
		_c.mutation.SetFeatured(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := mobileskill.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MobileSkillCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MobileSkill.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MobileSkill.updated_at"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "MobileSkill.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := mobileskill.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "MobileSkill.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MobileSkill.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mobileskill.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MobileSkill.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameZh(); !ok {
		return &ValidationError{Name: "name_zh", err: errors.New(`ent: missing required field "MobileSkill.name_zh"`)}
	}
	if v, ok := _c.mutation.NameZh(); ok {
		if err := mobileskill.NameZhValidator(v); err != nil {
			return &ValidationError{Name: "name_zh", err: fmt.Errorf(`ent: validator failed for field "MobileSkill.name_zh": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DescriptionZh(); !ok {
		return &ValidationError{Name: "description_zh", err: errors.New(`ent: missing required field "MobileSkill.description_zh"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "MobileSkill.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := mobileskill.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "MobileSkill.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IconURL(); !ok {
		return &ValidationError{Name: "icon_url", err: errors.New(`ent: missing required field "MobileSkill.icon_url"`)}
	}
	if _, ok := _c.mutation.CoverURL(); !ok {
		return &ValidationError{Name: "cover_url", err: errors.New(`ent: missing required field "MobileSkill.cover_url"`)}
	}
	if _, ok := _c.mutation.CurrentVersion(); !ok {
		return &ValidationError{Name: "current_version", err: errors.New(`ent: missing required field "MobileSkill.current_version"`)}
	}
	if v, ok := _c.mutation.CurrentVersion(); ok {
		if err := mobileskill.CurrentVersionValidator(v); err != nil {
			return &ValidationError{Name: "current_version", err: fmt.Errorf(`ent: validator failed for field "MobileSkill.current_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PublishedVersion(); ok {
		if err := mobileskill.PublishedVersionValidator(v); err != nil {
			return &ValidationError{Name: "published_version", err: fmt.Errorf(`ent: validator failed for field "MobileSkill.published_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "MobileSkill.featured"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "MobileSkill.sort_order"`)}
	}
	return nil
}

func (_c *MobileSkillCreate) sqlSave(ctx context.Context) (*MobileSkill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MobileSkillCreate) createSpec() (*MobileSkill, *sqlgraph.CreateSpec) {
	var (
		_node = &MobileSkill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mobileskill.Table, sqlgraph.NewFieldSpec(mobileskill.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mobileskill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mobileskill.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(mobileskill.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mobileskill.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NameZh(); ok {
		_spec.SetField(mobileskill.FieldNameZh, field.TypeString, value)
		_node.NameZh = value
	}
	if value, ok := _c.mutation.DescriptionZh(); ok {
		_spec.SetField(mobileskill.FieldDescriptionZh, field.TypeString, value)
		_node.DescriptionZh = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(mobileskill.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.IconURL(); ok {
		_spec.SetField(mobileskill.FieldIconURL, field.TypeString, value)
		_node.IconURL = value
	}
	if value, ok := _c.mutation.CoverURL(); ok {
		_spec.SetField(mobileskill.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := _c.mutation.CurrentVersion(); ok {
		_spec.SetField(mobileskill.FieldCurrentVersion, field.TypeInt, value)
		_node.CurrentVersion = value
	}
	if value, ok := _c.mutation.PublishedVersion(); ok {
		_spec.SetField(mobileskill.FieldPublishedVersion, field.TypeInt, value)
		_node.PublishedVersion = &value
	}
	if value, ok := _c.mutation.Featured(); ok {
		_spec.SetField(mobileskill.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(mobileskill.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileskill.VersionsTable,
			Columns: []string{mobileskill.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mobileskillversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserInstallsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mobileskill.UserInstallsTable,
			Columns: []string{mobileskill.UserInstallsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usermobileskill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MobileSkill.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MobileSkillUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MobileSkillCreate) OnConflict(opts ...sql.ConflictOption) *MobileSkillUpsertOne {
	_c.conflict = opts
	return &MobileSkillUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MobileSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MobileSkillCreate) OnConflictColumns(columns ...string) *MobileSkillUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MobileSkillUpsertOne{
		create: _c,
	}
}

type (
	// MobileSkillUpsertOne is the builder for "upsert"-ing
	//  one MobileSkill node.
	MobileSkillUpsertOne struct {
		create *MobileSkillCreate
	}

	// MobileSkillUpsert is the "OnConflict" setter.
	MobileSkillUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MobileSkillUpsert) SetUpdatedAt(v time.Time) *MobileSkillUpsert {
	u.Set(mobileskill.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateUpdatedAt() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldUpdatedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *MobileSkillUpsert) SetSlug(v string) *MobileSkillUpsert {
	u.Set(mobileskill.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateSlug() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldSlug)
	return u
}

// SetStatus sets the "status" field.
func (u *MobileSkillUpsert) SetStatus(v mobileskill.Status) *MobileSkillUpsert {
	u.Set(mobileskill.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateStatus() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldStatus)
	return u
}

// SetNameZh sets the "name_zh" field.
func (u *MobileSkillUpsert) SetNameZh(v string) *MobileSkillUpsert {
	u.Set(mobileskill.FieldNameZh, v)
	return u
}

// UpdateNameZh sets the "name_zh" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateNameZh() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldNameZh)
	return u
}

// SetDescriptionZh sets the "description_zh" field.
func (u *MobileSkillUpsert) SetDescriptionZh(v string) *MobileSkillUpsert {
	u.Set(mobileskill.FieldDescriptionZh, v)
	return u
}

// UpdateDescriptionZh sets the "description_zh" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateDescriptionZh() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldDescriptionZh)
	return u
}

// SetCategory sets the "category" field.
func (u *MobileSkillUpsert) SetCategory(v string) *MobileSkillUpsert {
	u.Set(mobileskill.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateCategory() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldCategory)
	return u
}

// SetIconURL sets the "icon_url" field.
func (u *MobileSkillUpsert) SetIconURL(v string) *MobileSkillUpsert {
	u.Set(mobileskill.FieldIconURL, v)
	return u
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateIconURL() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldIconURL)
	return u
}

// SetCoverURL sets the "cover_url" field.
func (u *MobileSkillUpsert) SetCoverURL(v string) *MobileSkillUpsert {
	u.Set(mobileskill.FieldCoverURL, v)
	return u
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateCoverURL() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldCoverURL)
	return u
}

// SetCurrentVersion sets the "current_version" field.
func (u *MobileSkillUpsert) SetCurrentVersion(v int) *MobileSkillUpsert {
	u.Set(mobileskill.FieldCurrentVersion, v)
	return u
}

// UpdateCurrentVersion sets the "current_version" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateCurrentVersion() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldCurrentVersion)
	return u
}

// AddCurrentVersion adds v to the "current_version" field.
func (u *MobileSkillUpsert) AddCurrentVersion(v int) *MobileSkillUpsert {
	u.Add(mobileskill.FieldCurrentVersion, v)
	return u
}

// SetPublishedVersion sets the "published_version" field.
func (u *MobileSkillUpsert) SetPublishedVersion(v int) *MobileSkillUpsert {
	u.Set(mobileskill.FieldPublishedVersion, v)
	return u
}

// UpdatePublishedVersion sets the "published_version" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdatePublishedVersion() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldPublishedVersion)
	return u
}

// AddPublishedVersion adds v to the "published_version" field.
func (u *MobileSkillUpsert) AddPublishedVersion(v int) *MobileSkillUpsert {
	u.Add(mobileskill.FieldPublishedVersion, v)
	return u
}

// ClearPublishedVersion clears the value of the "published_version" field.
func (u *MobileSkillUpsert) ClearPublishedVersion() *MobileSkillUpsert {
	u.SetNull(mobileskill.FieldPublishedVersion)
	return u
}

// SetFeatured sets the "featured" field.
func (u *MobileSkillUpsert) SetFeatured(v bool) *MobileSkillUpsert {
	u.Set(mobileskill.FieldFeatured, v)
	return u
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateFeatured() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldFeatured)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *MobileSkillUpsert) SetSortOrder(v int) *MobileSkillUpsert {
	u.Set(mobileskill.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *MobileSkillUpsert) UpdateSortOrder() *MobileSkillUpsert {
	u.SetExcluded(mobileskill.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *MobileSkillUpsert) AddSortOrder(v int) *MobileSkillUpsert {
	u.Add(mobileskill.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MobileSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MobileSkillUpsertOne) UpdateNewValues() *MobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mobileskill.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MobileSkill.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MobileSkillUpsertOne) Ignore() *MobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MobileSkillUpsertOne) DoNothing() *MobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MobileSkillCreate.OnConflict
// documentation for more info.
func (u *MobileSkillUpsertOne) Update(set func(*MobileSkillUpsert)) *MobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MobileSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MobileSkillUpsertOne) SetUpdatedAt(v time.Time) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateUpdatedAt() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *MobileSkillUpsertOne) SetSlug(v string) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateSlug() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateSlug()
	})
}

// SetStatus sets the "status" field.
func (u *MobileSkillUpsertOne) SetStatus(v mobileskill.Status) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateStatus() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateStatus()
	})
}

// SetNameZh sets the "name_zh" field.
func (u *MobileSkillUpsertOne) SetNameZh(v string) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetNameZh(v)
	})
}

// UpdateNameZh sets the "name_zh" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateNameZh() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateNameZh()
	})
}

// SetDescriptionZh sets the "description_zh" field.
func (u *MobileSkillUpsertOne) SetDescriptionZh(v string) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetDescriptionZh(v)
	})
}

// UpdateDescriptionZh sets the "description_zh" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateDescriptionZh() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateDescriptionZh()
	})
}

// SetCategory sets the "category" field.
func (u *MobileSkillUpsertOne) SetCategory(v string) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateCategory() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateCategory()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *MobileSkillUpsertOne) SetIconURL(v string) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateIconURL() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateIconURL()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *MobileSkillUpsertOne) SetCoverURL(v string) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateCoverURL() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateCoverURL()
	})
}

// SetCurrentVersion sets the "current_version" field.
func (u *MobileSkillUpsertOne) SetCurrentVersion(v int) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetCurrentVersion(v)
	})
}

// AddCurrentVersion adds v to the "current_version" field.
func (u *MobileSkillUpsertOne) AddCurrentVersion(v int) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.AddCurrentVersion(v)
	})
}

// UpdateCurrentVersion sets the "current_version" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateCurrentVersion() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateCurrentVersion()
	})
}

// SetPublishedVersion sets the "published_version" field.
func (u *MobileSkillUpsertOne) SetPublishedVersion(v int) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetPublishedVersion(v)
	})
}

// AddPublishedVersion adds v to the "published_version" field.
func (u *MobileSkillUpsertOne) AddPublishedVersion(v int) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.AddPublishedVersion(v)
	})
}

// UpdatePublishedVersion sets the "published_version" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdatePublishedVersion() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdatePublishedVersion()
	})
}

// ClearPublishedVersion clears the value of the "published_version" field.
func (u *MobileSkillUpsertOne) ClearPublishedVersion() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.ClearPublishedVersion()
	})
}

// SetFeatured sets the "featured" field.
func (u *MobileSkillUpsertOne) SetFeatured(v bool) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetFeatured(v)
	})
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateFeatured() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateFeatured()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *MobileSkillUpsertOne) SetSortOrder(v int) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *MobileSkillUpsertOne) AddSortOrder(v int) *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *MobileSkillUpsertOne) UpdateSortOrder() *MobileSkillUpsertOne {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *MobileSkillUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MobileSkillCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MobileSkillUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MobileSkillUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MobileSkillUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MobileSkillCreateBulk is the builder for creating many MobileSkill entities in bulk.
type MobileSkillCreateBulk struct {
	config
	err      error
	builders []*MobileSkillCreate
	conflict []sql.ConflictOption
}

// Save creates the MobileSkill entities in the database.
func (_c *MobileSkillCreateBulk) Save(ctx context.Context) ([]*MobileSkill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MobileSkill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MobileSkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MobileSkillCreateBulk) SaveX(ctx context.Context) []*MobileSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MobileSkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MobileSkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MobileSkill.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MobileSkillUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MobileSkillCreateBulk) OnConflict(opts ...sql.ConflictOption) *MobileSkillUpsertBulk {
	_c.conflict = opts
	return &MobileSkillUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MobileSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MobileSkillCreateBulk) OnConflictColumns(columns ...string) *MobileSkillUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MobileSkillUpsertBulk{
		create: _c,
	}
}

// MobileSkillUpsertBulk is the builder for "upsert"-ing
// a bulk of MobileSkill nodes.
type MobileSkillUpsertBulk struct {
	create *MobileSkillCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MobileSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MobileSkillUpsertBulk) UpdateNewValues() *MobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mobileskill.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MobileSkill.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MobileSkillUpsertBulk) Ignore() *MobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MobileSkillUpsertBulk) DoNothing() *MobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MobileSkillCreateBulk.OnConflict
// documentation for more info.
func (u *MobileSkillUpsertBulk) Update(set func(*MobileSkillUpsert)) *MobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MobileSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MobileSkillUpsertBulk) SetUpdatedAt(v time.Time) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateUpdatedAt() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *MobileSkillUpsertBulk) SetSlug(v string) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateSlug() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateSlug()
	})
}

// SetStatus sets the "status" field.
func (u *MobileSkillUpsertBulk) SetStatus(v mobileskill.Status) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateStatus() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateStatus()
	})
}

// SetNameZh sets the "name_zh" field.
func (u *MobileSkillUpsertBulk) SetNameZh(v string) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetNameZh(v)
	})
}

// UpdateNameZh sets the "name_zh" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateNameZh() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateNameZh()
	})
}

// SetDescriptionZh sets the "description_zh" field.
func (u *MobileSkillUpsertBulk) SetDescriptionZh(v string) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetDescriptionZh(v)
	})
}

// UpdateDescriptionZh sets the "description_zh" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateDescriptionZh() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateDescriptionZh()
	})
}

// SetCategory sets the "category" field.
func (u *MobileSkillUpsertBulk) SetCategory(v string) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateCategory() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateCategory()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *MobileSkillUpsertBulk) SetIconURL(v string) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateIconURL() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateIconURL()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *MobileSkillUpsertBulk) SetCoverURL(v string) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateCoverURL() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateCoverURL()
	})
}

// SetCurrentVersion sets the "current_version" field.
func (u *MobileSkillUpsertBulk) SetCurrentVersion(v int) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetCurrentVersion(v)
	})
}

// AddCurrentVersion adds v to the "current_version" field.
func (u *MobileSkillUpsertBulk) AddCurrentVersion(v int) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.AddCurrentVersion(v)
	})
}

// UpdateCurrentVersion sets the "current_version" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateCurrentVersion() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateCurrentVersion()
	})
}

// SetPublishedVersion sets the "published_version" field.
func (u *MobileSkillUpsertBulk) SetPublishedVersion(v int) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetPublishedVersion(v)
	})
}

// AddPublishedVersion adds v to the "published_version" field.
func (u *MobileSkillUpsertBulk) AddPublishedVersion(v int) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.AddPublishedVersion(v)
	})
}

// UpdatePublishedVersion sets the "published_version" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdatePublishedVersion() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdatePublishedVersion()
	})
}

// ClearPublishedVersion clears the value of the "published_version" field.
func (u *MobileSkillUpsertBulk) ClearPublishedVersion() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.ClearPublishedVersion()
	})
}

// SetFeatured sets the "featured" field.
func (u *MobileSkillUpsertBulk) SetFeatured(v bool) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetFeatured(v)
	})
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateFeatured() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateFeatured()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *MobileSkillUpsertBulk) SetSortOrder(v int) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *MobileSkillUpsertBulk) AddSortOrder(v int) *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *MobileSkillUpsertBulk) UpdateSortOrder() *MobileSkillUpsertBulk {
	return u.Update(func(s *MobileSkillUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *MobileSkillUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MobileSkillCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MobileSkillCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MobileSkillUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
