// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementhold"
)

// SubscriptionEntitlementHoldUpdate is the builder for updating SubscriptionEntitlementHold entities.
type SubscriptionEntitlementHoldUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionEntitlementHoldMutation
}

// Where appends a list predicates to the SubscriptionEntitlementHoldUpdate builder.
func (_u *SubscriptionEntitlementHoldUpdate) Where(ps ...predicate.SubscriptionEntitlementHold) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetEntitlementID(v int64) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.ResetEntitlementID()
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableEntitlementID(v *int64) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// AddEntitlementID adds value to the "entitlement_id" field.
func (_u *SubscriptionEntitlementHoldUpdate) AddEntitlementID(v int64) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.AddEntitlementID(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetRequestID(v string) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableRequestID(v *string) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetRequestFingerprint(v string) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableRequestFingerprint(v *string) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetReservedUsd sets the "reserved_usd" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetReservedUsd(v float64) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.ResetReservedUsd()
	_u.mutation.SetReservedUsd(v)
	return _u
}

// SetNillableReservedUsd sets the "reserved_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableReservedUsd(v *float64) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetReservedUsd(*v)
	}
	return _u
}

// AddReservedUsd adds value to the "reserved_usd" field.
func (_u *SubscriptionEntitlementHoldUpdate) AddReservedUsd(v float64) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.AddReservedUsd(v)
	return _u
}

// SetCapturedUsd sets the "captured_usd" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetCapturedUsd(v float64) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.ResetCapturedUsd()
	_u.mutation.SetCapturedUsd(v)
	return _u
}

// SetNillableCapturedUsd sets the "captured_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableCapturedUsd(v *float64) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetCapturedUsd(*v)
	}
	return _u
}

// AddCapturedUsd adds value to the "captured_usd" field.
func (_u *SubscriptionEntitlementHoldUpdate) AddCapturedUsd(v float64) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.AddCapturedUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetStatus(v string) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableStatus(v *string) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetExpiresAt(v time.Time) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetCapturedAt(v time.Time) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableCapturedAt(v *time.Time) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (_u *SubscriptionEntitlementHoldUpdate) ClearCapturedAt() *SubscriptionEntitlementHoldUpdate {
	_u.mutation.ClearCapturedAt()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetReleasedAt(v time.Time) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdate) SetNillableReleasedAt(v *time.Time) *SubscriptionEntitlementHoldUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *SubscriptionEntitlementHoldUpdate) ClearReleasedAt() *SubscriptionEntitlementHoldUpdate {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionEntitlementHoldUpdate) SetUpdatedAt(v time.Time) *SubscriptionEntitlementHoldUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionEntitlementHoldMutation object of the builder.
func (_u *SubscriptionEntitlementHoldUpdate) Mutation() *SubscriptionEntitlementHoldMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionEntitlementHoldUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementHoldUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionEntitlementHoldUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementHoldUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionEntitlementHoldUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionentitlementhold.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementHoldUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := subscriptionentitlementhold.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := subscriptionentitlementhold.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionentitlementhold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEntitlementHoldUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlementhold.Table, subscriptionentitlementhold.Columns, sqlgraph.NewFieldSpec(subscriptionentitlementhold.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntitlementID(); ok {
		_spec.AddField(subscriptionentitlementhold.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservedUsd(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedUsd(); ok {
		_spec.AddField(subscriptionentitlementhold.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapturedUsd(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCapturedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCapturedUsd(); ok {
		_spec.AddField(subscriptionentitlementhold.FieldCapturedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCapturedAt, field.TypeTime, value)
	}
	if _u.mutation.CapturedAtCleared() {
		_spec.ClearField(subscriptionentitlementhold.FieldCapturedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(subscriptionentitlementhold.FieldReleasedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlementhold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionEntitlementHoldUpdateOne is the builder for updating a single SubscriptionEntitlementHold entity.
type SubscriptionEntitlementHoldUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionEntitlementHoldMutation
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetEntitlementID(v int64) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.ResetEntitlementID()
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableEntitlementID(v *int64) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// AddEntitlementID adds value to the "entitlement_id" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) AddEntitlementID(v int64) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.AddEntitlementID(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetRequestID(v string) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableRequestID(v *string) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetRequestFingerprint(v string) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableRequestFingerprint(v *string) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetReservedUsd sets the "reserved_usd" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetReservedUsd(v float64) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.ResetReservedUsd()
	_u.mutation.SetReservedUsd(v)
	return _u
}

// SetNillableReservedUsd sets the "reserved_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableReservedUsd(v *float64) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetReservedUsd(*v)
	}
	return _u
}

// AddReservedUsd adds value to the "reserved_usd" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) AddReservedUsd(v float64) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.AddReservedUsd(v)
	return _u
}

// SetCapturedUsd sets the "captured_usd" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetCapturedUsd(v float64) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.ResetCapturedUsd()
	_u.mutation.SetCapturedUsd(v)
	return _u
}

// SetNillableCapturedUsd sets the "captured_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableCapturedUsd(v *float64) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetCapturedUsd(*v)
	}
	return _u
}

// AddCapturedUsd adds value to the "captured_usd" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) AddCapturedUsd(v float64) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.AddCapturedUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetStatus(v string) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableStatus(v *string) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetExpiresAt(v time.Time) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetCapturedAt(v time.Time) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableCapturedAt(v *time.Time) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) ClearCapturedAt() *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.ClearCapturedAt()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetReleasedAt(v time.Time) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetNillableReleasedAt(v *time.Time) *SubscriptionEntitlementHoldUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) ClearReleasedAt() *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionEntitlementHoldUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionEntitlementHoldMutation object of the builder.
func (_u *SubscriptionEntitlementHoldUpdateOne) Mutation() *SubscriptionEntitlementHoldMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionEntitlementHoldUpdate builder.
func (_u *SubscriptionEntitlementHoldUpdateOne) Where(ps ...predicate.SubscriptionEntitlementHold) *SubscriptionEntitlementHoldUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionEntitlementHoldUpdateOne) Select(field string, fields ...string) *SubscriptionEntitlementHoldUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionEntitlementHold entity.
func (_u *SubscriptionEntitlementHoldUpdateOne) Save(ctx context.Context) (*SubscriptionEntitlementHold, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementHoldUpdateOne) SaveX(ctx context.Context) *SubscriptionEntitlementHold {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionEntitlementHoldUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementHoldUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionEntitlementHoldUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionentitlementhold.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementHoldUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := subscriptionentitlementhold.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := subscriptionentitlementhold.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionentitlementhold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEntitlementHoldUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionEntitlementHold, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlementhold.Table, subscriptionentitlementhold.Columns, sqlgraph.NewFieldSpec(subscriptionentitlementhold.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionEntitlementHold.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionentitlementhold.FieldID)
		for _, f := range fields {
			if !subscriptionentitlementhold.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionentitlementhold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntitlementID(); ok {
		_spec.AddField(subscriptionentitlementhold.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservedUsd(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedUsd(); ok {
		_spec.AddField(subscriptionentitlementhold.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapturedUsd(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCapturedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCapturedUsd(); ok {
		_spec.AddField(subscriptionentitlementhold.FieldCapturedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCapturedAt, field.TypeTime, value)
	}
	if _u.mutation.CapturedAtCleared() {
		_spec.ClearField(subscriptionentitlementhold.FieldCapturedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(subscriptionentitlementhold.FieldReleasedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionEntitlementHold{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlementhold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
