// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlement"
)

// SubscriptionEntitlement is the model entity for the SubscriptionEntitlement schema.
type SubscriptionEntitlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// QuotaMode holds the value of the "quota_mode" field.
	QuotaMode string `json:"quota_mode,omitempty"`
	// QuotaLimitUsd holds the value of the "quota_limit_usd" field.
	QuotaLimitUsd float64 `json:"quota_limit_usd,omitempty"`
	// QuotaUsedUsd holds the value of the "quota_used_usd" field.
	QuotaUsedUsd float64 `json:"quota_used_usd,omitempty"`
	// QuotaReservedUsd holds the value of the "quota_reserved_usd" field.
	QuotaReservedUsd float64 `json:"quota_reserved_usd,omitempty"`
	// DurationHours holds the value of the "duration_hours" field.
	DurationHours int `json:"duration_hours,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt *time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// ActivatedAt holds the value of the "activated_at" field.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// ExhaustedAt holds the value of the "exhausted_at" field.
	ExhaustedAt *time.Time `json:"exhausted_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionEntitlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionentitlement.FieldQuotaLimitUsd, subscriptionentitlement.FieldQuotaUsedUsd, subscriptionentitlement.FieldQuotaReservedUsd:
			values[i] = new(sql.NullFloat64)
		case subscriptionentitlement.FieldID, subscriptionentitlement.FieldUserID, subscriptionentitlement.FieldGroupID, subscriptionentitlement.FieldPlanID, subscriptionentitlement.FieldPaymentOrderID, subscriptionentitlement.FieldDurationHours:
			values[i] = new(sql.NullInt64)
		case subscriptionentitlement.FieldSourceType, subscriptionentitlement.FieldSourceID, subscriptionentitlement.FieldQuotaMode, subscriptionentitlement.FieldStatus:
			values[i] = new(sql.NullString)
		case subscriptionentitlement.FieldStartsAt, subscriptionentitlement.FieldExpiresAt, subscriptionentitlement.FieldActivatedAt, subscriptionentitlement.FieldExhaustedAt, subscriptionentitlement.FieldEndedAt, subscriptionentitlement.FieldCreatedAt, subscriptionentitlement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionEntitlement fields.
func (_m *SubscriptionEntitlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionentitlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionentitlement.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionentitlement.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionentitlement.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case subscriptionentitlement.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case subscriptionentitlement.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case subscriptionentitlement.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case subscriptionentitlement.FieldQuotaMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quota_mode", values[i])
			} else if value.Valid {
				_m.QuotaMode = value.String
			}
		case subscriptionentitlement.FieldQuotaLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_limit_usd", values[i])
			} else if value.Valid {
				_m.QuotaLimitUsd = value.Float64
			}
		case subscriptionentitlement.FieldQuotaUsedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_used_usd", values[i])
			} else if value.Valid {
				_m.QuotaUsedUsd = value.Float64
			}
		case subscriptionentitlement.FieldQuotaReservedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_reserved_usd", values[i])
			} else if value.Valid {
				_m.QuotaReservedUsd = value.Float64
			}
		case subscriptionentitlement.FieldDurationHours:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_hours", values[i])
			} else if value.Valid {
				_m.DurationHours = int(value.Int64)
			}
		case subscriptionentitlement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionentitlement.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = new(time.Time)
				*_m.StartsAt = value.Time
			}
		case subscriptionentitlement.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case subscriptionentitlement.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case subscriptionentitlement.FieldExhaustedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field exhausted_at", values[i])
			} else if value.Valid {
				_m.ExhaustedAt = new(time.Time)
				*_m.ExhaustedAt = value.Time
			}
		case subscriptionentitlement.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case subscriptionentitlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionentitlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionEntitlement.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionEntitlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionEntitlement.
// Note that you need to call SubscriptionEntitlement.Unwrap() before calling this method if this SubscriptionEntitlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionEntitlement) Update() *SubscriptionEntitlementUpdateOne {
	return NewSubscriptionEntitlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionEntitlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionEntitlement) Unwrap() *SubscriptionEntitlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionEntitlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionEntitlement) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionEntitlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("quota_mode=")
	builder.WriteString(_m.QuotaMode)
	builder.WriteString(", ")
	builder.WriteString("quota_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("quota_used_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaUsedUsd))
	builder.WriteString(", ")
	builder.WriteString("quota_reserved_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaReservedUsd))
	builder.WriteString(", ")
	builder.WriteString("duration_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationHours))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.StartsAt; v != nil {
		builder.WriteString("starts_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExhaustedAt; v != nil {
		builder.WriteString("exhausted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionEntitlements is a parsable slice of SubscriptionEntitlement.
type SubscriptionEntitlements []*SubscriptionEntitlement
