// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementhold"
)

// SubscriptionEntitlementHoldCreate is the builder for creating a SubscriptionEntitlementHold entity.
type SubscriptionEntitlementHoldCreate struct {
	config
	mutation *SubscriptionEntitlementHoldMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEntitlementID sets the "entitlement_id" field.
func (_c *SubscriptionEntitlementHoldCreate) SetEntitlementID(v int64) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetEntitlementID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *SubscriptionEntitlementHoldCreate) SetRequestID(v string) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *SubscriptionEntitlementHoldCreate) SetRequestFingerprint(v string) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetReservedUsd sets the "reserved_usd" field.
func (_c *SubscriptionEntitlementHoldCreate) SetReservedUsd(v float64) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetReservedUsd(v)
	return _c
}

// SetCapturedUsd sets the "captured_usd" field.
func (_c *SubscriptionEntitlementHoldCreate) SetCapturedUsd(v float64) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetCapturedUsd(v)
	return _c
}

// SetNillableCapturedUsd sets the "captured_usd" field if the given value is not nil.
func (_c *SubscriptionEntitlementHoldCreate) SetNillableCapturedUsd(v *float64) *SubscriptionEntitlementHoldCreate {
	if v != nil {
		_c.SetCapturedUsd(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionEntitlementHoldCreate) SetStatus(v string) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionEntitlementHoldCreate) SetNillableStatus(v *string) *SubscriptionEntitlementHoldCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubscriptionEntitlementHoldCreate) SetExpiresAt(v time.Time) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *SubscriptionEntitlementHoldCreate) SetCapturedAt(v time.Time) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *SubscriptionEntitlementHoldCreate) SetNillableCapturedAt(v *time.Time) *SubscriptionEntitlementHoldCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *SubscriptionEntitlementHoldCreate) SetReleasedAt(v time.Time) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *SubscriptionEntitlementHoldCreate) SetNillableReleasedAt(v *time.Time) *SubscriptionEntitlementHoldCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionEntitlementHoldCreate) SetCreatedAt(v time.Time) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionEntitlementHoldCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionEntitlementHoldCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionEntitlementHoldCreate) SetUpdatedAt(v time.Time) *SubscriptionEntitlementHoldCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionEntitlementHoldCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionEntitlementHoldCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SubscriptionEntitlementHoldMutation object of the builder.
func (_c *SubscriptionEntitlementHoldCreate) Mutation() *SubscriptionEntitlementHoldMutation {
	return _c.mutation
}

// Save creates the SubscriptionEntitlementHold in the database.
func (_c *SubscriptionEntitlementHoldCreate) Save(ctx context.Context) (*SubscriptionEntitlementHold, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionEntitlementHoldCreate) SaveX(ctx context.Context) *SubscriptionEntitlementHold {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEntitlementHoldCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEntitlementHoldCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionEntitlementHoldCreate) defaults() {
	if _, ok := _c.mutation.CapturedUsd(); !ok {
		v := subscriptionentitlementhold.DefaultCapturedUsd
		_c.mutation.SetCapturedUsd(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionentitlementhold.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionentitlementhold.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionentitlementhold.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionEntitlementHoldCreate) check() error {
	if _, ok := _c.mutation.EntitlementID(); !ok {
		return &ValidationError{Name: "entitlement_id", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.entitlement_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := subscriptionentitlementhold.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := subscriptionentitlementhold.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.request_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReservedUsd(); !ok {
		return &ValidationError{Name: "reserved_usd", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.reserved_usd"`)}
	}
	if _, ok := _c.mutation.CapturedUsd(); !ok {
		return &ValidationError{Name: "captured_usd", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.captured_usd"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionentitlementhold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementHold.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionEntitlementHold.updated_at"`)}
	}
	return nil
}

func (_c *SubscriptionEntitlementHoldCreate) sqlSave(ctx context.Context) (*SubscriptionEntitlementHold, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionEntitlementHoldCreate) createSpec() (*SubscriptionEntitlementHold, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionEntitlementHold{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionentitlementhold.Table, sqlgraph.NewFieldSpec(subscriptionentitlementhold.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldEntitlementID, field.TypeInt64, value)
		_node.EntitlementID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.ReservedUsd(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldReservedUsd, field.TypeFloat64, value)
		_node.ReservedUsd = value
	}
	if value, ok := _c.mutation.CapturedUsd(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCapturedUsd, field.TypeFloat64, value)
		_node.CapturedUsd = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = &value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionentitlementhold.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionEntitlementHold.Create().
//		SetEntitlementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionEntitlementHoldUpsert) {
//			SetEntitlementID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionEntitlementHoldCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionEntitlementHoldUpsertOne {
	_c.conflict = opts
	return &SubscriptionEntitlementHoldUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementHold.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionEntitlementHoldCreate) OnConflictColumns(columns ...string) *SubscriptionEntitlementHoldUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionEntitlementHoldUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionEntitlementHoldUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionEntitlementHold node.
	SubscriptionEntitlementHoldUpsertOne struct {
		create *SubscriptionEntitlementHoldCreate
	}

	// SubscriptionEntitlementHoldUpsert is the "OnConflict" setter.
	SubscriptionEntitlementHoldUpsert struct {
		*sql.UpdateSet
	}
)

// SetEntitlementID sets the "entitlement_id" field.
func (u *SubscriptionEntitlementHoldUpsert) SetEntitlementID(v int64) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldEntitlementID, v)
	return u
}

// UpdateEntitlementID sets the "entitlement_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateEntitlementID() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldEntitlementID)
	return u
}

// AddEntitlementID adds v to the "entitlement_id" field.
func (u *SubscriptionEntitlementHoldUpsert) AddEntitlementID(v int64) *SubscriptionEntitlementHoldUpsert {
	u.Add(subscriptionentitlementhold.FieldEntitlementID, v)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *SubscriptionEntitlementHoldUpsert) SetRequestID(v string) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateRequestID() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldRequestID)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *SubscriptionEntitlementHoldUpsert) SetRequestFingerprint(v string) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateRequestFingerprint() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldRequestFingerprint)
	return u
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *SubscriptionEntitlementHoldUpsert) SetReservedUsd(v float64) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldReservedUsd, v)
	return u
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateReservedUsd() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldReservedUsd)
	return u
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *SubscriptionEntitlementHoldUpsert) AddReservedUsd(v float64) *SubscriptionEntitlementHoldUpsert {
	u.Add(subscriptionentitlementhold.FieldReservedUsd, v)
	return u
}

// SetCapturedUsd sets the "captured_usd" field.
func (u *SubscriptionEntitlementHoldUpsert) SetCapturedUsd(v float64) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldCapturedUsd, v)
	return u
}

// UpdateCapturedUsd sets the "captured_usd" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateCapturedUsd() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldCapturedUsd)
	return u
}

// AddCapturedUsd adds v to the "captured_usd" field.
func (u *SubscriptionEntitlementHoldUpsert) AddCapturedUsd(v float64) *SubscriptionEntitlementHoldUpsert {
	u.Add(subscriptionentitlementhold.FieldCapturedUsd, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionEntitlementHoldUpsert) SetStatus(v string) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateStatus() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionEntitlementHoldUpsert) SetExpiresAt(v time.Time) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateExpiresAt() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldExpiresAt)
	return u
}

// SetCapturedAt sets the "captured_at" field.
func (u *SubscriptionEntitlementHoldUpsert) SetCapturedAt(v time.Time) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldCapturedAt, v)
	return u
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateCapturedAt() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldCapturedAt)
	return u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *SubscriptionEntitlementHoldUpsert) ClearCapturedAt() *SubscriptionEntitlementHoldUpsert {
	u.SetNull(subscriptionentitlementhold.FieldCapturedAt)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *SubscriptionEntitlementHoldUpsert) SetReleasedAt(v time.Time) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateReleasedAt() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldReleasedAt)
	return u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *SubscriptionEntitlementHoldUpsert) ClearReleasedAt() *SubscriptionEntitlementHoldUpsert {
	u.SetNull(subscriptionentitlementhold.FieldReleasedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionEntitlementHoldUpsert) SetUpdatedAt(v time.Time) *SubscriptionEntitlementHoldUpsert {
	u.Set(subscriptionentitlementhold.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsert) UpdateUpdatedAt() *SubscriptionEntitlementHoldUpsert {
	u.SetExcluded(subscriptionentitlementhold.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementHold.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateNewValues() *SubscriptionEntitlementHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionentitlementhold.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementHold.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionEntitlementHoldUpsertOne) Ignore() *SubscriptionEntitlementHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionEntitlementHoldUpsertOne) DoNothing() *SubscriptionEntitlementHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionEntitlementHoldCreate.OnConflict
// documentation for more info.
func (u *SubscriptionEntitlementHoldUpsertOne) Update(set func(*SubscriptionEntitlementHoldUpsert)) *SubscriptionEntitlementHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionEntitlementHoldUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntitlementID sets the "entitlement_id" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetEntitlementID(v int64) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetEntitlementID(v)
	})
}

// AddEntitlementID adds v to the "entitlement_id" field.
func (u *SubscriptionEntitlementHoldUpsertOne) AddEntitlementID(v int64) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.AddEntitlementID(v)
	})
}

// UpdateEntitlementID sets the "entitlement_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateEntitlementID() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateEntitlementID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetRequestID(v string) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateRequestID() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateRequestID()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetRequestFingerprint(v string) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateRequestFingerprint() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetReservedUsd(v float64) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetReservedUsd(v)
	})
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *SubscriptionEntitlementHoldUpsertOne) AddReservedUsd(v float64) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.AddReservedUsd(v)
	})
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateReservedUsd() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateReservedUsd()
	})
}

// SetCapturedUsd sets the "captured_usd" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetCapturedUsd(v float64) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetCapturedUsd(v)
	})
}

// AddCapturedUsd adds v to the "captured_usd" field.
func (u *SubscriptionEntitlementHoldUpsertOne) AddCapturedUsd(v float64) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.AddCapturedUsd(v)
	})
}

// UpdateCapturedUsd sets the "captured_usd" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateCapturedUsd() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateCapturedUsd()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetStatus(v string) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateStatus() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetExpiresAt(v time.Time) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateExpiresAt() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetCapturedAt(v time.Time) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateCapturedAt() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateCapturedAt()
	})
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *SubscriptionEntitlementHoldUpsertOne) ClearCapturedAt() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.ClearCapturedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetReleasedAt(v time.Time) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateReleasedAt() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *SubscriptionEntitlementHoldUpsertOne) ClearReleasedAt() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.ClearReleasedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionEntitlementHoldUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertOne) UpdateUpdatedAt() *SubscriptionEntitlementHoldUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionEntitlementHoldUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionEntitlementHoldCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionEntitlementHoldUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionEntitlementHoldUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionEntitlementHoldUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionEntitlementHoldCreateBulk is the builder for creating many SubscriptionEntitlementHold entities in bulk.
type SubscriptionEntitlementHoldCreateBulk struct {
	config
	err      error
	builders []*SubscriptionEntitlementHoldCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionEntitlementHold entities in the database.
func (_c *SubscriptionEntitlementHoldCreateBulk) Save(ctx context.Context) ([]*SubscriptionEntitlementHold, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionEntitlementHold, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionEntitlementHoldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionEntitlementHoldCreateBulk) SaveX(ctx context.Context) []*SubscriptionEntitlementHold {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEntitlementHoldCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEntitlementHoldCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionEntitlementHold.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionEntitlementHoldUpsert) {
//			SetEntitlementID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionEntitlementHoldCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionEntitlementHoldUpsertBulk {
	_c.conflict = opts
	return &SubscriptionEntitlementHoldUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementHold.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionEntitlementHoldCreateBulk) OnConflictColumns(columns ...string) *SubscriptionEntitlementHoldUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionEntitlementHoldUpsertBulk{
		create: _c,
	}
}

// SubscriptionEntitlementHoldUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionEntitlementHold nodes.
type SubscriptionEntitlementHoldUpsertBulk struct {
	create *SubscriptionEntitlementHoldCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementHold.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateNewValues() *SubscriptionEntitlementHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionentitlementhold.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementHold.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionEntitlementHoldUpsertBulk) Ignore() *SubscriptionEntitlementHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionEntitlementHoldUpsertBulk) DoNothing() *SubscriptionEntitlementHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionEntitlementHoldCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionEntitlementHoldUpsertBulk) Update(set func(*SubscriptionEntitlementHoldUpsert)) *SubscriptionEntitlementHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionEntitlementHoldUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntitlementID sets the "entitlement_id" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetEntitlementID(v int64) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetEntitlementID(v)
	})
}

// AddEntitlementID adds v to the "entitlement_id" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) AddEntitlementID(v int64) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.AddEntitlementID(v)
	})
}

// UpdateEntitlementID sets the "entitlement_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateEntitlementID() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateEntitlementID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetRequestID(v string) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateRequestID() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateRequestID()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetRequestFingerprint(v string) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateRequestFingerprint() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetReservedUsd(v float64) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetReservedUsd(v)
	})
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) AddReservedUsd(v float64) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.AddReservedUsd(v)
	})
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateReservedUsd() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateReservedUsd()
	})
}

// SetCapturedUsd sets the "captured_usd" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetCapturedUsd(v float64) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetCapturedUsd(v)
	})
}

// AddCapturedUsd adds v to the "captured_usd" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) AddCapturedUsd(v float64) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.AddCapturedUsd(v)
	})
}

// UpdateCapturedUsd sets the "captured_usd" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateCapturedUsd() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateCapturedUsd()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetStatus(v string) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateStatus() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetExpiresAt(v time.Time) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateExpiresAt() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetCapturedAt(v time.Time) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateCapturedAt() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateCapturedAt()
	})
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) ClearCapturedAt() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.ClearCapturedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetReleasedAt(v time.Time) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateReleasedAt() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) ClearReleasedAt() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.ClearReleasedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionEntitlementHoldUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionEntitlementHoldUpsertBulk) UpdateUpdatedAt() *SubscriptionEntitlementHoldUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementHoldUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionEntitlementHoldUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionEntitlementHoldCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionEntitlementHoldCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionEntitlementHoldUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
