// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlement"
)

// SubscriptionEntitlementUpdate is the builder for updating SubscriptionEntitlement entities.
type SubscriptionEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionEntitlementMutation
}

// Where appends a list predicates to the SubscriptionEntitlementUpdate builder.
func (_u *SubscriptionEntitlementUpdate) Where(ps ...predicate.SubscriptionEntitlement) *SubscriptionEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionEntitlementUpdate) SetUserID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableUserID(v *int64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionEntitlementUpdate) AddUserID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionEntitlementUpdate) SetGroupID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableGroupID(v *int64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionEntitlementUpdate) AddGroupID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *SubscriptionEntitlementUpdate) SetPlanID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillablePlanID(v *int64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *SubscriptionEntitlementUpdate) AddPlanID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddPlanID(v)
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *SubscriptionEntitlementUpdate) ClearPlanID() *SubscriptionEntitlementUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionEntitlementUpdate) SetPaymentOrderID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillablePaymentOrderID(v *int64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionEntitlementUpdate) AddPaymentOrderID(v int64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetQuotaMode sets the "quota_mode" field.
func (_u *SubscriptionEntitlementUpdate) SetQuotaMode(v string) *SubscriptionEntitlementUpdate {
	_u.mutation.SetQuotaMode(v)
	return _u
}

// SetNillableQuotaMode sets the "quota_mode" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableQuotaMode(v *string) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetQuotaMode(*v)
	}
	return _u
}

// SetQuotaLimitUsd sets the "quota_limit_usd" field.
func (_u *SubscriptionEntitlementUpdate) SetQuotaLimitUsd(v float64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetQuotaLimitUsd()
	_u.mutation.SetQuotaLimitUsd(v)
	return _u
}

// SetNillableQuotaLimitUsd sets the "quota_limit_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableQuotaLimitUsd(v *float64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetQuotaLimitUsd(*v)
	}
	return _u
}

// AddQuotaLimitUsd adds value to the "quota_limit_usd" field.
func (_u *SubscriptionEntitlementUpdate) AddQuotaLimitUsd(v float64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddQuotaLimitUsd(v)
	return _u
}

// SetQuotaUsedUsd sets the "quota_used_usd" field.
func (_u *SubscriptionEntitlementUpdate) SetQuotaUsedUsd(v float64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetQuotaUsedUsd()
	_u.mutation.SetQuotaUsedUsd(v)
	return _u
}

// SetNillableQuotaUsedUsd sets the "quota_used_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableQuotaUsedUsd(v *float64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetQuotaUsedUsd(*v)
	}
	return _u
}

// AddQuotaUsedUsd adds value to the "quota_used_usd" field.
func (_u *SubscriptionEntitlementUpdate) AddQuotaUsedUsd(v float64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddQuotaUsedUsd(v)
	return _u
}

// SetQuotaReservedUsd sets the "quota_reserved_usd" field.
func (_u *SubscriptionEntitlementUpdate) SetQuotaReservedUsd(v float64) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetQuotaReservedUsd()
	_u.mutation.SetQuotaReservedUsd(v)
	return _u
}

// SetNillableQuotaReservedUsd sets the "quota_reserved_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableQuotaReservedUsd(v *float64) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetQuotaReservedUsd(*v)
	}
	return _u
}

// AddQuotaReservedUsd adds value to the "quota_reserved_usd" field.
func (_u *SubscriptionEntitlementUpdate) AddQuotaReservedUsd(v float64) *SubscriptionEntitlementUpdate {
	_u.mutation.AddQuotaReservedUsd(v)
	return _u
}

// SetDurationHours sets the "duration_hours" field.
func (_u *SubscriptionEntitlementUpdate) SetDurationHours(v int) *SubscriptionEntitlementUpdate {
	_u.mutation.ResetDurationHours()
	_u.mutation.SetDurationHours(v)
	return _u
}

// SetNillableDurationHours sets the "duration_hours" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableDurationHours(v *int) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetDurationHours(*v)
	}
	return _u
}

// AddDurationHours adds value to the "duration_hours" field.
func (_u *SubscriptionEntitlementUpdate) AddDurationHours(v int) *SubscriptionEntitlementUpdate {
	_u.mutation.AddDurationHours(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionEntitlementUpdate) SetStatus(v string) *SubscriptionEntitlementUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableStatus(v *string) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionEntitlementUpdate) SetStartsAt(v time.Time) *SubscriptionEntitlementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableStartsAt(v *time.Time) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *SubscriptionEntitlementUpdate) ClearStartsAt() *SubscriptionEntitlementUpdate {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionEntitlementUpdate) SetExpiresAt(v time.Time) *SubscriptionEntitlementUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionEntitlementUpdate) ClearExpiresAt() *SubscriptionEntitlementUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *SubscriptionEntitlementUpdate) SetActivatedAt(v time.Time) *SubscriptionEntitlementUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableActivatedAt(v *time.Time) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *SubscriptionEntitlementUpdate) ClearActivatedAt() *SubscriptionEntitlementUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetExhaustedAt sets the "exhausted_at" field.
func (_u *SubscriptionEntitlementUpdate) SetExhaustedAt(v time.Time) *SubscriptionEntitlementUpdate {
	_u.mutation.SetExhaustedAt(v)
	return _u
}

// SetNillableExhaustedAt sets the "exhausted_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableExhaustedAt(v *time.Time) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetExhaustedAt(*v)
	}
	return _u
}

// ClearExhaustedAt clears the value of the "exhausted_at" field.
func (_u *SubscriptionEntitlementUpdate) ClearExhaustedAt() *SubscriptionEntitlementUpdate {
	_u.mutation.ClearExhaustedAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SubscriptionEntitlementUpdate) SetEndedAt(v time.Time) *SubscriptionEntitlementUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdate) SetNillableEndedAt(v *time.Time) *SubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SubscriptionEntitlementUpdate) ClearEndedAt() *SubscriptionEntitlementUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionEntitlementUpdate) SetUpdatedAt(v time.Time) *SubscriptionEntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionEntitlementMutation object of the builder.
func (_u *SubscriptionEntitlementUpdate) Mutation() *SubscriptionEntitlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionEntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionEntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementUpdate) check() error {
	if v, ok := _u.mutation.QuotaMode(); ok {
		if err := subscriptionentitlement.QuotaModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_mode", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlement.quota_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlement.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlement.Table, subscriptionentitlement.Columns, sqlgraph.NewFieldSpec(subscriptionentitlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(subscriptionentitlement.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(subscriptionentitlement.FieldPlanID, field.TypeInt64, value)
	}
	if _u.mutation.PlanIDCleared() {
		_spec.ClearField(subscriptionentitlement.FieldPlanID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionentitlement.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionentitlement.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.QuotaMode(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLimitUsd(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaLimitUsd(); ok {
		_spec.AddField(subscriptionentitlement.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedUsd(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedUsd(); ok {
		_spec.AddField(subscriptionentitlement.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaReservedUsd(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaReservedUsd(); ok {
		_spec.AddField(subscriptionentitlement.FieldQuotaReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DurationHours(); ok {
		_spec.SetField(subscriptionentitlement.FieldDurationHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationHours(); ok {
		_spec.AddField(subscriptionentitlement.FieldDurationHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionentitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExhaustedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldExhaustedAt, field.TypeTime, value)
	}
	if _u.mutation.ExhaustedAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldExhaustedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionEntitlementUpdateOne is the builder for updating a single SubscriptionEntitlement entity.
type SubscriptionEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionEntitlementMutation
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionEntitlementUpdateOne) SetUserID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableUserID(v *int64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionEntitlementUpdateOne) AddUserID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionEntitlementUpdateOne) SetGroupID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableGroupID(v *int64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionEntitlementUpdateOne) AddGroupID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *SubscriptionEntitlementUpdateOne) SetPlanID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillablePlanID(v *int64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *SubscriptionEntitlementUpdateOne) AddPlanID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddPlanID(v)
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *SubscriptionEntitlementUpdateOne) ClearPlanID() *SubscriptionEntitlementUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionEntitlementUpdateOne) SetPaymentOrderID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillablePaymentOrderID(v *int64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionEntitlementUpdateOne) AddPaymentOrderID(v int64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// SetQuotaMode sets the "quota_mode" field.
func (_u *SubscriptionEntitlementUpdateOne) SetQuotaMode(v string) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetQuotaMode(v)
	return _u
}

// SetNillableQuotaMode sets the "quota_mode" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableQuotaMode(v *string) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetQuotaMode(*v)
	}
	return _u
}

// SetQuotaLimitUsd sets the "quota_limit_usd" field.
func (_u *SubscriptionEntitlementUpdateOne) SetQuotaLimitUsd(v float64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetQuotaLimitUsd()
	_u.mutation.SetQuotaLimitUsd(v)
	return _u
}

// SetNillableQuotaLimitUsd sets the "quota_limit_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableQuotaLimitUsd(v *float64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetQuotaLimitUsd(*v)
	}
	return _u
}

// AddQuotaLimitUsd adds value to the "quota_limit_usd" field.
func (_u *SubscriptionEntitlementUpdateOne) AddQuotaLimitUsd(v float64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddQuotaLimitUsd(v)
	return _u
}

// SetQuotaUsedUsd sets the "quota_used_usd" field.
func (_u *SubscriptionEntitlementUpdateOne) SetQuotaUsedUsd(v float64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetQuotaUsedUsd()
	_u.mutation.SetQuotaUsedUsd(v)
	return _u
}

// SetNillableQuotaUsedUsd sets the "quota_used_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableQuotaUsedUsd(v *float64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetQuotaUsedUsd(*v)
	}
	return _u
}

// AddQuotaUsedUsd adds value to the "quota_used_usd" field.
func (_u *SubscriptionEntitlementUpdateOne) AddQuotaUsedUsd(v float64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddQuotaUsedUsd(v)
	return _u
}

// SetQuotaReservedUsd sets the "quota_reserved_usd" field.
func (_u *SubscriptionEntitlementUpdateOne) SetQuotaReservedUsd(v float64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetQuotaReservedUsd()
	_u.mutation.SetQuotaReservedUsd(v)
	return _u
}

// SetNillableQuotaReservedUsd sets the "quota_reserved_usd" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableQuotaReservedUsd(v *float64) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetQuotaReservedUsd(*v)
	}
	return _u
}

// AddQuotaReservedUsd adds value to the "quota_reserved_usd" field.
func (_u *SubscriptionEntitlementUpdateOne) AddQuotaReservedUsd(v float64) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddQuotaReservedUsd(v)
	return _u
}

// SetDurationHours sets the "duration_hours" field.
func (_u *SubscriptionEntitlementUpdateOne) SetDurationHours(v int) *SubscriptionEntitlementUpdateOne {
	_u.mutation.ResetDurationHours()
	_u.mutation.SetDurationHours(v)
	return _u
}

// SetNillableDurationHours sets the "duration_hours" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableDurationHours(v *int) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetDurationHours(*v)
	}
	return _u
}

// AddDurationHours adds value to the "duration_hours" field.
func (_u *SubscriptionEntitlementUpdateOne) AddDurationHours(v int) *SubscriptionEntitlementUpdateOne {
	_u.mutation.AddDurationHours(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionEntitlementUpdateOne) SetStatus(v string) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableStatus(v *string) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *SubscriptionEntitlementUpdateOne) SetStartsAt(v time.Time) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableStartsAt(v *time.Time) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (_u *SubscriptionEntitlementUpdateOne) ClearStartsAt() *SubscriptionEntitlementUpdateOne {
	_u.mutation.ClearStartsAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionEntitlementUpdateOne) SetExpiresAt(v time.Time) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionEntitlementUpdateOne) ClearExpiresAt() *SubscriptionEntitlementUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *SubscriptionEntitlementUpdateOne) SetActivatedAt(v time.Time) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableActivatedAt(v *time.Time) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *SubscriptionEntitlementUpdateOne) ClearActivatedAt() *SubscriptionEntitlementUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetExhaustedAt sets the "exhausted_at" field.
func (_u *SubscriptionEntitlementUpdateOne) SetExhaustedAt(v time.Time) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetExhaustedAt(v)
	return _u
}

// SetNillableExhaustedAt sets the "exhausted_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableExhaustedAt(v *time.Time) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetExhaustedAt(*v)
	}
	return _u
}

// ClearExhaustedAt clears the value of the "exhausted_at" field.
func (_u *SubscriptionEntitlementUpdateOne) ClearExhaustedAt() *SubscriptionEntitlementUpdateOne {
	_u.mutation.ClearExhaustedAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SubscriptionEntitlementUpdateOne) SetEndedAt(v time.Time) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementUpdateOne) SetNillableEndedAt(v *time.Time) *SubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SubscriptionEntitlementUpdateOne) ClearEndedAt() *SubscriptionEntitlementUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionEntitlementUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionEntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionEntitlementMutation object of the builder.
func (_u *SubscriptionEntitlementUpdateOne) Mutation() *SubscriptionEntitlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionEntitlementUpdate builder.
func (_u *SubscriptionEntitlementUpdateOne) Where(ps ...predicate.SubscriptionEntitlement) *SubscriptionEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionEntitlementUpdateOne) Select(field string, fields ...string) *SubscriptionEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionEntitlement entity.
func (_u *SubscriptionEntitlementUpdateOne) Save(ctx context.Context) (*SubscriptionEntitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementUpdateOne) SaveX(ctx context.Context) *SubscriptionEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionEntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.QuotaMode(); ok {
		if err := subscriptionentitlement.QuotaModeValidator(v); err != nil {
			return &ValidationError{Name: "quota_mode", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlement.quota_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlement.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlement.Table, subscriptionentitlement.Columns, sqlgraph.NewFieldSpec(subscriptionentitlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionentitlement.FieldID)
		for _, f := range fields {
			if !subscriptionentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(subscriptionentitlement.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(subscriptionentitlement.FieldPlanID, field.TypeInt64, value)
	}
	if _u.mutation.PlanIDCleared() {
		_spec.ClearField(subscriptionentitlement.FieldPlanID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionentitlement.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionentitlement.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.QuotaMode(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLimitUsd(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaLimitUsd(); ok {
		_spec.AddField(subscriptionentitlement.FieldQuotaLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedUsd(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedUsd(); ok {
		_spec.AddField(subscriptionentitlement.FieldQuotaUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaReservedUsd(); ok {
		_spec.SetField(subscriptionentitlement.FieldQuotaReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaReservedUsd(); ok {
		_spec.AddField(subscriptionentitlement.FieldQuotaReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DurationHours(); ok {
		_spec.SetField(subscriptionentitlement.FieldDurationHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationHours(); ok {
		_spec.AddField(subscriptionentitlement.FieldDurationHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionentitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if _u.mutation.StartsAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExhaustedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldExhaustedAt, field.TypeTime, value)
	}
	if _u.mutation.ExhaustedAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldExhaustedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(subscriptionentitlement.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
