// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mobileskill"
	"github.com/Wei-Shaw/sub2api/ent/usermobileskill"
)

// UserMobileSkillCreate is the builder for creating a UserMobileSkill entity.
type UserMobileSkillCreate struct {
	config
	mutation *UserMobileSkillMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserMobileSkillCreate) SetCreatedAt(v time.Time) *UserMobileSkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserMobileSkillCreate) SetNillableCreatedAt(v *time.Time) *UserMobileSkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserMobileSkillCreate) SetUpdatedAt(v time.Time) *UserMobileSkillCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserMobileSkillCreate) SetNillableUpdatedAt(v *time.Time) *UserMobileSkillCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserMobileSkillCreate) SetUserID(v int64) *UserMobileSkillCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *UserMobileSkillCreate) SetSkillID(v int64) *UserMobileSkillCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetInstalledVersion sets the "installed_version" field.
func (_c *UserMobileSkillCreate) SetInstalledVersion(v int) *UserMobileSkillCreate {
	_c.mutation.SetInstalledVersion(v)
	return _c
}

// SetPinned sets the "pinned" field.
func (_c *UserMobileSkillCreate) SetPinned(v bool) *UserMobileSkillCreate {
	_c.mutation.SetPinned(v)
	return _c
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_c *UserMobileSkillCreate) SetNillablePinned(v *bool) *UserMobileSkillCreate {
	if v != nil {
		_c.SetPinned(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *UserMobileSkillCreate) SetLastUsedAt(v time.Time) *UserMobileSkillCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *UserMobileSkillCreate) SetNillableLastUsedAt(v *time.Time) *UserMobileSkillCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetSkill sets the "skill" edge to the MobileSkill entity.
func (_c *UserMobileSkillCreate) SetSkill(v *MobileSkill) *UserMobileSkillCreate {
	return _c.SetSkillID(v.ID)
}

// Mutation returns the UserMobileSkillMutation object of the builder.
func (_c *UserMobileSkillCreate) Mutation() *UserMobileSkillMutation {
	return _c.mutation
}

// Save creates the UserMobileSkill in the database.
func (_c *UserMobileSkillCreate) Save(ctx context.Context) (*UserMobileSkill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserMobileSkillCreate) SaveX(ctx context.Context) *UserMobileSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserMobileSkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserMobileSkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserMobileSkillCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usermobileskill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usermobileskill.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Pinned(); !ok {
		v := usermobileskill.DefaultPinned
		_c.mutation.SetPinned(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserMobileSkillCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserMobileSkill.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserMobileSkill.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserMobileSkill.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := usermobileskill.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserMobileSkill.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`ent: missing required field "UserMobileSkill.skill_id"`)}
	}
	if v, ok := _c.mutation.SkillID(); ok {
		if err := usermobileskill.SkillIDValidator(v); err != nil {
			return &ValidationError{Name: "skill_id", err: fmt.Errorf(`ent: validator failed for field "UserMobileSkill.skill_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstalledVersion(); !ok {
		return &ValidationError{Name: "installed_version", err: errors.New(`ent: missing required field "UserMobileSkill.installed_version"`)}
	}
	if v, ok := _c.mutation.InstalledVersion(); ok {
		if err := usermobileskill.InstalledVersionValidator(v); err != nil {
			return &ValidationError{Name: "installed_version", err: fmt.Errorf(`ent: validator failed for field "UserMobileSkill.installed_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pinned(); !ok {
		return &ValidationError{Name: "pinned", err: errors.New(`ent: missing required field "UserMobileSkill.pinned"`)}
	}
	if len(_c.mutation.SkillIDs()) == 0 {
		return &ValidationError{Name: "skill", err: errors.New(`ent: missing required edge "UserMobileSkill.skill"`)}
	}
	return nil
}

func (_c *UserMobileSkillCreate) sqlSave(ctx context.Context) (*UserMobileSkill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserMobileSkillCreate) createSpec() (*UserMobileSkill, *sqlgraph.CreateSpec) {
	var (
		_node = &UserMobileSkill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usermobileskill.Table, sqlgraph.NewFieldSpec(usermobileskill.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usermobileskill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usermobileskill.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usermobileskill.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.InstalledVersion(); ok {
		_spec.SetField(usermobileskill.FieldInstalledVersion, field.TypeInt, value)
		_node.InstalledVersion = value
	}
	if value, ok := _c.mutation.Pinned(); ok {
		_spec.SetField(usermobileskill.FieldPinned, field.TypeBool, value)
		_node.Pinned = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(usermobileskill.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if nodes := _c.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermobileskill.SkillTable,
			Columns: []string{usermobileskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mobileskill.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkillID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserMobileSkill.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserMobileSkillUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserMobileSkillCreate) OnConflict(opts ...sql.ConflictOption) *UserMobileSkillUpsertOne {
	_c.conflict = opts
	return &UserMobileSkillUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserMobileSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserMobileSkillCreate) OnConflictColumns(columns ...string) *UserMobileSkillUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserMobileSkillUpsertOne{
		create: _c,
	}
}

type (
	// UserMobileSkillUpsertOne is the builder for "upsert"-ing
	//  one UserMobileSkill node.
	UserMobileSkillUpsertOne struct {
		create *UserMobileSkillCreate
	}

	// UserMobileSkillUpsert is the "OnConflict" setter.
	UserMobileSkillUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserMobileSkillUpsert) SetUpdatedAt(v time.Time) *UserMobileSkillUpsert {
	u.Set(usermobileskill.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserMobileSkillUpsert) UpdateUpdatedAt() *UserMobileSkillUpsert {
	u.SetExcluded(usermobileskill.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserMobileSkillUpsert) SetUserID(v int64) *UserMobileSkillUpsert {
	u.Set(usermobileskill.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserMobileSkillUpsert) UpdateUserID() *UserMobileSkillUpsert {
	u.SetExcluded(usermobileskill.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserMobileSkillUpsert) AddUserID(v int64) *UserMobileSkillUpsert {
	u.Add(usermobileskill.FieldUserID, v)
	return u
}

// SetSkillID sets the "skill_id" field.
func (u *UserMobileSkillUpsert) SetSkillID(v int64) *UserMobileSkillUpsert {
	u.Set(usermobileskill.FieldSkillID, v)
	return u
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *UserMobileSkillUpsert) UpdateSkillID() *UserMobileSkillUpsert {
	u.SetExcluded(usermobileskill.FieldSkillID)
	return u
}

// SetInstalledVersion sets the "installed_version" field.
func (u *UserMobileSkillUpsert) SetInstalledVersion(v int) *UserMobileSkillUpsert {
	u.Set(usermobileskill.FieldInstalledVersion, v)
	return u
}

// UpdateInstalledVersion sets the "installed_version" field to the value that was provided on create.
func (u *UserMobileSkillUpsert) UpdateInstalledVersion() *UserMobileSkillUpsert {
	u.SetExcluded(usermobileskill.FieldInstalledVersion)
	return u
}

// AddInstalledVersion adds v to the "installed_version" field.
func (u *UserMobileSkillUpsert) AddInstalledVersion(v int) *UserMobileSkillUpsert {
	u.Add(usermobileskill.FieldInstalledVersion, v)
	return u
}

// SetPinned sets the "pinned" field.
func (u *UserMobileSkillUpsert) SetPinned(v bool) *UserMobileSkillUpsert {
	u.Set(usermobileskill.FieldPinned, v)
	return u
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *UserMobileSkillUpsert) UpdatePinned() *UserMobileSkillUpsert {
	u.SetExcluded(usermobileskill.FieldPinned)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserMobileSkillUpsert) SetLastUsedAt(v time.Time) *UserMobileSkillUpsert {
	u.Set(usermobileskill.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserMobileSkillUpsert) UpdateLastUsedAt() *UserMobileSkillUpsert {
	u.SetExcluded(usermobileskill.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserMobileSkillUpsert) ClearLastUsedAt() *UserMobileSkillUpsert {
	u.SetNull(usermobileskill.FieldLastUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserMobileSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserMobileSkillUpsertOne) UpdateNewValues() *UserMobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usermobileskill.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserMobileSkill.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserMobileSkillUpsertOne) Ignore() *UserMobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserMobileSkillUpsertOne) DoNothing() *UserMobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserMobileSkillCreate.OnConflict
// documentation for more info.
func (u *UserMobileSkillUpsertOne) Update(set func(*UserMobileSkillUpsert)) *UserMobileSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserMobileSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserMobileSkillUpsertOne) SetUpdatedAt(v time.Time) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserMobileSkillUpsertOne) UpdateUpdatedAt() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserMobileSkillUpsertOne) SetUserID(v int64) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserMobileSkillUpsertOne) AddUserID(v int64) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserMobileSkillUpsertOne) UpdateUserID() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateUserID()
	})
}

// SetSkillID sets the "skill_id" field.
func (u *UserMobileSkillUpsertOne) SetSkillID(v int64) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetSkillID(v)
	})
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *UserMobileSkillUpsertOne) UpdateSkillID() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateSkillID()
	})
}

// SetInstalledVersion sets the "installed_version" field.
func (u *UserMobileSkillUpsertOne) SetInstalledVersion(v int) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetInstalledVersion(v)
	})
}

// AddInstalledVersion adds v to the "installed_version" field.
func (u *UserMobileSkillUpsertOne) AddInstalledVersion(v int) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.AddInstalledVersion(v)
	})
}

// UpdateInstalledVersion sets the "installed_version" field to the value that was provided on create.
func (u *UserMobileSkillUpsertOne) UpdateInstalledVersion() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateInstalledVersion()
	})
}

// SetPinned sets the "pinned" field.
func (u *UserMobileSkillUpsertOne) SetPinned(v bool) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *UserMobileSkillUpsertOne) UpdatePinned() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdatePinned()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserMobileSkillUpsertOne) SetLastUsedAt(v time.Time) *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserMobileSkillUpsertOne) UpdateLastUsedAt() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserMobileSkillUpsertOne) ClearLastUsedAt() *UserMobileSkillUpsertOne {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *UserMobileSkillUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserMobileSkillCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserMobileSkillUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserMobileSkillUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserMobileSkillUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserMobileSkillCreateBulk is the builder for creating many UserMobileSkill entities in bulk.
type UserMobileSkillCreateBulk struct {
	config
	err      error
	builders []*UserMobileSkillCreate
	conflict []sql.ConflictOption
}

// Save creates the UserMobileSkill entities in the database.
func (_c *UserMobileSkillCreateBulk) Save(ctx context.Context) ([]*UserMobileSkill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserMobileSkill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMobileSkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserMobileSkillCreateBulk) SaveX(ctx context.Context) []*UserMobileSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserMobileSkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserMobileSkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserMobileSkill.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserMobileSkillUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserMobileSkillCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserMobileSkillUpsertBulk {
	_c.conflict = opts
	return &UserMobileSkillUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserMobileSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserMobileSkillCreateBulk) OnConflictColumns(columns ...string) *UserMobileSkillUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserMobileSkillUpsertBulk{
		create: _c,
	}
}

// UserMobileSkillUpsertBulk is the builder for "upsert"-ing
// a bulk of UserMobileSkill nodes.
type UserMobileSkillUpsertBulk struct {
	create *UserMobileSkillCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserMobileSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserMobileSkillUpsertBulk) UpdateNewValues() *UserMobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usermobileskill.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserMobileSkill.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserMobileSkillUpsertBulk) Ignore() *UserMobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserMobileSkillUpsertBulk) DoNothing() *UserMobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserMobileSkillCreateBulk.OnConflict
// documentation for more info.
func (u *UserMobileSkillUpsertBulk) Update(set func(*UserMobileSkillUpsert)) *UserMobileSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserMobileSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserMobileSkillUpsertBulk) SetUpdatedAt(v time.Time) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserMobileSkillUpsertBulk) UpdateUpdatedAt() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserMobileSkillUpsertBulk) SetUserID(v int64) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserMobileSkillUpsertBulk) AddUserID(v int64) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserMobileSkillUpsertBulk) UpdateUserID() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateUserID()
	})
}

// SetSkillID sets the "skill_id" field.
func (u *UserMobileSkillUpsertBulk) SetSkillID(v int64) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetSkillID(v)
	})
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *UserMobileSkillUpsertBulk) UpdateSkillID() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateSkillID()
	})
}

// SetInstalledVersion sets the "installed_version" field.
func (u *UserMobileSkillUpsertBulk) SetInstalledVersion(v int) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetInstalledVersion(v)
	})
}

// AddInstalledVersion adds v to the "installed_version" field.
func (u *UserMobileSkillUpsertBulk) AddInstalledVersion(v int) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.AddInstalledVersion(v)
	})
}

// UpdateInstalledVersion sets the "installed_version" field to the value that was provided on create.
func (u *UserMobileSkillUpsertBulk) UpdateInstalledVersion() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateInstalledVersion()
	})
}

// SetPinned sets the "pinned" field.
func (u *UserMobileSkillUpsertBulk) SetPinned(v bool) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *UserMobileSkillUpsertBulk) UpdatePinned() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdatePinned()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserMobileSkillUpsertBulk) SetLastUsedAt(v time.Time) *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserMobileSkillUpsertBulk) UpdateLastUsedAt() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserMobileSkillUpsertBulk) ClearLastUsedAt() *UserMobileSkillUpsertBulk {
	return u.Update(func(s *UserMobileSkillUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *UserMobileSkillUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserMobileSkillCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserMobileSkillCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserMobileSkillUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
