// Code generated by ent, DO NOT EDIT.

package mobileskillversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// SkillID applies equality check predicate on the "skill_id" field. It's identical to SkillIDEQ.
func SkillID(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldSkillID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldVersion, v))
}

// PromptID applies equality check predicate on the "prompt_id" field. It's identical to PromptIDEQ.
func PromptID(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldPromptID, v))
}

// PromptVersion applies equality check predicate on the "prompt_version" field. It's identical to PromptVersionEQ.
func PromptVersion(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldPromptVersion, v))
}

// SystemPromptOverride applies equality check predicate on the "system_prompt_override" field. It's identical to SystemPromptOverrideEQ.
func SystemPromptOverride(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldSystemPromptOverride, v))
}

// ConsumptionNoteZh applies equality check predicate on the "consumption_note_zh" field. It's identical to ConsumptionNoteZhEQ.
func ConsumptionNoteZh(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldConsumptionNoteZh, v))
}

// ChangelogZh applies equality check predicate on the "changelog_zh" field. It's identical to ChangelogZhEQ.
func ChangelogZh(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldChangelogZh, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// SkillIDEQ applies the EQ predicate on the "skill_id" field.
func SkillIDEQ(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldSkillID, v))
}

// SkillIDNEQ applies the NEQ predicate on the "skill_id" field.
func SkillIDNEQ(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldSkillID, v))
}

// SkillIDIn applies the In predicate on the "skill_id" field.
func SkillIDIn(vs ...int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldSkillID, vs...))
}

// SkillIDNotIn applies the NotIn predicate on the "skill_id" field.
func SkillIDNotIn(vs ...int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldSkillID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldVersion, v))
}

// PromptIDEQ applies the EQ predicate on the "prompt_id" field.
func PromptIDEQ(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldPromptID, v))
}

// PromptIDNEQ applies the NEQ predicate on the "prompt_id" field.
func PromptIDNEQ(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldPromptID, v))
}

// PromptIDIn applies the In predicate on the "prompt_id" field.
func PromptIDIn(vs ...int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldPromptID, vs...))
}

// PromptIDNotIn applies the NotIn predicate on the "prompt_id" field.
func PromptIDNotIn(vs ...int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldPromptID, vs...))
}

// PromptIDGT applies the GT predicate on the "prompt_id" field.
func PromptIDGT(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldPromptID, v))
}

// PromptIDGTE applies the GTE predicate on the "prompt_id" field.
func PromptIDGTE(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldPromptID, v))
}

// PromptIDLT applies the LT predicate on the "prompt_id" field.
func PromptIDLT(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldPromptID, v))
}

// PromptIDLTE applies the LTE predicate on the "prompt_id" field.
func PromptIDLTE(v int64) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldPromptID, v))
}

// PromptVersionEQ applies the EQ predicate on the "prompt_version" field.
func PromptVersionEQ(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldPromptVersion, v))
}

// PromptVersionNEQ applies the NEQ predicate on the "prompt_version" field.
func PromptVersionNEQ(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldPromptVersion, v))
}

// PromptVersionIn applies the In predicate on the "prompt_version" field.
func PromptVersionIn(vs ...int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldPromptVersion, vs...))
}

// PromptVersionNotIn applies the NotIn predicate on the "prompt_version" field.
func PromptVersionNotIn(vs ...int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldPromptVersion, vs...))
}

// PromptVersionGT applies the GT predicate on the "prompt_version" field.
func PromptVersionGT(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldPromptVersion, v))
}

// PromptVersionGTE applies the GTE predicate on the "prompt_version" field.
func PromptVersionGTE(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldPromptVersion, v))
}

// PromptVersionLT applies the LT predicate on the "prompt_version" field.
func PromptVersionLT(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldPromptVersion, v))
}

// PromptVersionLTE applies the LTE predicate on the "prompt_version" field.
func PromptVersionLTE(v int) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldPromptVersion, v))
}

// SystemPromptOverrideEQ applies the EQ predicate on the "system_prompt_override" field.
func SystemPromptOverrideEQ(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideNEQ applies the NEQ predicate on the "system_prompt_override" field.
func SystemPromptOverrideNEQ(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideIn applies the In predicate on the "system_prompt_override" field.
func SystemPromptOverrideIn(vs ...string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldSystemPromptOverride, vs...))
}

// SystemPromptOverrideNotIn applies the NotIn predicate on the "system_prompt_override" field.
func SystemPromptOverrideNotIn(vs ...string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldSystemPromptOverride, vs...))
}

// SystemPromptOverrideGT applies the GT predicate on the "system_prompt_override" field.
func SystemPromptOverrideGT(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideGTE applies the GTE predicate on the "system_prompt_override" field.
func SystemPromptOverrideGTE(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideLT applies the LT predicate on the "system_prompt_override" field.
func SystemPromptOverrideLT(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideLTE applies the LTE predicate on the "system_prompt_override" field.
func SystemPromptOverrideLTE(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideContains applies the Contains predicate on the "system_prompt_override" field.
func SystemPromptOverrideContains(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldContains(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideHasPrefix applies the HasPrefix predicate on the "system_prompt_override" field.
func SystemPromptOverrideHasPrefix(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldHasPrefix(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideHasSuffix applies the HasSuffix predicate on the "system_prompt_override" field.
func SystemPromptOverrideHasSuffix(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldHasSuffix(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideIsNil applies the IsNil predicate on the "system_prompt_override" field.
func SystemPromptOverrideIsNil() predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIsNull(FieldSystemPromptOverride))
}

// SystemPromptOverrideNotNil applies the NotNil predicate on the "system_prompt_override" field.
func SystemPromptOverrideNotNil() predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotNull(FieldSystemPromptOverride))
}

// SystemPromptOverrideEqualFold applies the EqualFold predicate on the "system_prompt_override" field.
func SystemPromptOverrideEqualFold(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEqualFold(FieldSystemPromptOverride, v))
}

// SystemPromptOverrideContainsFold applies the ContainsFold predicate on the "system_prompt_override" field.
func SystemPromptOverrideContainsFold(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldContainsFold(FieldSystemPromptOverride, v))
}

// ConsumptionNoteZhEQ applies the EQ predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhEQ(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhNEQ applies the NEQ predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhNEQ(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhIn applies the In predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhIn(vs ...string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldConsumptionNoteZh, vs...))
}

// ConsumptionNoteZhNotIn applies the NotIn predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhNotIn(vs ...string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldConsumptionNoteZh, vs...))
}

// ConsumptionNoteZhGT applies the GT predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhGT(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhGTE applies the GTE predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhGTE(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhLT applies the LT predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhLT(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhLTE applies the LTE predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhLTE(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhContains applies the Contains predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhContains(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldContains(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhHasPrefix applies the HasPrefix predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhHasPrefix(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldHasPrefix(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhHasSuffix applies the HasSuffix predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhHasSuffix(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldHasSuffix(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhEqualFold applies the EqualFold predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhEqualFold(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEqualFold(FieldConsumptionNoteZh, v))
}

// ConsumptionNoteZhContainsFold applies the ContainsFold predicate on the "consumption_note_zh" field.
func ConsumptionNoteZhContainsFold(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldContainsFold(FieldConsumptionNoteZh, v))
}

// ChangelogZhEQ applies the EQ predicate on the "changelog_zh" field.
func ChangelogZhEQ(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEQ(FieldChangelogZh, v))
}

// ChangelogZhNEQ applies the NEQ predicate on the "changelog_zh" field.
func ChangelogZhNEQ(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNEQ(FieldChangelogZh, v))
}

// ChangelogZhIn applies the In predicate on the "changelog_zh" field.
func ChangelogZhIn(vs ...string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldIn(FieldChangelogZh, vs...))
}

// ChangelogZhNotIn applies the NotIn predicate on the "changelog_zh" field.
func ChangelogZhNotIn(vs ...string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldNotIn(FieldChangelogZh, vs...))
}

// ChangelogZhGT applies the GT predicate on the "changelog_zh" field.
func ChangelogZhGT(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGT(FieldChangelogZh, v))
}

// ChangelogZhGTE applies the GTE predicate on the "changelog_zh" field.
func ChangelogZhGTE(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldGTE(FieldChangelogZh, v))
}

// ChangelogZhLT applies the LT predicate on the "changelog_zh" field.
func ChangelogZhLT(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLT(FieldChangelogZh, v))
}

// ChangelogZhLTE applies the LTE predicate on the "changelog_zh" field.
func ChangelogZhLTE(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldLTE(FieldChangelogZh, v))
}

// ChangelogZhContains applies the Contains predicate on the "changelog_zh" field.
func ChangelogZhContains(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldContains(FieldChangelogZh, v))
}

// ChangelogZhHasPrefix applies the HasPrefix predicate on the "changelog_zh" field.
func ChangelogZhHasPrefix(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldHasPrefix(FieldChangelogZh, v))
}

// ChangelogZhHasSuffix applies the HasSuffix predicate on the "changelog_zh" field.
func ChangelogZhHasSuffix(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldHasSuffix(FieldChangelogZh, v))
}

// ChangelogZhEqualFold applies the EqualFold predicate on the "changelog_zh" field.
func ChangelogZhEqualFold(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldEqualFold(FieldChangelogZh, v))
}

// ChangelogZhContainsFold applies the ContainsFold predicate on the "changelog_zh" field.
func ChangelogZhContainsFold(v string) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.FieldContainsFold(FieldChangelogZh, v))
}

// HasSkill applies the HasEdge predicate on the "skill" edge.
func HasSkill() predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkillWith applies the HasEdge predicate on the "skill" edge with a given conditions (other predicates).
func HasSkillWith(preds ...predicate.MobileSkill) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(func(s *sql.Selector) {
		step := newSkillStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MobileSkillVersion) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MobileSkillVersion) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MobileSkillVersion) predicate.MobileSkillVersion {
	return predicate.MobileSkillVersion(sql.NotPredicates(p))
}
