package service

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// The expected strings below are produced by the NodeBB plugin's own
// canonicalize()/sign() in plugins/nodebb-plugin-sub2api-sso/webhook-handlers.js.
// They are pinned here so a change on either side fails loudly instead of
// silently making every webhook return 401 bad_signature in production.
func TestForumSSOCanonicalizeMatchesPluginContract(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name     string
		payload  map[string]any
		expected string
	}{
		{
			name:     "empty payload still binds timestamp and nonce",
			payload:  map[string]any{},
			expected: "1700000000\nabc\n",
		},
		{
			name: "flat keys sort lexicographically",
			payload: map[string]any{
				"event": "balance.changed",
				"b":     "2",
				"a":     "1",
			},
			expected: "1700000000\nabc\na=1&b=2&event=balance.changed",
		},
		{
			name: "nested objects join with dot",
			payload: map[string]any{
				"event": "balance.changed",
				"data": map[string]any{
					"user_id": int64(42),
					"balance": "10.00",
				},
			},
			expected: "1700000000\nabc\ndata.balance=10.00&data.user_id=42&event=balance.changed",
		},
		{
			name: "arrays index with brackets",
			payload: map[string]any{
				"d": map[string]any{
					"ids": []any{int64(1), int64(2)},
					"n":   map[string]any{"k": "v"},
				},
				"e": "x",
			},
			expected: "1700000000\nabc\nd.ids[0]=1&d.ids[1]=2&d.n.k=v&e=x",
		},
		{
			name: "nil values are skipped entirely",
			payload: map[string]any{
				"a": "1",
				"b": nil,
				"c": "3",
			},
			expected: "1700000000\nabc\na=1&c=3",
		},
		{
			name: "booleans stringify like JS",
			payload: map[string]any{
				"ok":   true,
				"fail": false,
			},
			expected: "1700000000\nabc\nfail=false&ok=true",
		},
		{
			name: "money passed as string keeps its scale",
			payload: map[string]any{
				"amount": "10.00",
			},
			expected: "1700000000\nabc\namount=10.00",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := ForumSSOCanonicalize(tc.payload, "1700000000", "abc")
			require.Equal(t, tc.expected, got)
		})
	}
}

// Guards the money contract: a float64 10.00 stringifies to "10", which is
// exactly the mismatch that made raw-body signing unusable. Outbound payloads
// must therefore carry monetary values as strings.
func TestForumSSOFloatMoneyLosesScaleSoStringsAreRequired(t *testing.T) {
	t.Parallel()

	asFloat := ForumSSOCanonicalize(map[string]any{"amount": 10.00}, "1", "n")
	asString := ForumSSOCanonicalize(map[string]any{"amount": "10.00"}, "1", "n")

	require.Equal(t, "1\nn\namount=10", asFloat)
	require.Equal(t, "1\nn\namount=10.00", asString)
	require.NotEqual(t, asFloat, asString)
}

func TestForumSSOSignIsStableAndSecretDependent(t *testing.T) {
	t.Parallel()

	payload := map[string]any{
		"event": "vip.changed",
		"data": map[string]any{
			"user_id": int64(7),
			"tier":    int64(3),
			"label":   "V3",
		},
	}

	first := ForumSSOSign(payload, "1700000000", "nonce-1", "secret")
	second := ForumSSOSign(payload, "1700000000", "nonce-1", "secret")
	require.Equal(t, first, second, "signing must be deterministic")
	require.Len(t, first, 64, "hex sha256 is 64 chars")

	// Fixture generated by running the plugin's own crypto.createHmac(...) over
	// the same payload. If this assertion ever fails, the two implementations
	// have diverged and every webhook will be rejected as bad_signature.
	require.Equal(t,
		"6dbbfb65db0794e4979530a03cf32b65ae0bdbe3876d3a38968d96ac4930e479",
		first,
		"signature must match the NodeBB plugin implementation",
	)

	require.NotEqual(t, first, ForumSSOSign(payload, "1700000000", "nonce-1", "other-secret"))
	require.NotEqual(t, first, ForumSSOSign(payload, "1700000001", "nonce-1", "secret"))
	require.NotEqual(t, first, ForumSSOSign(payload, "1700000000", "nonce-2", "secret"))
}
