<template>
  <section class="space-y-5" aria-labelledby="membership-operations-title" :aria-busy="loading">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div><h2 id="membership-operations-title" class="text-lg font-semibold text-gray-900 dark:text-white">{{ t('admin.playOps.membership.title') }}</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ t('admin.playOps.membership.hint') }}</p></div>
      <button type="button" class="btn btn-secondary inline-flex items-center gap-2" :disabled="loading" @click="load"><Icon name="refresh" size="sm" />{{ t('admin.playOps.refresh') }}</button>
    </div>

    <div v-if="error" class="card border-red-200 p-4 text-sm text-red-700 dark:border-red-900 dark:text-red-300" role="alert"><p>{{ error }}</p><button type="button" class="btn btn-secondary mt-3" @click="load">{{ t('common.retry') }}</button></div>
    <template v-else>
      <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="stat in stats" :key="stat.label" class="card p-4"><p class="text-xs text-gray-500 dark:text-gray-400">{{ stat.label }}</p><p class="mt-2 text-xl font-semibold tabular-nums text-gray-900 dark:text-white">{{ loading ? '—' : stat.value }}</p></div></div>

      <section class="card overflow-hidden" aria-labelledby="vip-config-title">
        <div class="flex flex-col gap-3 border-b border-gray-100 px-5 py-4 dark:border-dark-700 sm:flex-row sm:items-center sm:justify-between"><div><h3 id="vip-config-title" class="font-semibold text-gray-900 dark:text-white">{{ t('admin.playOps.membership.rules') }}</h3><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ t('admin.playOps.membership.rulesHint') }}</p></div><button type="button" class="btn btn-secondary inline-flex items-center gap-2" @click="addTier"><Icon name="plus" size="sm" />{{ t('admin.playOps.membership.addTier') }}</button></div>
        <div class="overflow-x-auto"><table class="min-w-[900px] divide-y divide-gray-100 text-sm dark:divide-dark-700"><thead class="bg-gray-50 text-left text-xs text-gray-500 dark:bg-dark-800 dark:text-gray-400"><tr><th class="px-4 py-3">{{ t('admin.playOps.membership.tier') }}</th><th class="px-4 py-3">{{ t('admin.playOps.membership.tierName') }}</th><th class="px-4 py-3">{{ t('admin.playOps.membership.threshold') }}</th><th class="px-4 py-3">{{ t('admin.playOps.membership.bonus') }}</th><th class="px-4 py-3">{{ t('admin.playOps.membership.perks') }}</th><th class="w-14 px-4 py-3"></th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="(tier,index) in tierDraft" :key="`${tier.tier}-${index}`"><td class="px-4 py-3"><input v-model.number="tier.tier" type="number" min="0" class="input w-24" :disabled="tier.tier === 0" /></td><td class="px-4 py-3"><input v-model="tier.label" class="input min-w-32" maxlength="64" /></td><td class="px-4 py-3"><input v-model.number="tier.min_recharge" type="number" min="0" step="0.01" class="input min-w-32" :disabled="tier.tier === 0" /></td><td class="px-4 py-3"><input v-model.number="tier.recharge_bonus_pct" type="number" min="0" max="10" step="0.01" class="input min-w-28" /></td><td class="px-4 py-3"><input :value="(tier.perks || []).join(', ')" class="input min-w-64" :placeholder="t('admin.playOps.membership.perksPlaceholder')" @input="setTierPerks(tier, $event)" /></td><td class="px-4 py-3"><button v-if="tier.tier !== 0" type="button" class="btn-icon text-red-600" :title="t('admin.playOps.membership.removeTier')" @click="removeTier(index)"><Icon name="trash" size="sm" /></button></td></tr></tbody></table></div>
        <div class="space-y-4 border-t border-gray-100 p-5 dark:border-dark-700">
          <p class="text-xs text-gray-500 dark:text-gray-400">{{ t('admin.playOps.membership.auditHint') }}</p>
          <div v-if="vipPreview" class="grid gap-3 rounded border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100 sm:grid-cols-3"><div>{{ t('admin.playOps.membership.affected') }} <strong>{{ vipPreview.affected_users }}</strong></div><div>{{ t('admin.playOps.membership.previewUpgrades') }} <strong>{{ vipPreview.upgraded_users }}</strong></div><div>{{ t('admin.playOps.membership.previewDowngrades') }} <strong>{{ vipPreview.downgraded_users }}</strong></div></div>
          <label class="grid gap-1 text-sm"><span class="text-gray-600 dark:text-gray-300">{{ t('admin.playOps.membership.publishReason') }}</span><textarea v-model="publishReason" rows="2" maxlength="500" class="input" :placeholder="t('admin.playOps.membership.publishReasonPlaceholder')" /></label>
          <div class="flex flex-col gap-2 sm:flex-row sm:justify-end"><button type="button" class="btn btn-secondary" :disabled="configSaving" @click="previewConfig">{{ t('admin.playOps.membership.preview') }}</button><button type="button" class="btn btn-primary" :disabled="!canPublish" @click="publishConfig">{{ t('admin.playOps.membership.publish') }}</button></div>
        </div>
      </section>

      <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]">
        <section class="card overflow-hidden">
          <div class="flex flex-col gap-3 border-b border-gray-100 px-5 py-4 dark:border-dark-700 sm:flex-row"><input v-model="query" class="input sm:w-72" type="search" :placeholder="t('admin.playOps.membership.search')" @keyup.enter="loadUsers(1)" /><select v-model="memberFilter" class="input sm:w-40" @change="loadUsers(1)"><option value="">{{ t('admin.playOps.membership.allStates') }}</option><option value="member">{{ t('admin.playOps.membership.member') }}</option><option value="ordinary">{{ t('admin.playOps.membership.ordinary') }}</option></select></div>
          <div v-if="usersLoading" class="p-8 text-center text-sm text-gray-500">{{ t('admin.playOps.loading') }}</div><div v-else-if="!users.items.length" class="p-8 text-center text-sm text-gray-500">{{ t('admin.playOps.membership.noUsers') }}</div>
          <div v-else class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-100 text-sm dark:divide-dark-700"><thead class="bg-gray-50 text-left text-xs text-gray-500 dark:bg-dark-800 dark:text-gray-400"><tr><th class="px-4 py-3">{{ t('admin.playOps.membership.user') }}</th><th class="px-4 py-3">{{ t('admin.playOps.membership.tier') }}</th><th class="px-4 py-3 text-right">{{ t('admin.playOps.membership.netPaid') }}</th><th class="px-4 py-3">{{ t('admin.playOps.membership.lastPaid') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="user in users.items" :key="user.user_id" class="cursor-pointer hover:bg-gray-50 dark:hover:bg-dark-800" :class="{ 'bg-primary-50/70 dark:bg-primary-900/20': detail?.user.user_id === user.user_id }" @click="selectUser(user.user_id)"><td class="px-4 py-3"><div>{{ user.email_masked }}</div><div v-if="user.username" class="text-xs text-gray-500">{{ user.username }}</div></td><td class="px-4 py-3">{{ user.tier_label }}</td><td class="px-4 py-3 text-right tabular-nums">{{ user.net_paid_amount }}</td><td class="px-4 py-3 text-gray-500">{{ formatDate(user.last_paid_at) }}</td></tr></tbody></table></div>
          <div class="flex items-center justify-between border-t border-gray-100 px-4 py-3 text-sm dark:border-dark-700"><span class="text-gray-500">{{ t('admin.playOps.membership.totalUsers', { count: users.total }) }}</span><div class="flex gap-2"><button type="button" class="btn btn-secondary" :disabled="users.page <= 1 || usersLoading" @click="loadUsers(users.page - 1)">{{ t('admin.playOps.membership.previous') }}</button><button type="button" class="btn btn-secondary" :disabled="users.page * users.page_size >= users.total || usersLoading" @click="loadUsers(users.page + 1)">{{ t('admin.playOps.membership.next') }}</button></div></div>
        </section>

        <aside class="card p-5"><div v-if="detailLoading" class="py-8 text-center text-sm text-gray-500">{{ t('admin.playOps.loading') }}</div><div v-else-if="detail" class="space-y-5"><div><h3 class="font-semibold text-gray-900 dark:text-white">{{ detail.user.email_masked }}</h3><p class="mt-1 text-sm text-gray-500">{{ detail.user.tier_label }} · {{ detail.user.net_paid_amount }}</p></div><div><h4 class="mb-2 text-sm font-semibold">{{ t('admin.playOps.membership.orders') }}</h4><div v-if="!detail.contributions.length" class="text-sm text-gray-500">{{ t('admin.playOps.membership.noOrders') }}</div><div v-for="item in detail.contributions" :key="item.order_id" class="border-b border-gray-100 py-2 text-xs last:border-b-0 dark:border-dark-700"><div class="flex justify-between gap-3"><span>#{{ item.order_id }} · {{ item.order_type }}</span><strong>{{ item.net_amount }}</strong></div><div class="mt-1 text-gray-500">{{ formatDate(item.paid_at || item.updated_at) }} · {{ item.status }}</div></div></div><div><h4 class="mb-2 text-sm font-semibold">{{ t('admin.playOps.membership.tierHistory') }}</h4><div v-if="!detail.tier_history.length" class="text-sm text-gray-500">{{ t('admin.playOps.membership.noHistory') }}</div><div v-for="item in detail.tier_history" :key="`${item.created_at}-${item.from_tier}-${item.to_tier}`" class="border-b border-gray-100 py-2 text-xs last:border-b-0 dark:border-dark-700"><div>V{{ item.from_tier }} → V{{ item.to_tier }} · {{ t(`admin.playOps.membership.reasons.${item.reason}`, item.reason) }}</div><div class="mt-1 text-gray-500">{{ formatDate(item.created_at) }}</div></div></div></div><div v-else class="py-8 text-center text-sm text-gray-500">{{ t('admin.playOps.membership.selectUser') }}</div></aside>
      </div>
    </template>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import Icon from '@/components/icons/Icon.vue'
import adminPlayAPI, { type AdminMembershipDetail, type AdminMembershipList, type AdminMembershipOverview, type AdminVIPConfigImpact, type AdminVIPTier } from '@/api/admin/play'

const { t, locale } = useI18n()
const loading = ref(false); const usersLoading = ref(false); const detailLoading = ref(false); const configSaving = ref(false); const error = ref('')
const overview = ref<AdminMembershipOverview | null>(null); const users = ref<AdminMembershipList>({ items: [], total: 0, page: 1, page_size: 20 }); const detail = ref<AdminMembershipDetail | null>(null)
const query = ref(''); const memberFilter = ref(''); const tierDraft = ref<AdminVIPTier[]>([]); const vipVersion = ref(0); const vipPreview = ref<AdminVIPConfigImpact | null>(null); const publishReason = ref('')
const stats = computed(() => [{ label: t('admin.playOps.membership.totalMembers'), value: overview.value?.total_members.toLocaleString(locale.value) || '0' }, { label: t('admin.playOps.membership.netPaid'), value: overview.value?.net_paid_amount || '0' }, { label: t('admin.playOps.membership.upgrades'), value: overview.value?.recent_upgrades.toLocaleString(locale.value) || '0' }, { label: t('admin.playOps.membership.downgrades'), value: overview.value?.recent_downgrades.toLocaleString(locale.value) || '0' }])
const canPublish = computed(() => Boolean(vipPreview.value && publishReason.value.trim().length >= 10 && !configSaving.value))

async function loadUsers(page = 1) { usersLoading.value = true; try { users.value = await adminPlayAPI.listMembershipUsers({ q: query.value.trim() || undefined, member: memberFilter.value ? memberFilter.value === 'member' : undefined, page, page_size: users.value.page_size }) } catch { error.value = t('admin.playOps.membership.loadFailed') } finally { usersLoading.value = false } }
async function selectUser(id: number) { detailLoading.value = true; try { detail.value = await adminPlayAPI.getMembershipUser(id) } catch { error.value = t('admin.playOps.membership.loadFailed') } finally { detailLoading.value = false } }
async function load() { loading.value = true; error.value = ''; try { const [summary, config] = await Promise.all([adminPlayAPI.getMembershipOverview(), adminPlayAPI.getVIPConfig()]); overview.value = summary; tierDraft.value = config.tiers.map(tier => ({ ...tier, perks: [...(tier.perks || [])] })); vipVersion.value = config.version; vipPreview.value = null; await loadUsers(1) } catch { error.value = t('admin.playOps.membership.loadFailed') } finally { loading.value = false } }
function addTier() { const last = [...tierDraft.value].sort((a,b) => a.tier-b.tier).at(-1); tierDraft.value.push({ tier: (last?.tier || 0)+1, label: `V${(last?.tier || 0)+1}`, min_recharge: (last?.min_recharge || 0)+100, recharge_bonus_pct: last?.recharge_bonus_pct || 0, color_key: 'neutral', perks: [] }); vipPreview.value = null }
function removeTier(index: number) { tierDraft.value.splice(index,1); vipPreview.value = null }
function setTierPerks(tier: AdminVIPTier, event: Event) { tier.perks = (event.target as HTMLInputElement).value.split(/[,，]/).map(value => value.trim()).filter(Boolean); vipPreview.value = null }
async function previewConfig() { configSaving.value = true; try { vipPreview.value = await adminPlayAPI.previewVIPConfig(tierDraft.value); vipVersion.value = vipPreview.value.version } catch { error.value = t('admin.playOps.membership.configInvalid') } finally { configSaving.value = false } }
async function publishConfig() { if (!vipPreview.value) return; configSaving.value = true; try { const result = await adminPlayAPI.publishVIPConfig({ tiers: vipPreview.value.tiers, expected_version: vipVersion.value, reason: publishReason.value.trim() }); vipVersion.value = result.version; vipPreview.value = null; publishReason.value = ''; await load() } catch { error.value = t('admin.playOps.membership.publishFailed') } finally { configSaving.value = false } }
function formatDate(value?: string) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(locale.value, { timeZone: 'Asia/Shanghai' }) }
watch(tierDraft, () => { vipPreview.value = null }, { deep: true })
onMounted(load)
</script>
