<template>
  <section class="space-y-4" aria-labelledby="app-analytics-title" :aria-busy="loading">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="app-analytics-title" class="text-lg font-semibold text-gray-900 dark:text-white">{{ t('admin.playOps.appAnalytics.title') }}</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ t('admin.playOps.appAnalytics.hint') }}</p></div><button type="button" class="btn btn-secondary inline-flex items-center gap-2" :disabled="loading" @click="load"><Icon name="refresh" size="sm" />{{ t('admin.playOps.refresh') }}</button></div>
    <div class="flex flex-col gap-2 sm:flex-row"><select v-model="period" class="input sm:w-40" @change="load"><option value="7d">{{ t('admin.playOps.appAnalytics.last7') }}</option><option value="30d">{{ t('admin.playOps.appAnalytics.last30') }}</option><option value="90d">{{ t('admin.playOps.appAnalytics.last90') }}</option></select><input v-model="version" class="input sm:w-40" :placeholder="t('admin.playOps.appAnalytics.version')" @keyup.enter="load" /><input v-model="channel" class="input sm:w-40" :placeholder="t('admin.playOps.appAnalytics.channel')" @keyup.enter="load" /></div>
    <div v-if="error" class="card border-red-200 p-4 text-sm text-red-700 dark:border-red-900 dark:text-red-300" role="alert"><p>{{ error }}</p><button type="button" class="btn btn-secondary mt-3" @click="load">{{ t('common.retry') }}</button></div>
    <template v-else><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="stat in stats" :key="stat.label" class="card p-4"><p class="text-xs text-gray-500 dark:text-gray-400">{{ stat.label }}</p><p class="mt-2 text-xl font-semibold tabular-nums text-gray-900 dark:text-white">{{ loading ? '—' : stat.value }}</p></div></div><div class="grid gap-6 xl:grid-cols-2"><div class="card overflow-hidden"><div class="border-b border-gray-100 px-5 py-4 dark:border-dark-700"><h3 class="font-semibold text-gray-900 dark:text-white">{{ t('admin.playOps.appAnalytics.funnel') }}</h3></div><div v-if="!loading && !funnel.length" class="p-8 text-center text-sm text-gray-500">{{ t('admin.playOps.appAnalytics.empty') }}</div><table v-else class="min-w-full divide-y divide-gray-100 text-sm dark:divide-dark-700"><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="item in funnel" :key="item.event"><td class="px-4 py-3">{{ t(`admin.playOps.appAnalytics.events.${item.event}`, item.event) }}</td><td class="px-4 py-3 text-right tabular-nums">{{ item.count.toLocaleString(locale) }}</td><td class="px-4 py-3 text-right tabular-nums">{{ item.conversion_rate == null ? '—' : `${item.conversion_rate}%` }}</td></tr></tbody></table></div><div class="card overflow-hidden"><div class="border-b border-gray-100 px-5 py-4 dark:border-dark-700"><h3 class="font-semibold text-gray-900 dark:text-white">{{ t('admin.playOps.appAnalytics.versions') }}</h3></div><div v-if="!loading && !versions.length" class="p-8 text-center text-sm text-gray-500">{{ t('admin.playOps.appAnalytics.empty') }}</div><table v-else class="min-w-full divide-y divide-gray-100 text-sm dark:divide-dark-700"><thead class="bg-gray-50 text-left text-xs text-gray-500 dark:bg-dark-800 dark:text-gray-400"><tr><th class="px-4 py-3">{{ t('admin.playOps.appAnalytics.version') }}</th><th class="px-4 py-3">{{ t('admin.playOps.appAnalytics.platform') }}</th><th class="px-4 py-3 text-right">{{ t('admin.playOps.appAnalytics.active') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="item in versions" :key="`${item.platform}-${item.version}`"><td class="px-4 py-3">{{ item.version }}</td><td class="px-4 py-3">{{ item.platform }}</td><td class="px-4 py-3 text-right tabular-nums">{{ item.active.toLocaleString(locale) }}</td></tr></tbody></table></div></div></template>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import Icon from '@/components/icons/Icon.vue'
import adminPlayAPI, { type AdminAppAnalytics } from '@/api/admin/play'
const { t, locale } = useI18n(); const loading = ref(false); const error = ref(''); const analytics = ref<AdminAppAnalytics | null>(null); const period = ref('30d'); const version = ref(''); const channel = ref('')
const stats = computed(() => [{ label: t('admin.playOps.appAnalytics.scans'), value: analytics.value?.scans.toLocaleString(locale.value) || '0' }, { label: t('admin.playOps.appAnalytics.firstLaunches'), value: analytics.value?.first_launches.toLocaleString(locale.value) || '0' }, { label: t('admin.playOps.appAnalytics.registeredInstalls'), value: analytics.value?.registered_installs.toLocaleString(locale.value) || '0' }, { label: t('admin.playOps.appAnalytics.mau'), value: analytics.value?.mau.toLocaleString(locale.value) || '0' }])
const funnel = computed(() => analytics.value?.funnel ?? [])
const versions = computed(() => analytics.value?.versions ?? [])
async function load() { loading.value = true; error.value = ''; try { analytics.value = await adminPlayAPI.getAppAnalytics({ period: period.value, version: version.value || undefined, channel: channel.value || undefined }) } catch { error.value = t('admin.playOps.appAnalytics.loadFailed') } finally { loading.value = false } }
onMounted(load)
</script>
