// Code generated by ent, DO NOT EDIT.

package subscriptionentitlementhold

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscriptionentitlementhold type in the database.
	Label = "subscription_entitlement_hold"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEntitlementID holds the string denoting the entitlement_id field in the database.
	FieldEntitlementID = "entitlement_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldReservedUsd holds the string denoting the reserved_usd field in the database.
	FieldReservedUsd = "reserved_usd"
	// FieldCapturedUsd holds the string denoting the captured_usd field in the database.
	FieldCapturedUsd = "captured_usd"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldReleasedAt holds the string denoting the released_at field in the database.
	FieldReleasedAt = "released_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the subscriptionentitlementhold in the database.
	Table = "subscription_entitlement_holds"
)

// Columns holds all SQL columns for subscriptionentitlementhold fields.
var Columns = []string{
	FieldID,
	FieldEntitlementID,
	FieldRequestID,
	FieldRequestFingerprint,
	FieldReservedUsd,
	FieldCapturedUsd,
	FieldStatus,
	FieldExpiresAt,
	FieldCapturedAt,
	FieldReleasedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	RequestFingerprintValidator func(string) error
	// DefaultCapturedUsd holds the default value on creation for the "captured_usd" field.
	DefaultCapturedUsd float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionEntitlementHold queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEntitlementID orders the results by the entitlement_id field.
func ByEntitlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntitlementID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByReservedUsd orders the results by the reserved_usd field.
func ByReservedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedUsd, opts...).ToFunc()
}

// ByCapturedUsd orders the results by the captured_usd field.
func ByCapturedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedUsd, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByReleasedAt orders the results by the released_at field.
func ByReleasedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleasedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
