// Code generated by ent, DO NOT EDIT.

package mobileskill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldUpdatedAt, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldSlug, v))
}

// NameZh applies equality check predicate on the "name_zh" field. It's identical to NameZhEQ.
func NameZh(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldNameZh, v))
}

// DescriptionZh applies equality check predicate on the "description_zh" field. It's identical to DescriptionZhEQ.
func DescriptionZh(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldDescriptionZh, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCategory, v))
}

// IconURL applies equality check predicate on the "icon_url" field. It's identical to IconURLEQ.
func IconURL(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldIconURL, v))
}

// CoverURL applies equality check predicate on the "cover_url" field. It's identical to CoverURLEQ.
func CoverURL(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCoverURL, v))
}

// CurrentVersion applies equality check predicate on the "current_version" field. It's identical to CurrentVersionEQ.
func CurrentVersion(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCurrentVersion, v))
}

// PublishedVersion applies equality check predicate on the "published_version" field. It's identical to PublishedVersionEQ.
func PublishedVersion(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldPublishedVersion, v))
}

// Featured applies equality check predicate on the "featured" field. It's identical to FeaturedEQ.
func Featured(v bool) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldFeatured, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContainsFold(FieldSlug, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldStatus, vs...))
}

// NameZhEQ applies the EQ predicate on the "name_zh" field.
func NameZhEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldNameZh, v))
}

// NameZhNEQ applies the NEQ predicate on the "name_zh" field.
func NameZhNEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldNameZh, v))
}

// NameZhIn applies the In predicate on the "name_zh" field.
func NameZhIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldNameZh, vs...))
}

// NameZhNotIn applies the NotIn predicate on the "name_zh" field.
func NameZhNotIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldNameZh, vs...))
}

// NameZhGT applies the GT predicate on the "name_zh" field.
func NameZhGT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldNameZh, v))
}

// NameZhGTE applies the GTE predicate on the "name_zh" field.
func NameZhGTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldNameZh, v))
}

// NameZhLT applies the LT predicate on the "name_zh" field.
func NameZhLT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldNameZh, v))
}

// NameZhLTE applies the LTE predicate on the "name_zh" field.
func NameZhLTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldNameZh, v))
}

// NameZhContains applies the Contains predicate on the "name_zh" field.
func NameZhContains(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContains(FieldNameZh, v))
}

// NameZhHasPrefix applies the HasPrefix predicate on the "name_zh" field.
func NameZhHasPrefix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasPrefix(FieldNameZh, v))
}

// NameZhHasSuffix applies the HasSuffix predicate on the "name_zh" field.
func NameZhHasSuffix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasSuffix(FieldNameZh, v))
}

// NameZhEqualFold applies the EqualFold predicate on the "name_zh" field.
func NameZhEqualFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEqualFold(FieldNameZh, v))
}

// NameZhContainsFold applies the ContainsFold predicate on the "name_zh" field.
func NameZhContainsFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContainsFold(FieldNameZh, v))
}

// DescriptionZhEQ applies the EQ predicate on the "description_zh" field.
func DescriptionZhEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldDescriptionZh, v))
}

// DescriptionZhNEQ applies the NEQ predicate on the "description_zh" field.
func DescriptionZhNEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldDescriptionZh, v))
}

// DescriptionZhIn applies the In predicate on the "description_zh" field.
func DescriptionZhIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldDescriptionZh, vs...))
}

// DescriptionZhNotIn applies the NotIn predicate on the "description_zh" field.
func DescriptionZhNotIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldDescriptionZh, vs...))
}

// DescriptionZhGT applies the GT predicate on the "description_zh" field.
func DescriptionZhGT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldDescriptionZh, v))
}

// DescriptionZhGTE applies the GTE predicate on the "description_zh" field.
func DescriptionZhGTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldDescriptionZh, v))
}

// DescriptionZhLT applies the LT predicate on the "description_zh" field.
func DescriptionZhLT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldDescriptionZh, v))
}

// DescriptionZhLTE applies the LTE predicate on the "description_zh" field.
func DescriptionZhLTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldDescriptionZh, v))
}

// DescriptionZhContains applies the Contains predicate on the "description_zh" field.
func DescriptionZhContains(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContains(FieldDescriptionZh, v))
}

// DescriptionZhHasPrefix applies the HasPrefix predicate on the "description_zh" field.
func DescriptionZhHasPrefix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasPrefix(FieldDescriptionZh, v))
}

// DescriptionZhHasSuffix applies the HasSuffix predicate on the "description_zh" field.
func DescriptionZhHasSuffix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasSuffix(FieldDescriptionZh, v))
}

// DescriptionZhEqualFold applies the EqualFold predicate on the "description_zh" field.
func DescriptionZhEqualFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEqualFold(FieldDescriptionZh, v))
}

// DescriptionZhContainsFold applies the ContainsFold predicate on the "description_zh" field.
func DescriptionZhContainsFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContainsFold(FieldDescriptionZh, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContainsFold(FieldCategory, v))
}

// IconURLEQ applies the EQ predicate on the "icon_url" field.
func IconURLEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldIconURL, v))
}

// IconURLNEQ applies the NEQ predicate on the "icon_url" field.
func IconURLNEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldIconURL, v))
}

// IconURLIn applies the In predicate on the "icon_url" field.
func IconURLIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldIconURL, vs...))
}

// IconURLNotIn applies the NotIn predicate on the "icon_url" field.
func IconURLNotIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldIconURL, vs...))
}

// IconURLGT applies the GT predicate on the "icon_url" field.
func IconURLGT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldIconURL, v))
}

// IconURLGTE applies the GTE predicate on the "icon_url" field.
func IconURLGTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldIconURL, v))
}

// IconURLLT applies the LT predicate on the "icon_url" field.
func IconURLLT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldIconURL, v))
}

// IconURLLTE applies the LTE predicate on the "icon_url" field.
func IconURLLTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldIconURL, v))
}

// IconURLContains applies the Contains predicate on the "icon_url" field.
func IconURLContains(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContains(FieldIconURL, v))
}

// IconURLHasPrefix applies the HasPrefix predicate on the "icon_url" field.
func IconURLHasPrefix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasPrefix(FieldIconURL, v))
}

// IconURLHasSuffix applies the HasSuffix predicate on the "icon_url" field.
func IconURLHasSuffix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasSuffix(FieldIconURL, v))
}

// IconURLEqualFold applies the EqualFold predicate on the "icon_url" field.
func IconURLEqualFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEqualFold(FieldIconURL, v))
}

// IconURLContainsFold applies the ContainsFold predicate on the "icon_url" field.
func IconURLContainsFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContainsFold(FieldIconURL, v))
}

// CoverURLEQ applies the EQ predicate on the "cover_url" field.
func CoverURLEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCoverURL, v))
}

// CoverURLNEQ applies the NEQ predicate on the "cover_url" field.
func CoverURLNEQ(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldCoverURL, v))
}

// CoverURLIn applies the In predicate on the "cover_url" field.
func CoverURLIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldCoverURL, vs...))
}

// CoverURLNotIn applies the NotIn predicate on the "cover_url" field.
func CoverURLNotIn(vs ...string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldCoverURL, vs...))
}

// CoverURLGT applies the GT predicate on the "cover_url" field.
func CoverURLGT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldCoverURL, v))
}

// CoverURLGTE applies the GTE predicate on the "cover_url" field.
func CoverURLGTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldCoverURL, v))
}

// CoverURLLT applies the LT predicate on the "cover_url" field.
func CoverURLLT(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldCoverURL, v))
}

// CoverURLLTE applies the LTE predicate on the "cover_url" field.
func CoverURLLTE(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldCoverURL, v))
}

// CoverURLContains applies the Contains predicate on the "cover_url" field.
func CoverURLContains(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContains(FieldCoverURL, v))
}

// CoverURLHasPrefix applies the HasPrefix predicate on the "cover_url" field.
func CoverURLHasPrefix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasPrefix(FieldCoverURL, v))
}

// CoverURLHasSuffix applies the HasSuffix predicate on the "cover_url" field.
func CoverURLHasSuffix(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldHasSuffix(FieldCoverURL, v))
}

// CoverURLEqualFold applies the EqualFold predicate on the "cover_url" field.
func CoverURLEqualFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEqualFold(FieldCoverURL, v))
}

// CoverURLContainsFold applies the ContainsFold predicate on the "cover_url" field.
func CoverURLContainsFold(v string) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldContainsFold(FieldCoverURL, v))
}

// CurrentVersionEQ applies the EQ predicate on the "current_version" field.
func CurrentVersionEQ(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldCurrentVersion, v))
}

// CurrentVersionNEQ applies the NEQ predicate on the "current_version" field.
func CurrentVersionNEQ(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldCurrentVersion, v))
}

// CurrentVersionIn applies the In predicate on the "current_version" field.
func CurrentVersionIn(vs ...int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldCurrentVersion, vs...))
}

// CurrentVersionNotIn applies the NotIn predicate on the "current_version" field.
func CurrentVersionNotIn(vs ...int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldCurrentVersion, vs...))
}

// CurrentVersionGT applies the GT predicate on the "current_version" field.
func CurrentVersionGT(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldCurrentVersion, v))
}

// CurrentVersionGTE applies the GTE predicate on the "current_version" field.
func CurrentVersionGTE(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldCurrentVersion, v))
}

// CurrentVersionLT applies the LT predicate on the "current_version" field.
func CurrentVersionLT(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldCurrentVersion, v))
}

// CurrentVersionLTE applies the LTE predicate on the "current_version" field.
func CurrentVersionLTE(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldCurrentVersion, v))
}

// PublishedVersionEQ applies the EQ predicate on the "published_version" field.
func PublishedVersionEQ(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldPublishedVersion, v))
}

// PublishedVersionNEQ applies the NEQ predicate on the "published_version" field.
func PublishedVersionNEQ(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldPublishedVersion, v))
}

// PublishedVersionIn applies the In predicate on the "published_version" field.
func PublishedVersionIn(vs ...int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldPublishedVersion, vs...))
}

// PublishedVersionNotIn applies the NotIn predicate on the "published_version" field.
func PublishedVersionNotIn(vs ...int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldPublishedVersion, vs...))
}

// PublishedVersionGT applies the GT predicate on the "published_version" field.
func PublishedVersionGT(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldPublishedVersion, v))
}

// PublishedVersionGTE applies the GTE predicate on the "published_version" field.
func PublishedVersionGTE(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldPublishedVersion, v))
}

// PublishedVersionLT applies the LT predicate on the "published_version" field.
func PublishedVersionLT(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldPublishedVersion, v))
}

// PublishedVersionLTE applies the LTE predicate on the "published_version" field.
func PublishedVersionLTE(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldPublishedVersion, v))
}

// PublishedVersionIsNil applies the IsNil predicate on the "published_version" field.
func PublishedVersionIsNil() predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIsNull(FieldPublishedVersion))
}

// PublishedVersionNotNil applies the NotNil predicate on the "published_version" field.
func PublishedVersionNotNil() predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotNull(FieldPublishedVersion))
}

// FeaturedEQ applies the EQ predicate on the "featured" field.
func FeaturedEQ(v bool) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldFeatured, v))
}

// FeaturedNEQ applies the NEQ predicate on the "featured" field.
func FeaturedNEQ(v bool) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldFeatured, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.MobileSkill {
	return predicate.MobileSkill(sql.FieldLTE(FieldSortOrder, v))
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.MobileSkill {
	return predicate.MobileSkill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.MobileSkillVersion) predicate.MobileSkill {
	return predicate.MobileSkill(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserInstalls applies the HasEdge predicate on the "user_installs" edge.
func HasUserInstalls() predicate.MobileSkill {
	return predicate.MobileSkill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserInstallsTable, UserInstallsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserInstallsWith applies the HasEdge predicate on the "user_installs" edge with a given conditions (other predicates).
func HasUserInstallsWith(preds ...predicate.UserMobileSkill) predicate.MobileSkill {
	return predicate.MobileSkill(func(s *sql.Selector) {
		step := newUserInstallsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MobileSkill) predicate.MobileSkill {
	return predicate.MobileSkill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MobileSkill) predicate.MobileSkill {
	return predicate.MobileSkill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MobileSkill) predicate.MobileSkill {
	return predicate.MobileSkill(sql.NotPredicates(p))
}
