//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
	seoTitleSuffix       = "AI API Gateway 与中文提示词库"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path
		if isLegacyModelsPageNavigation(c.Request) {
			setModelsCompatibilityVary(c)
			c.Redirect(http.StatusPermanentRedirect, legacyModelsCatalogLocation(c.Request))
			c.Abort()
			return
		}

		// Skip API routes
		if shouldBypassEmbeddedFrontendRequest(c.Request) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" {
			s.serveIndexHTML(c)
			return
		}
		if s.tryServeOverride(c, cleanPath) {
			return
		}
		if !s.fileExists(cleanPath) {
			if isEmbeddedAssetRequest(cleanPath) {
				serveMissingEmbeddedAsset(c)
				return
			}
			s.serveIndexHTML(c)
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	path := c.Request.URL.Path
	setRouteSEORobotsHeader(c, path)
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		etag := routeSEOETag(cached.ETag, path)
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == etag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)
		content = injectRouteSEO(content, path)
		content = localizeEnglishHTMLShell(content, path)

		c.Header("ETag", etag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		content := injectRouteSEO(s.baseHTML, path)
		content = localizeEnglishHTMLShell(content, path)
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		content := injectRouteSEO(s.baseHTML, path)
		content = localizeEnglishHTMLShell(content, path)
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)
	content = injectRouteSEO(content, path)
	content = localizeEnglishHTMLShell(content, path)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", routeSEOETag(cached.ETag, path))
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteTitle(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)

	return result
}

func localizeEnglishHTMLShell(html []byte, path string) []byte {
	if !isEnglishRoutePath(path) {
		return html
	}
	// Some English routes, such as /en/status, are deliberately noindex and
	// therefore do not belong to the public SEO map. Language selection is a
	// route concern rather than an indexing concern: direct visits must not
	// receive a Chinese static shell before the SPA hydrates.
	return localizeEnglishInjectedAppConfig(setHTMLLang(html, "en"))
}

func isEnglishRoutePath(path string) bool {
	normalized := normalizePublicRouteSEOPath(path)
	return normalized == "/en" || strings.HasPrefix(normalized, "/en/")
}

func localizeEnglishInjectedAppConfig(html []byte) []byte {
	const prefix = `window.__APP_CONFIG__=`
	start := bytes.Index(html, []byte(prefix))
	if start == -1 {
		return html
	}
	jsonStart := start + len(prefix)
	endOffset := bytes.Index(html[jsonStart:], []byte(`;</script>`))
	if endOffset == -1 {
		return html
	}
	jsonEnd := jsonStart + endOffset

	var cfg map[string]any
	if err := json.Unmarshal(html[jsonStart:jsonEnd], &cfg); err != nil {
		return html
	}
	sanitizeEnglishAppConfig(cfg)
	localized, err := json.Marshal(cfg)
	if err != nil {
		return html
	}

	var buf bytes.Buffer
	buf.Write(html[:jsonStart])
	buf.Write(localized)
	buf.Write(html[jsonEnd:])
	return buf.Bytes()
}

func sanitizeEnglishAppConfig(cfg map[string]any) {
	cfg["site_name"] = "Jisudeng"
	cfg["site_subtitle"] = "One OpenAI-compatible API for AI models"
	cfg["contact_info"] = "WeChat: tqytwemx"
	cfg["login_agreement_documents"] = []any{}

	if support, ok := cfg["support_contact"].(map[string]any); ok {
		support["title"] = "Contact support"
		support["subtitle"] = "Get help with login, billing, API keys, model access, and image generation."
		if contacts, ok := support["contacts"].([]any); ok {
			for _, raw := range contacts {
				contact, ok := raw.(map[string]any)
				if !ok {
					continue
				}
				localizeEnglishSupportContact(contact)
			}
		}
	}

	if onboarding, ok := cfg["api_onboarding"].(map[string]any); ok {
		onboarding["title"] = "Start using the Jisudeng API"
		onboarding["subtitle"] = "Create an API key, choose an available group, and connect your code, client, or tools."
		if items, ok := onboarding["items"].([]any); ok {
			for index, raw := range items {
				item, ok := raw.(map[string]any)
				if !ok {
					continue
				}
				localizeEnglishAPIOnboardingItem(item, index)
			}
		}
	}

	if items, ok := cfg["custom_menu_items"].([]any); ok {
		for _, raw := range items {
			item, ok := raw.(map[string]any)
			if !ok {
				continue
			}
			if url, _ := item["url"].(string); isCanonicalDocsMenuURL(url) {
				item["label"] = "Docs"
			} else if label, _ := item["label"].(string); containsCJK(label) {
				item["label"] = "Menu"
			}
		}
	}

	stripCJKStrings(cfg)
}

func isCanonicalDocsMenuURL(rawURL string) bool {
	target, err := url.Parse(strings.TrimSpace(rawURL))
	if err != nil || target == nil || target.User != nil {
		return false
	}
	return target.Scheme == "https" &&
		target.Hostname() == "www.jisudeng.com" &&
		(target.Port() == "" || target.Port() == "443") &&
		(target.Path == "/docs" || target.Path == "/en/docs")
}

func localizeEnglishSupportContact(contact map[string]any) {
	contactType, _ := contact["type"].(string)
	switch strings.ToLower(contactType) {
	case "wechat":
		contact["label"] = "WeChat support"
		contact["description"] = "Add WeChat for support"
	case "qq":
		contact["label"] = "QQ support"
		contact["description"] = "Copy the QQ number for support"
	case "telegram":
		contact["label"] = "Telegram support"
		contact["description"] = "Contact us on Telegram"
	case "email":
		contact["label"] = "Email support"
		contact["description"] = "Email us for support"
	case "docs":
		contact["label"] = "Docs"
		contact["description"] = "Read the documentation"
	default:
		contact["label"] = "Support"
		contact["description"] = "Contact support"
	}
}

func localizeEnglishAPIOnboardingItem(item map[string]any, index int) {
	switch index {
	case 0:
		item["title"] = "Create a stable API key"
		item["description"] = "Create an API key and select the recommended group. Copy it into Cherry Studio, NextChat, OpenCode, Cursor, or your own SDK client."
		item["badge"] = "Start here"
	case 1:
		item["title"] = "Add balance"
		item["description"] = "Add balance for usage-based API calls when you only need quick tests or light usage."
		item["badge"] = "Usage-based"
	default:
		item["title"] = "Subscribe to a recommended plan"
		item["description"] = "Subscribe for steadier access and group permissions when you plan to use the API long term."
		item["badge"] = "Recommended"
	}
}

func stripCJKStrings(value any) {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			if text, ok := child.(string); ok && containsCJK(text) {
				typed[key] = ""
				continue
			}
			stripCJKStrings(child)
		}
	case []any:
		for index, child := range typed {
			if text, ok := child.(string); ok && containsCJK(text) {
				typed[index] = ""
				continue
			}
			stripCJKStrings(child)
		}
	}
}

func containsCJK(value string) bool {
	for _, r := range value {
		if (r >= 0x3400 && r <= 0x9fff) || (r >= 0xf900 && r <= 0xfaff) {
			return true
		}
	}
	return false
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// injectSiteTitle replaces the static <title> in HTML with the configured site title.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}
	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(buildSiteTitle(siteName)) + "</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func buildSiteTitle(siteName string) string {
	return strings.TrimSpace(siteName) + " - " + seoTitleSuffix
}

type routeSEOAlternate struct {
	Hreflang string
	Path     string
}

type routeSEO struct {
	Title              string
	Description        string
	TwitterTitle       string
	TwitterDescription string
	Keywords           string
	CanonicalPath      string
	Lang               string
	OGLocale           string
	OGType             string
	SiteName           string
	StructuredType     string
	Alternates         []routeSEOAlternate
}

type publicCatalogFallbackEntry struct {
	Path        string
	Name        string
	Description string
}

const routeSEOOrigin = "https://www.jisudeng.com"

const (
	routeSEOAuthor          = "Jisudeng"
	routeSEOImage           = "https://www.jisudeng.com/logo.png"
	routeSEOImageAlt        = "Jisudeng logo"
	routeSEOFormatDetection = "telephone=no,email=no,address=no"
	routeSEOTwitterCard     = "summary"
	routeSEOTwitterHandle   = "@jisudeng"
)

var publicRouteSEO = map[string]routeSEO{
	"/": {
		Title:              "极速蹬 - OpenAI兼容 AI API 网关与多模型服务平台",
		Description:        "极速蹬为开发者、团队和 AI 工具用户提供 OpenAI 兼容 API 网关，统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，支持公开价格、文档、图像生成、API Key 管理与按量计费。",
		TwitterTitle:       "极速蹬 OpenAI兼容 API 网关 - DeepSeek、Qwen、Kimi、GLM 多模型统一接入",
		TwitterDescription: "极速蹬统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，提供 OpenAI 兼容 API、公开模型价格、图像生成、API Key 管理、文档和按量计费服务，适合把现有 OpenAI SDK、AI 工具、自动化脚本和业务应用迁移到统一入口，并持续比较模型能力、调用权限与成本。",
		Keywords:           "极速蹬, AI API Gateway, OpenAI 兼容 API, AI 模型接口, DeepSeek API, Qwen API, Kimi API, GLM API, Claude API, Gemini API, 图像生成 API, API Key, 模型价格",
		CanonicalPath:      "/",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "WebSite",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "x-default", Path: "/"},
		},
	},
	"/home": {
		Title:              "极速蹬 - OpenAI兼容 AI API 网关与多模型服务平台",
		Description:        "极速蹬为开发者、团队和 AI 工具用户提供 OpenAI 兼容 API 网关，统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，支持公开价格、文档、图像生成、API Key 管理与按量计费。",
		TwitterTitle:       "极速蹬 OpenAI兼容 API 网关 - DeepSeek、Qwen、Kimi、GLM 多模型统一接入",
		TwitterDescription: "极速蹬统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，提供 OpenAI 兼容 API、公开模型价格、图像生成、API Key 管理、文档和按量计费服务，适合把现有 OpenAI SDK、AI 工具、自动化脚本和业务应用迁移到统一入口，并持续比较模型能力、调用权限与成本。",
		Keywords:           "极速蹬, AI API Gateway, OpenAI 兼容 API, AI 模型接口, DeepSeek API, Qwen API, Kimi API, GLM API, Claude API, Gemini API, 图像生成 API, API Key, 模型价格",
		CanonicalPath:      "/",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "WebSite",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "x-default", Path: "/"},
		},
	},
	"/catalog": {
		Title:              "极速蹬模型价格与 API 目录 - 多模型公开计费与调用指南",
		Description:        "查看极速蹬公开模型目录、模型平台、用途分类与 USD / 1M tokens 计费参考，覆盖 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，登录后可查看分组有效价格与调用权限，帮助开发者快速评估成本。",
		TwitterTitle:       "极速蹬模型价格与 API 目录 - DeepSeek、Qwen、Kimi、GLM、Claude 多模型公开计费",
		TwitterDescription: "查看极速蹬公开模型目录、模型平台、用途分类、USD / 1M tokens 计费参考和分组有效价格，覆盖 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等多模型 API 调用，帮助开发者快速评估成本、调用权限、模型能力与接入路径，并在登录后核对账号实际可用价格表。",
		Keywords:           "极速蹬模型价格, AI 模型目录, API 计费, DeepSeek API 价格, Qwen API 价格, Kimi API 价格, GLM API 价格, Claude API, Gemini API, OpenAI 兼容接口",
		CanonicalPath:      "/catalog",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/catalog"},
			{Hreflang: "en", Path: "/en/catalog"},
			{Hreflang: "x-default", Path: "/catalog"},
		},
	},
	"/catalog/deepseek": {
		Title:              "DeepSeek API 价格与模型接入 - 极速蹬多模型目录",
		Description:        "查看极速蹬 DeepSeek 模型目录、公开 API 价格、本站基础售价和 USD / 1M tokens 计费参考，支持通过 OpenAI 兼容 API、统一 Key、接入文档、图像能力说明和账单入口快速评估模型能力、调用权限、接入路径与上线成本。",
		TwitterTitle:       "DeepSeek API 价格与模型接入 - 极速蹬 OpenAI 兼容 API、公开计费、文档、调用与成本指南",
		TwitterDescription: "查看极速蹬 DeepSeek 模型目录、公开 API 价格、本站基础售价、USD / 1M tokens 计费参考、OpenAI 兼容接入方式、API Key 设置、文档入口、图像能力说明、分组实付价提示和账单规则，帮助开发者在登录前评估模型能力、调用权限、接入路径、测试步骤、生产迁移、日常调用、成本监控和上线成本。",
		Keywords:           "DeepSeek API 价格, DeepSeek 模型价格, DeepSeek 接口, OpenAI 兼容 DeepSeek, 极速蹬模型目录, API 计费, 模型接入",
		CanonicalPath:      "/catalog/deepseek",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/catalog/deepseek"},
			{Hreflang: "en", Path: "/en/catalog/deepseek"},
			{Hreflang: "x-default", Path: "/catalog/deepseek"},
		},
	},
	"/catalog/qwen": {
		Title:              "Qwen API 价格与模型接入 - 极速蹬多模型公开计费目录",
		Description:        "查看极速蹬 Qwen 模型目录、公开 API 价格、本站基础售价和 USD / 1M tokens 计费参考，支持通过 OpenAI 兼容 API、统一 Key、接入文档、图像能力说明和账单入口快速评估模型能力、调用权限、接入路径与上线成本。",
		TwitterTitle:       "Qwen API 价格与模型接入 - 极速蹬 OpenAI 兼容 API、公开计费、文档、调用与成本指南",
		TwitterDescription: "查看极速蹬 Qwen 模型目录、公开 API 价格、本站基础售价、USD / 1M tokens 计费参考、OpenAI 兼容接入方式、API Key 设置、文档入口、图像能力说明、分组实付价提示和账单规则，帮助开发者在登录前评估模型能力、调用权限、接入路径、测试步骤、生产迁移、日常调用、成本监控和上线成本。",
		Keywords:           "Qwen API 价格, Qwen 模型价格, Qwen 接口, OpenAI 兼容 Qwen, 极速蹬模型目录, API 计费, 模型接入",
		CanonicalPath:      "/catalog/qwen",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/catalog/qwen"},
			{Hreflang: "en", Path: "/en/catalog/qwen"},
			{Hreflang: "x-default", Path: "/catalog/qwen"},
		},
	},
	"/catalog/kimi": {
		Title:              "Kimi API 价格与模型接入 - 极速蹬多模型公开计费目录",
		Description:        "查看极速蹬 Kimi 模型目录、公开 API 价格、本站基础售价和 USD / 1M tokens 计费参考，支持通过 OpenAI 兼容 API、统一 Key、接入文档、图像能力说明和账单入口快速评估模型能力、调用权限、接入路径与上线成本。",
		TwitterTitle:       "Kimi API 价格与模型接入 - 极速蹬 OpenAI 兼容 API、公开计费、文档、调用与成本指南",
		TwitterDescription: "查看极速蹬 Kimi 模型目录、公开 API 价格、本站基础售价、USD / 1M tokens 计费参考、OpenAI 兼容接入方式、API Key 设置、文档入口、图像能力说明、分组实付价提示和账单规则，帮助开发者在登录前评估模型能力、调用权限、接入路径、测试步骤、生产迁移、日常调用、成本监控和上线成本。",
		Keywords:           "Kimi API 价格, Kimi 模型价格, Kimi 接口, OpenAI 兼容 Kimi, 极速蹬模型目录, API 计费, 模型接入",
		CanonicalPath:      "/catalog/kimi",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/catalog/kimi"},
			{Hreflang: "en", Path: "/en/catalog/kimi"},
			{Hreflang: "x-default", Path: "/catalog/kimi"},
		},
	},
	"/catalog/glm": {
		Title:              "GLM API 价格与模型接入 - 极速蹬多模型公开计费目录",
		Description:        "查看极速蹬 GLM 模型目录、公开 API 价格、本站基础售价和 USD / 1M tokens 计费参考，支持通过 OpenAI 兼容 API、统一 Key、接入文档、图像能力说明和账单入口快速评估模型能力、调用权限、接入路径与上线成本。",
		TwitterTitle:       "GLM API 价格与模型接入 - 极速蹬 OpenAI 兼容 API、公开计费、文档、调用与成本指南",
		TwitterDescription: "查看极速蹬 GLM 模型目录、公开 API 价格、本站基础售价、USD / 1M tokens 计费参考、OpenAI 兼容接入方式、API Key 设置、文档入口、图像能力说明、分组实付价提示和账单规则，帮助开发者在登录前评估模型能力、调用权限、接入路径、测试步骤、生产迁移、日常调用、成本监控和上线成本。",
		Keywords:           "GLM API 价格, GLM 模型价格, GLM 接口, OpenAI 兼容 GLM, 极速蹬模型目录, API 计费, 模型接入",
		CanonicalPath:      "/catalog/glm",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/catalog/glm"},
			{Hreflang: "en", Path: "/en/catalog/glm"},
			{Hreflang: "x-default", Path: "/catalog/glm"},
		},
	},
	"/docs": {
		Title:              "极速蹬 API 文档 - OpenAI兼容接口、模型调用与计费指南",
		Description:        "阅读极速蹬 API Key、OpenAI 兼容接口、模型选择、图片生成、异步任务、Batch Image、工具接入和计费说明，快速完成从注册到生产调用的配置。文档覆盖常见 SDK、命令行工具、环境安装与排障，适合开发者、团队和 AI 工具用户查阅。",
		TwitterTitle:       "极速蹬 API 文档 - OpenAI兼容接口、模型调用、图像生成、Batch Image 与计费指南",
		TwitterDescription: "阅读极速蹬 API 文档，完成 API Key、OpenAI 兼容接口、模型调用、图片生成、异步任务、Batch Image、工具接入、计费说明、SDK 配置和生产排障，帮助团队从注册、创建 Key、切换 base URL 到上线调用都能快速查到步骤、示例、权限说明、排障路径、上线检查和常见问题答案。",
		Keywords:           "极速蹬文档, API 接入指南, OpenAI 兼容 SDK, API Key 设置, 图片生成 API, Batch Image, 异步图片任务, Claude Code, Codex CLI, Gemini CLI",
		CanonicalPath:      "/docs",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "article",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/docs"},
			{Hreflang: "en", Path: "/en/docs"},
			{Hreflang: "x-default", Path: "/docs"},
		},
	},
	"/download/android": {
		Title:              "JisudengChat Android 下载 - 极速蹬 AI 客户端与移动模型调用入口",
		Description:        "下载 JisudengChat Android APK，使用极速蹬账号登录并同步余额、分组、API Key 和可用模型，在手机上查看账户状态、接入文档、模型调用入口和更新信息。页面提供版本号、安装包校验、下载说明与故障提示，适合已注册用户快速安装并开始移动端使用。",
		TwitterTitle:       "JisudengChat Android 下载 - 极速蹬 AI 客户端、API Key 与模型调用入口",
		TwitterDescription: "下载 JisudengChat Android APK，使用极速蹬账号登录并同步余额、分组、API Key、可用模型、接入文档、账户状态和更新信息。页面提供版本号、安装包校验、下载说明、更新提示和移动端入口，帮助已注册用户在手机上快速进入 AI 模型调用、账户查看、文档查询、移动测试与日常使用工作流。",
		Keywords:           "JisudengChat Android, 极速蹬 APP, Android APK 下载, AI 客户端, API Key, 模型调用, 移动端 AI 工具",
		CanonicalPath:      "/download/android",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/download/android"},
			{Hreflang: "x-default", Path: "/download/android"},
		},
	},
	"/about": {
		Title:              "关于极速蹬 - OpenAI兼容 API 网关、模型目录与提示词库",
		Description:        "了解极速蹬如何为开发者、团队和 AI 工具用户提供 OpenAI 兼容 API 网关、模型目录、公开价格、接入文档、图像生成、API Key 管理和提示词库，统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，帮助快速评估能力、成本和上线路径。",
		TwitterTitle:       "关于极速蹬 - OpenAI兼容 API 网关、模型价格、图像生成、API 文档与提示词库服务入口指南",
		TwitterDescription: "了解极速蹬如何统一 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型入口，提供 OpenAI 兼容 API、公开价格、API Key 管理、接入文档、图像生成和提示词库，帮助开发者、团队和 AI 工具用户更快完成模型选择、成本评估、测试接入、生产迁移与日常调用。",
		Keywords:           "关于极速蹬, AI API 网关, OpenAI 兼容 API, 多模型服务, 模型价格, API 文档, 图像生成, 提示词库, DeepSeek API, Qwen API, Kimi API, GLM API",
		CanonicalPath:      "/about",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "AboutPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/about"},
			{Hreflang: "en", Path: "/en/about"},
			{Hreflang: "x-default", Path: "/about"},
		},
	},
	"/contact": {
		Title:              "联系极速蹬客服 - API、模型调用、充值、账号与接入支持入口",
		Description:        "联系极速蹬客服获取登录注册、API Key、模型调用、充值支付、余额、分组权限、文档接入、图像生成、账号安全和故障排查支持。我们会帮助开发者和团队确认 OpenAI 兼容 API 接入路径、模型可用性、价格说明、调用示例、SDK 配置和上线问题。",
		TwitterTitle:       "联系极速蹬客服 - API Key、模型调用、充值、账号、图像生成、API 文档与开发者接入支持入口",
		TwitterDescription: "通过极速蹬客服入口获取登录注册、API Key、模型调用、充值支付、余额、分组权限、文档接入、图像生成、账号安全和故障排查支持。我们会围绕 OpenAI 兼容 API、DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型的可用性、价格说明、接入配置和上线问题提供帮助。",
		Keywords:           "联系极速蹬, 极速蹬客服, API Key 支持, 模型调用支持, 充值支付支持, OpenAI 兼容 API 接入, 图像生成支持, 开发者支持",
		CanonicalPath:      "/contact",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "ContactPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/contact"},
			{Hreflang: "en", Path: "/en/contact"},
			{Hreflang: "x-default", Path: "/contact"},
		},
	},
	"/en": {
		Title:              "Jisudeng: One OpenAI-Compatible API for Frontier AI Models",
		Description:        "Access DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through one OpenAI-compatible API with unified keys, public pricing, image APIs, billing, docs.",
		TwitterDescription: "Jisudeng unifies DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more behind one OpenAI-compatible API, with public pricing, API docs, image generation, usage controls, and billing.",
		Keywords:           "Jisudeng, OpenAI-compatible API, AI API gateway, DeepSeek API, Qwen API, Kimi API, GLM API, Claude API, Gemini API, model pricing, image generation API, API key",
		CanonicalPath:      "/en/",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "WebSite",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "x-default", Path: "/"},
		},
	},
	"/en/catalog": {
		Title:              "DeepSeek, Qwen, Kimi, GLM, Claude API Pricing | Jisudeng",
		Description:        "Compare model access and usage-based API rates for DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through Jisudeng.",
		TwitterTitle:       "DeepSeek, Qwen, Kimi, GLM, GPT, Claude API Pricing | Jisudeng",
		TwitterDescription: "Compare model access, public API rates, and usage-based pricing for DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through Jisudeng, with docs and API key setup guidance.",
		Keywords:           "AI model API pricing, DeepSeek API pricing, Qwen API pricing, Kimi API pricing, GLM API pricing, Claude API, Gemini API, OpenAI-compatible models, usage-based billing",
		CanonicalPath:      "/en/catalog",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/catalog"},
			{Hreflang: "zh-CN", Path: "/catalog"},
			{Hreflang: "x-default", Path: "/catalog"},
		},
	},
	"/en/catalog/deepseek": {
		Title:              "DeepSeek API Pricing and Access | Jisudeng",
		Description:        "Compare DeepSeek model access, public API rates, and usage-based pricing through Jisudeng. Use an OpenAI-compatible base URL, unified keys, docs, and billing.",
		TwitterTitle:       "DeepSeek API Pricing, Models, and OpenAI-Compatible Access",
		TwitterDescription: "Compare DeepSeek model access, public API rates, usage-based pricing, OpenAI-compatible setup, API key guidance, docs, image API notes, and billing through Jisudeng.",
		Keywords:           "DeepSeek API pricing, DeepSeek model pricing, DeepSeek API access, OpenAI-compatible DeepSeek, Jisudeng model catalog, usage-based billing",
		CanonicalPath:      "/en/catalog/deepseek",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/catalog/deepseek"},
			{Hreflang: "zh-CN", Path: "/catalog/deepseek"},
			{Hreflang: "x-default", Path: "/catalog/deepseek"},
		},
	},
	"/en/catalog/qwen": {
		Title:              "Qwen API Pricing and Access | Jisudeng",
		Description:        "Compare Qwen model access, public API rates, and usage-based pricing through Jisudeng. Use one OpenAI-compatible base URL with unified keys, docs, and billing.",
		TwitterTitle:       "Qwen API Pricing, Models, and OpenAI-Compatible Access",
		TwitterDescription: "Compare Qwen model access, public API rates, usage-based pricing, OpenAI-compatible setup, API key guidance, docs, image API notes, and billing through Jisudeng.",
		Keywords:           "Qwen API pricing, Qwen model pricing, Qwen API access, OpenAI-compatible Qwen, Jisudeng model catalog, usage-based billing",
		CanonicalPath:      "/en/catalog/qwen",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/catalog/qwen"},
			{Hreflang: "zh-CN", Path: "/catalog/qwen"},
			{Hreflang: "x-default", Path: "/catalog/qwen"},
		},
	},
	"/en/catalog/kimi": {
		Title:              "Kimi API Pricing and Access | Jisudeng",
		Description:        "Compare Kimi model access, public API rates, and usage-based pricing through Jisudeng. Use one OpenAI-compatible base URL with unified keys, docs, and billing.",
		TwitterTitle:       "Kimi API Pricing, Models, and OpenAI-Compatible Access",
		TwitterDescription: "Compare Kimi model access, public API rates, usage-based pricing, OpenAI-compatible setup, API key guidance, docs, model catalog, and billing through Jisudeng.",
		Keywords:           "Kimi API pricing, Kimi model pricing, Kimi API access, OpenAI-compatible Kimi, Jisudeng model catalog, usage-based billing",
		CanonicalPath:      "/en/catalog/kimi",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/catalog/kimi"},
			{Hreflang: "zh-CN", Path: "/catalog/kimi"},
			{Hreflang: "x-default", Path: "/catalog/kimi"},
		},
	},
	"/en/catalog/glm": {
		Title:              "GLM API Pricing and Access | Jisudeng",
		Description:        "Compare GLM model access, public API rates, and usage-based pricing through Jisudeng. Use one OpenAI-compatible base URL with unified keys, docs, and billing.",
		TwitterTitle:       "GLM API Pricing, Models, and OpenAI-Compatible Access",
		TwitterDescription: "Compare GLM model access, public API rates, usage-based pricing, OpenAI-compatible setup, API key guidance, docs, model catalog, and billing through Jisudeng.",
		Keywords:           "GLM API pricing, GLM model pricing, GLM API access, OpenAI-compatible GLM, Jisudeng model catalog, usage-based billing",
		CanonicalPath:      "/en/catalog/glm",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/catalog/glm"},
			{Hreflang: "zh-CN", Path: "/catalog/glm"},
			{Hreflang: "x-default", Path: "/catalog/glm"},
		},
	},
	"/en/docs": {
		Title:              "Jisudeng API Docs: OpenAI-Compatible Gateway, Models, Images",
		Description:        "Use Jisudeng with your existing OpenAI SDK. Change only the base URL and API key to access AI models, image APIs, tool setup guides, billing notes, and docs.",
		TwitterDescription: "Use Jisudeng with your existing OpenAI SDK. Change only the base URL and API key to access AI models, image APIs, tool setup guides, billing notes, and production docs.",
		Keywords:           "Jisudeng API docs, OpenAI-compatible SDK, API key setup, AI model API docs, image generation API, Batch Image API, Claude Code setup, Codex CLI setup, Gemini CLI setup",
		CanonicalPath:      "/en/docs",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "article",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/docs"},
			{Hreflang: "zh-CN", Path: "/docs"},
			{Hreflang: "x-default", Path: "/docs"},
		},
	},
	"/en/about": {
		Title:              "About Jisudeng: A Transparent OpenAI-Compatible API Relay",
		Description:        "Learn how Jisudeng provides a transparent OpenAI-compatible API with public pricing, privacy commitments, and practical developer documentation for teams.",
		TwitterTitle:       "About Jisudeng: Transparent AI API, Pricing, and Privacy",
		TwitterDescription: "Learn how Jisudeng routes major AI models through an OpenAI-compatible API with transparent channels, public pricing, request-body privacy, image access, developer docs, and support for teams.",
		Keywords:           "about Jisudeng, transparent AI API relay, OpenAI-compatible gateway, DeepSeek API, model pricing, API privacy, developer API access",
		CanonicalPath:      "/en/about",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "AboutPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/about"},
			{Hreflang: "zh-CN", Path: "/about"},
			{Hreflang: "x-default", Path: "/about"},
		},
	},
	"/en/contact": {
		Title:              "Contact Jisudeng: API, Account, Billing, and Support",
		Description:        "Contact Jisudeng for API keys, model access, billing questions, image generation, documentation, integration help, and technical support.",
		TwitterTitle:       "Contact Jisudeng: API, Billing, and Developer Support",
		TwitterDescription: "Contact Jisudeng for API keys, model access, billing, image generation, docs, integration help, privacy, and technical support for teams using major AI models.",
		Keywords:           "contact Jisudeng, AI API support, API key help, model access support, billing support, OpenAI-compatible integration support, developer support",
		CanonicalPath:      "/en/contact",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "ContactPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/contact"},
			{Hreflang: "zh-CN", Path: "/contact"},
			{Hreflang: "x-default", Path: "/contact"},
		},
	},
}

func isLegacyModelsAPIPath(path string) bool {
	return path == "/models" || strings.HasPrefix(path, "/models/") ||
		path == "/en/models" || strings.HasPrefix(path, "/en/models/")
}

func normalizePublicRouteSEOPath(path string) string {
	clean := strings.TrimSpace(path)
	if clean == "" {
		return "/"
	}
	if i := strings.IndexAny(clean, "?#"); i >= 0 {
		clean = clean[:i]
	}
	if clean == "/" {
		return "/"
	}
	return strings.TrimRight(clean, "/")
}

func resolveRouteSEO(path string) (routeSEO, bool) {
	normalized := normalizePublicRouteSEOPath(path)
	if normalized == "/home" || isLegacyModelsAPIPath(normalized) {
		return routeSEO{}, false
	}
	seo, ok := publicRouteSEO[normalized]
	return seo, ok
}

func routeSEOETag(baseETag, path string) string {
	if _, ok := resolveRouteSEO(path); !ok {
		return baseETag
	}
	base := strings.Trim(baseETag, `"`)
	suffix := strings.Trim(strings.ReplaceAll(normalizePublicRouteSEOPath(path), "/", "-"), "-")
	if suffix == "" {
		suffix = "root"
	}
	return `"` + base + "-seo-" + suffix + `"`
}

func injectRouteSEO(html []byte, path string) []byte {
	seo, ok := resolveRouteSEO(path)
	if !ok {
		return injectNonPublicRouteSEO(html)
	}
	twitterTitle := seo.TwitterTitle
	if strings.TrimSpace(twitterTitle) == "" {
		twitterTitle = seo.Title
	}
	twitterDescription := seo.TwitterDescription
	if strings.TrimSpace(twitterDescription) == "" {
		twitterDescription = seo.Description
	}
	ogType := seo.OGType
	if strings.TrimSpace(ogType) == "" {
		ogType = "website"
	}
	siteName := seo.SiteName
	if strings.TrimSpace(siteName) == "" {
		siteName = routeSEOAuthor
	}

	result := setHTMLLang(html, seo.Lang)
	result = replaceTitleTag(result, seo.Title)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "description")
	}, `<meta name="description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "keywords")
	}, `<meta name="keywords" content="`+htmlpkg.EscapeString(seo.Keywords)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "author")
	}, `<meta name="author" content="`+htmlpkg.EscapeString(routeSEOAuthor)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "format-detection")
	}, `<meta name="format-detection" content="`+htmlpkg.EscapeString(routeSEOFormatDetection)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "robots")
	}, `<meta name="robots" content="index,follow" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:type")
	}, `<meta property="og:type" content="`+htmlpkg.EscapeString(ogType)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:site_name")
	}, `<meta property="og:site_name" content="`+htmlpkg.EscapeString(siteName)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:title")
	}, `<meta property="og:title" content="`+htmlpkg.EscapeString(seo.Title)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:description")
	}, `<meta property="og:description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:url")
	}, `<meta property="og:url" content="`+htmlpkg.EscapeString(absoluteRouteSEOURL(seo.CanonicalPath))+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:locale")
	}, `<meta property="og:locale" content="`+htmlpkg.EscapeString(seo.OGLocale)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:image")
	}, `<meta property="og:image" content="`+htmlpkg.EscapeString(routeSEOImage)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:image:alt")
	}, `<meta property="og:image:alt" content="`+htmlpkg.EscapeString(routeSEOImageAlt)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:card")
	}, `<meta name="twitter:card" content="`+htmlpkg.EscapeString(routeSEOTwitterCard)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:site")
	}, `<meta name="twitter:site" content="`+htmlpkg.EscapeString(routeSEOTwitterHandle)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:creator")
	}, `<meta name="twitter:creator" content="`+htmlpkg.EscapeString(routeSEOTwitterHandle)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:title")
	}, `<meta name="twitter:title" content="`+htmlpkg.EscapeString(twitterTitle)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:description")
	}, `<meta name="twitter:description" content="`+htmlpkg.EscapeString(twitterDescription)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:image")
	}, `<meta name="twitter:image" content="`+htmlpkg.EscapeString(routeSEOImage)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:image:alt")
	}, `<meta name="twitter:image:alt" content="`+htmlpkg.EscapeString(routeSEOImageAlt)+`" />`)
	result = upsertHeadTag(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "canonical")
	}, `<link rel="canonical" href="`+htmlpkg.EscapeString(absoluteRouteSEOURL(seo.CanonicalPath))+`" />`)

	result = removeMatchingTags(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "alternate") && strings.Contains(tag, "hreflang")
	})
	for _, alternate := range seo.Alternates {
		result = injectBeforeHeadClose(result, []byte(fmt.Sprintf(
			`<link rel="alternate" hreflang="%s" href="%s" />`,
			htmlpkg.EscapeString(alternate.Hreflang),
			htmlpkg.EscapeString(absoluteRouteSEOURL(alternate.Path)),
		)))
	}
	result = upsertRouteSEOStructuredData(result, seo)
	return injectPublicRouteFallback(result, seo)
}

// injectPublicRouteFallback gives indexable routes a semantic document when a
// crawler does not execute the SPA. The fallback lives inside #app, so Vue's
// normal mount clears it before rendering the interactive application.
func injectPublicRouteFallback(html []byte, seo routeSEO) []byte {
	const appRootOpen = `<div id="app">`
	start := bytes.Index(html, []byte(appRootOpen))
	if start == -1 {
		return html
	}
	contentStart := start + len(appRootOpen)
	endOffset := bytes.Index(html[contentStart:], []byte(`</div>`))
	if endOffset == -1 {
		return html
	}
	contentEnd := contentStart + endOffset
	if strings.TrimSpace(string(html[contentStart:contentEnd])) != "" {
		return html
	}

	fallback := []byte(buildPublicRouteFallback(seo))
	var result bytes.Buffer
	result.Write(html[:contentStart])
	result.Write(fallback)
	result.Write(html[contentEnd:])
	return result.Bytes()
}

func buildPublicRouteFallback(seo routeSEO) string {
	english := seo.Lang == "en"
	catalogPath := "/catalog"
	docsPath := "/docs"
	if english {
		catalogPath = "/en/catalog"
		docsPath = "/en/docs"
	}

	sectionTitle, primaryLabel, secondaryLabel := "开始使用", "查看模型与价格", "阅读接入文档"
	points := []string{
		"通过一个 OpenAI 兼容 API 接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型。",
		"查看公开模型目录与价格参考；登录后按 API Key 分组确认实际可用模型和价格。",
		"从创建 API Key、配置 SDK 到调用排障，都可以在公开文档中继续完成。",
	}
	if english {
		sectionTitle, primaryLabel, secondaryLabel = "Get started", "Browse models and pricing", "Read the integration docs"
		points = []string{
			"Access DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini, and more through one OpenAI-compatible API.",
			"Review the public catalog and pricing references, then sign in to confirm the models and effective prices available to your API key group.",
			"Continue with API key setup, SDK configuration, requests, and troubleshooting in the public documentation.",
		}
	}

	normalizedPath := normalizePublicRouteSEOPath(seo.CanonicalPath)
	switch {
	case normalizedPath == "/catalog" || normalizedPath == "/en/catalog":
		if english {
			sectionTitle = "Public catalog and pricing"
			points = []string{
				"Compare public model names, families, use cases, and usage-based API pricing references before signing in.",
				"After signing in, the catalog shows the actual availability and effective prices for your API key group.",
				"Use the integration docs to connect an existing OpenAI SDK or compatible tool.",
			}
		} else {
			sectionTitle = "公开模型目录与价格"
			points = []string{
				"登录前可查看公开模型名称、平台、用途分类与按量计费参考。",
				"登录后以 API Key 所属分组显示真实可用模型、有效价格与调用权限。",
				"已有 OpenAI SDK 或兼容工具可继续按接入文档完成配置。",
			}
		}
	case strings.HasPrefix(normalizedPath, "/catalog/") || strings.HasPrefix(normalizedPath, "/en/catalog/"):
		if english {
			sectionTitle = "Model access and integration"
			points = []string{
				"Review this model family’s public access and usage-based pricing references.",
				"Confirm final availability and effective prices after signing in with an API key in an enabled group.",
				"Use the OpenAI-compatible integration docs for API key, base URL, and request setup.",
			}
		} else {
			sectionTitle = "模型接入与调用"
			points = []string{
				"查看该模型系列的公开接入信息与按量计费参考。",
				"登录后按 API Key 所属分组确认最终可用性和实际有效价格。",
				"使用 OpenAI 兼容接入文档完成 API Key、base URL 与请求配置。",
			}
		}
	case normalizedPath == "/docs" || normalizedPath == "/en/docs":
		if english {
			sectionTitle, primaryLabel, secondaryLabel = "OpenAI-compatible integration", "Browse models and pricing", "Create an API key"
			points = []string{
				"Create an API key and choose a group with the models needed by your application.",
				"Use the Jisudeng base URL with your existing OpenAI SDK or compatible client.",
				"Review image APIs, billing notes, request examples, and troubleshooting before production use.",
			}
		} else {
			sectionTitle, primaryLabel, secondaryLabel = "OpenAI 兼容接入", "查看模型与价格", "创建 API Key"
			points = []string{
				"创建 API Key，并选择包含所需模型的可用分组。",
				"把现有 OpenAI SDK 或兼容客户端的 base URL 切换到极速蹬。",
				"在生产调用前核对图像 API、计费说明、请求示例和常见排障步骤。",
			}
		}
	case normalizedPath == "/download/android":
		sectionTitle, primaryLabel, secondaryLabel = "Android 客户端下载与接入", "查看下载与版本信息", "阅读接入文档"
		points = []string{
			"下载 JisudengChat Android APK，并在安装前核对页面提供的版本信息与校验说明。",
			"使用极速蹬账号登录后，可同步查看余额、分组、API Key 和可用模型。",
			"需要配置 API 或排查调用问题时，继续阅读公开接入文档。",
		}
		catalogPath = "/download/android"
	case normalizedPath == "/about" || normalizedPath == "/en/about":
		if english {
			sectionTitle = "How Jisudeng works"
			points = []string{
				"Jisudeng provides a practical OpenAI-compatible API, public pricing references, and developer documentation for teams.",
				"Review public models and integration guidance before creating an API key for an enabled group.",
				"Use the support page when account, billing, access, or integration questions need help.",
			}
		} else {
			sectionTitle = "了解极速蹬"
			points = []string{
				"极速蹬提供 OpenAI 兼容 API、公开模型价格参考和面向开发者的接入文档。",
				"创建 API Key 前可先查看公开模型目录和接入指南，再按分组确认可用性。",
				"账号、计费、模型访问或接入问题可通过客服页面继续处理。",
			}
		}
	case normalizedPath == "/contact" || normalizedPath == "/en/contact":
		if english {
			sectionTitle, primaryLabel, secondaryLabel = "Account and API support", "Browse models and pricing", "Read the integration docs"
			points = []string{
				"Support covers account access, API keys, model availability, billing, image generation, and integration questions.",
				"Review the public catalog and documentation first to confirm the relevant model and integration path.",
				"Do not include API keys, billing records, or other private account data in public pages.",
			}
		} else {
			sectionTitle, primaryLabel, secondaryLabel = "账号与 API 支持", "查看模型与价格", "阅读接入文档"
			points = []string{
				"可获得登录注册、API Key、模型可用性、充值支付、图像生成和接入配置支持。",
				"联系前可先查看公开模型目录和接入文档，确认对应模型与配置路径。",
				"不要在公开页面或公开内容中提供 API Key、账单记录等私有账号数据。",
			}
		}
	}

	var content strings.Builder
	content.WriteString(`<main data-jisudeng-public-fallback="true"><header><p>`)
	content.WriteString(htmlpkg.EscapeString(seo.SiteName))
	content.WriteString(`</p><h1>`)
	content.WriteString(htmlpkg.EscapeString(seo.Title))
	content.WriteString(`</h1><p>`)
	content.WriteString(htmlpkg.EscapeString(seo.Description))
	content.WriteString(`</p></header><section><h2>`)
	content.WriteString(htmlpkg.EscapeString(sectionTitle))
	content.WriteString(`</h2><ul>`)
	for _, point := range points {
		content.WriteString(`<li>`)
		content.WriteString(htmlpkg.EscapeString(point))
		content.WriteString(`</li>`)
	}
	content.WriteString(`</ul></section>`)
	if isCatalogLandingRoute(normalizedPath) {
		appendCatalogFallbackSection(&content, english)
	}
	if isDocsRoute(normalizedPath) {
		appendDocsFallbackSection(&content, english)
	}
	content.WriteString(`<nav aria-label="`)
	if english {
		content.WriteString(`Public resources`)
	} else {
		content.WriteString(`公开资源`)
	}
	content.WriteString(`"><a href="`)
	content.WriteString(catalogPath)
	content.WriteString(`">`)
	content.WriteString(htmlpkg.EscapeString(primaryLabel))
	content.WriteString(`</a><a href="`)
	content.WriteString(docsPath)
	content.WriteString(`">`)
	content.WriteString(htmlpkg.EscapeString(secondaryLabel))
	content.WriteString(`</a></nav></main>`)
	return content.String()
}

func isCatalogLandingRoute(path string) bool {
	normalized := normalizePublicRouteSEOPath(path)
	return normalized == "/catalog" || normalized == "/en/catalog"
}

func isDocsRoute(path string) bool {
	normalized := normalizePublicRouteSEOPath(path)
	return normalized == "/docs" || normalized == "/en/docs"
}

func isHomeRoute(path string) bool {
	normalized := normalizePublicRouteSEOPath(path)
	return normalized == "/" || normalized == "/en"
}

// publicCatalogFallbackEntries is intentionally static and route-owned. It
// lists only model-family pages that are visibly linked by the catalog, rather
// than inventing volatile price or entitlement data for an unauthenticated
// crawler.
func publicCatalogFallbackEntries(english bool) []publicCatalogFallbackEntry {
	if english {
		return []publicCatalogFallbackEntry{
			{Path: "/en/catalog/deepseek", Name: "DeepSeek API", Description: "Public access guidance, usage-based rate references, and OpenAI-compatible integration."},
			{Path: "/en/catalog/qwen", Name: "Qwen API", Description: "Public model-family guidance, rate references, and unified API setup."},
			{Path: "/en/catalog/kimi", Name: "Kimi API", Description: "Model access guidance, pricing references, and compatible SDK setup."},
			{Path: "/en/catalog/glm", Name: "GLM API", Description: "Public integration guidance, usage-based pricing references, and API-key setup."},
		}
	}
	return []publicCatalogFallbackEntry{
		{Path: "/catalog/deepseek", Name: "DeepSeek API", Description: "查看 DeepSeek 系列的公开接入说明、按量计费参考和 OpenAI 兼容调用路径。"},
		{Path: "/catalog/qwen", Name: "Qwen API", Description: "查看 Qwen 系列的公开模型说明、价格参考和统一 API 配置方式。"},
		{Path: "/catalog/kimi", Name: "Kimi API", Description: "查看 Kimi 系列的模型接入说明、价格参考和兼容 SDK 配置。"},
		{Path: "/catalog/glm", Name: "GLM API", Description: "查看 GLM 系列的公开接入说明、按量计费参考和 API Key 配置。"},
	}
}

func appendCatalogFallbackSection(content *strings.Builder, english bool) {
	title := "公开模型系列"
	intro := "以下模型系列页面提供可公开核对的接入信息和价格参考；登录后仍应以 API Key 所属分组显示的可用性与有效价格为准。"
	if english {
		title = "Public model families"
		intro = "These model-family pages provide public access guidance and rate references. After sign-in, availability and effective pricing remain scoped to the API key group."
	}
	content.WriteString(`<section><h2>`)
	content.WriteString(htmlpkg.EscapeString(title))
	content.WriteString(`</h2><p>`)
	content.WriteString(htmlpkg.EscapeString(intro))
	content.WriteString(`</p><ol>`)
	for _, entry := range publicCatalogFallbackEntries(english) {
		content.WriteString(`<li><a href="`)
		content.WriteString(htmlpkg.EscapeString(entry.Path))
		content.WriteString(`">`)
		content.WriteString(htmlpkg.EscapeString(entry.Name))
		content.WriteString(`</a><p>`)
		content.WriteString(htmlpkg.EscapeString(entry.Description))
		content.WriteString(`</p></li>`)
	}
	content.WriteString(`</ol></section>`)
}

func appendDocsFallbackSection(content *strings.Builder, english bool) {
	title := "接入步骤"
	steps := []string{
		"创建 API Key，并选择包含所需模型的可用分组。",
		"将现有 OpenAI SDK 或兼容客户端的 base URL 配置为 https://api.jisudeng.com/v1。",
		"使用 POST /v1/chat/completions 发起第一个兼容请求，并在生产前核对模型、价格和权限。",
		"遇到鉴权、模型可用性、图像 API 或计费问题时，继续查阅对应文档和排障说明。",
	}
	if english {
		title = "Integration steps"
		steps = []string{
			"Create an API key and choose an enabled group with the models your application needs.",
			"Set an existing OpenAI SDK or compatible client's base URL to https://api.jisudeng.com/v1.",
			"Send the first compatible request to POST /v1/chat/completions, then verify models, rates, and permissions before production use.",
			"Use the relevant documentation and troubleshooting guidance for authentication, availability, image APIs, and billing questions.",
		}
	}
	content.WriteString(`<section><h2>`)
	content.WriteString(htmlpkg.EscapeString(title))
	content.WriteString(`</h2><ol>`)
	for _, step := range steps {
		content.WriteString(`<li>`)
		content.WriteString(htmlpkg.EscapeString(step))
		content.WriteString(`</li>`)
	}
	content.WriteString(`</ol></section>`)
}

func injectNonPublicRouteSEO(html []byte) []byte {
	result := upsertHeadTag(html, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "robots")
	}, `<meta name="robots" content="noindex,nofollow" />`)
	result = removeMatchingTags(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "canonical") || (tagHasAttr(tag, "rel", "alternate") && strings.Contains(tag, "hreflang"))
	})
	return removeRouteSEOStructuredData(result)
}

func upsertRouteSEOStructuredData(html []byte, seo routeSEO) []byte {
	result := removeRouteSEOStructuredData(html)
	payload := buildRouteSEOJSONLD(seo)
	if payload == "" {
		return result
	}
	return injectBeforeHeadClose(result, []byte(`<script type="application/ld+json" data-jisudeng-route-seo="true">`+payload+`</script>`))
}

func buildRouteSEOJSONLD(seo routeSEO) string {
	siteName := seo.SiteName
	if strings.TrimSpace(siteName) == "" {
		siteName = routeSEOAuthor
	}
	canonical := absoluteRouteSEOURL(seo.CanonicalPath)
	var graph map[string]any
	switch {
	case isHomeRoute(seo.CanonicalPath):
		organization := map[string]any{
			"@type":       "Organization",
			"name":        siteName,
			"url":         routeSEOOrigin + "/",
			"description": seo.Description,
		}
		application := map[string]any{
			"@type":               "WebApplication",
			"name":                "Jisudeng",
			"applicationCategory": "DeveloperApplication",
			"operatingSystem":     "Web",
			"description":         seo.Description,
			"url":                 canonical,
			"inLanguage":          seo.Lang,
		}
		graph = map[string]any{
			"@context": "https://schema.org",
			"@graph":   []any{organization, application},
		}
	case isCatalogLandingRoute(seo.CanonicalPath):
		entries := publicCatalogFallbackEntries(seo.Lang == "en")
		itemListName := "极速蹬公开模型系列"
		if seo.Lang == "en" {
			itemListName = "Jisudeng public model families"
		}
		items := make([]any, 0, len(entries))
		for index, entry := range entries {
			items = append(items, map[string]any{
				"@type":    "ListItem",
				"position": index + 1,
				"name":     entry.Name,
				"url":      absoluteRouteSEOURL(entry.Path),
			})
		}
		graph = map[string]any{
			"@context":        "https://schema.org",
			"@type":           "ItemList",
			"name":            itemListName,
			"description":     seo.Description,
			"url":             canonical,
			"inLanguage":      seo.Lang,
			"itemListElement": items,
		}
	default:
		return ""
	}
	payload, err := json.Marshal(graph)
	if err != nil {
		return "{}"
	}
	return string(payload)
}

func absoluteRouteSEOURL(path string) string {
	return routeSEOOrigin + path
}

func setHTMLLang(html []byte, lang string) []byte {
	return replaceFirstTag(html, "html", func(string) bool { return true }, func(tag string) string {
		return setTagAttr(tag, "lang", lang)
	})
}

func replaceTitleTag(html []byte, title string) []byte {
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return injectBeforeHeadClose(html, []byte("<title>"+htmlpkg.EscapeString(title)+"</title>"))
	}
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.WriteString("<title>")
	buf.WriteString(htmlpkg.EscapeString(title))
	buf.WriteString("</title>")
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func upsertHeadTag(html []byte, tagName string, match func(string) bool, replacement string) []byte {
	replaced := false
	result := replaceFirstTag(html, tagName, match, func(string) string {
		replaced = true
		return replacement
	})
	if replaced {
		return result
	}
	return injectBeforeHeadClose(html, []byte(replacement))
}

func replaceFirstTag(html []byte, tagName string, match func(string) bool, replacement func(string) string) []byte {
	token := []byte("<" + tagName)
	for offset := 0; offset < len(html); {
		idxOffset := bytes.Index(bytes.ToLower(html[offset:]), token)
		if idxOffset == -1 {
			return html
		}
		idx := offset + idxOffset
		endOffset := bytes.IndexByte(html[idx:], '>')
		if endOffset == -1 {
			return html
		}
		end := idx + endOffset + 1
		tag := string(html[idx:end])
		if match(strings.ToLower(tag)) {
			var buf bytes.Buffer
			buf.Write(html[:idx])
			buf.WriteString(replacement(tag))
			buf.Write(html[end:])
			return buf.Bytes()
		}
		offset = end
	}
	return html
}

func removeMatchingTags(html []byte, tagName string, match func(string) bool) []byte {
	token := []byte("<" + tagName)
	var buf bytes.Buffer
	cursor := 0
	for cursor < len(html) {
		idxOffset := bytes.Index(bytes.ToLower(html[cursor:]), token)
		if idxOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		idx := cursor + idxOffset
		endOffset := bytes.IndexByte(html[idx:], '>')
		if endOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		end := idx + endOffset + 1
		tag := strings.ToLower(string(html[idx:end]))
		if match(tag) {
			buf.Write(html[cursor:idx])
		} else {
			buf.Write(html[cursor:end])
		}
		cursor = end
	}
	return buf.Bytes()
}

func removeRouteSEOStructuredData(html []byte) []byte {
	token := []byte("<script")
	closeToken := []byte("</script>")
	var buf bytes.Buffer
	cursor := 0
	for cursor < len(html) {
		idxOffset := bytes.Index(bytes.ToLower(html[cursor:]), token)
		if idxOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		idx := cursor + idxOffset
		openEndOffset := bytes.IndexByte(html[idx:], '>')
		if openEndOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		openEnd := idx + openEndOffset + 1
		tag := strings.ToLower(string(html[idx:openEnd]))
		closeOffset := bytes.Index(bytes.ToLower(html[openEnd:]), closeToken)
		if closeOffset == -1 {
			buf.Write(html[cursor:openEnd])
			cursor = openEnd
			continue
		}
		blockEnd := openEnd + closeOffset + len(closeToken)
		if tagHasAttr(tag, "type", "application/ld+json") && tagHasAttr(tag, "data-jisudeng-route-seo", "true") {
			buf.Write(html[cursor:idx])
			cursor = blockEnd
			continue
		}
		buf.Write(html[cursor:blockEnd])
		cursor = blockEnd
	}
	return buf.Bytes()
}

func injectBeforeHeadClose(html, tag []byte) []byte {
	headClose := []byte("</head>")
	idx := bytes.Index(bytes.ToLower(html), headClose)
	if idx == -1 {
		return html
	}
	var buf bytes.Buffer
	buf.Write(html[:idx])
	buf.Write(tag)
	buf.WriteByte('\n')
	buf.Write(html[idx:])
	return buf.Bytes()
}

func tagHasAttr(tag, attr, value string) bool {
	return strings.Contains(tag, attr+`="`+strings.ToLower(value)+`"`) ||
		strings.Contains(tag, attr+`='`+strings.ToLower(value)+`'`)
}

func setTagAttr(tag, attr, value string) string {
	escaped := htmlpkg.EscapeString(value)
	lower := strings.ToLower(tag)
	for _, quote := range []byte{'"', '\''} {
		prefix := attr + "=" + string(quote)
		start := strings.Index(lower, prefix)
		if start == -1 {
			continue
		}
		valueStart := start + len(prefix)
		valueEndOffset := strings.IndexByte(tag[valueStart:], quote)
		if valueEndOffset == -1 {
			return tag
		}
		valueEnd := valueStart + valueEndOffset
		return tag[:valueStart] + escaped + tag[valueEnd:]
	}
	insertAt := len(tag) - 1
	if insertAt < 0 {
		return tag
	}
	return tag[:insertAt] + ` ` + attr + `="` + escaped + `"` + tag[insertAt:]
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path
		if isLegacyModelsPageNavigation(c.Request) {
			setModelsCompatibilityVary(c)
			c.Redirect(http.StatusPermanentRedirect, legacyModelsCatalogLocation(c.Request))
			c.Abort()
			return
		}

		if shouldBypassEmbeddedFrontendRequest(c.Request) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if cleanPath != "index.html" && tryServeOverrideFile(c, overrideDir, cleanPath) {
			return
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		if isEmbeddedAssetRequest(cleanPath) {
			serveMissingEmbeddedAsset(c)
			return
		}

		serveIndexHTML(c, distFS)
	}
}

func isEmbeddedAssetRequest(cleanPath string) bool {
	return strings.HasPrefix(cleanPath, "assets/")
}

func serveMissingEmbeddedAsset(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	c.String(http.StatusNotFound, "static asset not found")
	c.Abort()
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/home" ||
		trimmed == "/downloads/android-version.json" ||
		trimmed == "/robots.txt" ||
		trimmed == "/sitemap.xml" ||
		trimmed == "/llms.txt" ||
		trimmed == "/llms-full.txt" ||
		trimmed == "/llms.small-txt" ||
		trimmed == "/.well-known/ai.txt" ||
		trimmed == "/models" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		strings.HasPrefix(trimmed, "/images/") ||
		strings.HasPrefix(trimmed, "/videos/")
}

func shouldBypassEmbeddedFrontendRequest(r *http.Request) bool {
	if r == nil {
		return true
	}
	return shouldBypassEmbeddedFrontend(r.URL.Path)
}

func isLegacyModelsPageNavigation(r *http.Request) bool {
	if r == nil || !isFrontendHTMLNavigation(r) {
		return false
	}
	_, ok := legacyModelsCatalogPath(r.URL.Path)
	return ok
}

func legacyModelsCatalogLocation(r *http.Request) string {
	if r == nil {
		return "/catalog"
	}
	target, ok := legacyModelsCatalogPath(r.URL.Path)
	if !ok {
		return "/catalog"
	}
	if strings.TrimSpace(r.URL.RawQuery) == "" {
		return target
	}
	return target + "?" + r.URL.RawQuery
}

func legacyModelsCatalogPath(path string) (string, bool) {
	switch strings.TrimSpace(path) {
	case "/models":
		return "/catalog", true
	case "/en/models":
		return "/en/catalog", true
	}

	switch {
	case strings.HasPrefix(path, "/models/"):
		return "/catalog" + strings.TrimPrefix(path, "/models"), true
	case strings.HasPrefix(path, "/en/models/"):
		return "/en/catalog" + strings.TrimPrefix(path, "/en/models"), true
	default:
		return "", false
	}
}

func setModelsCompatibilityVary(c *gin.Context) {
	// These headers decide whether /models remains an API request or becomes a
	// legacy browser redirect, so every one must partition shared-cache entries.
	c.Header("Vary", "Accept, Authorization, X-API-Key, X-Goog-API-Key")
}

func setRouteSEORobotsHeader(c *gin.Context, path string) {
	if _, ok := resolveRouteSEO(path); ok {
		c.Header("X-Robots-Tag", "index, follow")
		return
	}
	c.Header("X-Robots-Tag", "noindex, nofollow")
}

func isFrontendHTMLNavigation(r *http.Request) bool {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		return false
	}
	if r.Header.Get("Authorization") != "" ||
		r.Header.Get("x-api-key") != "" ||
		r.Header.Get("x-goog-api-key") != "" {
		return false
	}
	acceptHeader := strings.ToLower(r.Header.Get("Accept"))
	acceptsHTML := strings.Contains(acceptHeader, "text/html")
	acceptsJSON := strings.Contains(acceptHeader, "application/json")
	// Crawlers commonly send the generic media range and no browser-only
	// Sec-Fetch headers. Only that header-less shape is treated as a document;
	// browser fetches with an explicit cors/empty mode retain API semantics.
	hasFetchMetadata := strings.TrimSpace(r.Header.Get("Sec-Fetch-Mode")) != "" ||
		strings.TrimSpace(r.Header.Get("Sec-Fetch-Dest")) != "" ||
		strings.TrimSpace(r.Header.Get("Sec-Fetch-Site")) != ""
	acceptsGenericDocument := strings.EqualFold(strings.TrimSpace(r.Header.Get("Accept")), "*/*") && !hasFetchMetadata
	isDocumentNavigation := strings.EqualFold(strings.TrimSpace(r.Header.Get("Sec-Fetch-Mode")), "navigate") &&
		strings.EqualFold(strings.TrimSpace(r.Header.Get("Sec-Fetch-Dest")), "document")
	// A client may advertise both HTML and JSON (for example, an SDK that uses
	// a broad default Accept). Without browser document metadata, preserve the
	// protected API contract whenever JSON is explicitly requested.
	if acceptsJSON && !isDocumentNavigation {
		return false
	}
	return acceptsHTML || acceptsGenericDocument || isDocumentNavigation
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	setRouteSEORobotsHeader(c, c.Request.URL.Path)
	content = injectRouteSEO(content, c.Request.URL.Path)
	content = localizeEnglishHTMLShell(content, c.Request.URL.Path)
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}

// ReadEmbeddedAsset returns a public frontend asset for compatibility routes
// that need a database-backed override with a static fallback.
func ReadEmbeddedAsset(name string) ([]byte, error) {
	return fs.ReadFile(frontendFS, "dist/"+strings.TrimLeft(name, "/"))
}
