//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
	seoTitleSuffix       = "AI API Gateway 与中文提示词库"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontendRequest(c.Request) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" {
			s.serveIndexHTML(c)
			return
		}
		if s.tryServeOverride(c, cleanPath) {
			return
		}
		if !s.fileExists(cleanPath) {
			if isEmbeddedAssetRequest(cleanPath) {
				serveMissingEmbeddedAsset(c)
				return
			}
			s.serveIndexHTML(c)
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	path := c.Request.URL.Path
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		etag := routeSEOETag(cached.ETag, path)
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == etag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)
		content = injectRouteSEO(content, path)

		c.Header("ETag", etag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", injectRouteSEO(s.baseHTML, path))
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", injectRouteSEO(s.baseHTML, path))
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)
	content = injectRouteSEO(content, path)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", routeSEOETag(cached.ETag, path))
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteTitle(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)

	return result
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// injectSiteTitle replaces the static <title> in HTML with the configured site title.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}
	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(buildSiteTitle(siteName)) + "</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func buildSiteTitle(siteName string) string {
	return strings.TrimSpace(siteName) + " - " + seoTitleSuffix
}

type routeSEOAlternate struct {
	Hreflang string
	Path     string
}

type routeSEO struct {
	Title              string
	Description        string
	TwitterTitle       string
	TwitterDescription string
	Keywords           string
	CanonicalPath      string
	Lang               string
	OGLocale           string
	OGType             string
	SiteName           string
	StructuredType     string
	Alternates         []routeSEOAlternate
}

const routeSEOOrigin = "https://www.jisudeng.com"

const (
	routeSEOAuthor          = "Jisudeng"
	routeSEOImage           = "https://www.jisudeng.com/logo.png"
	routeSEOImageAlt        = "Jisudeng logo"
	routeSEOFormatDetection = "telephone=no,email=no,address=no"
	routeSEOTwitterCard     = "summary"
	routeSEOTwitterHandle   = "@jisudeng"
)

var publicRouteSEO = map[string]routeSEO{
	"/": {
		Title:              "极速蹬 - OpenAI兼容 AI API 网关与多模型服务平台",
		Description:        "极速蹬为开发者、团队和 AI 工具用户提供 OpenAI 兼容 API 网关，统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，支持公开价格、文档、图像生成、API Key 管理与按量计费。",
		TwitterTitle:       "极速蹬 OpenAI兼容 API 网关 - DeepSeek、Qwen、Kimi、GLM 多模型统一接入",
		TwitterDescription: "极速蹬统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，提供 OpenAI 兼容 API、公开模型价格、图像生成、API Key 管理、文档和按量计费服务，适合把现有 OpenAI SDK、AI 工具、自动化脚本和业务应用迁移到统一入口，并持续比较模型能力、调用权限与成本。",
		Keywords:           "极速蹬, AI API Gateway, OpenAI 兼容 API, AI 模型接口, DeepSeek API, Qwen API, Kimi API, GLM API, Claude API, Gemini API, 图像生成 API, API Key, 模型价格",
		CanonicalPath:      "/",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "WebSite",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "x-default", Path: "/en/"},
		},
	},
	"/home": {
		Title:              "极速蹬 - OpenAI兼容 AI API 网关与多模型服务平台",
		Description:        "极速蹬为开发者、团队和 AI 工具用户提供 OpenAI 兼容 API 网关，统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，支持公开价格、文档、图像生成、API Key 管理与按量计费。",
		TwitterTitle:       "极速蹬 OpenAI兼容 API 网关 - DeepSeek、Qwen、Kimi、GLM 多模型统一接入",
		TwitterDescription: "极速蹬统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，提供 OpenAI 兼容 API、公开模型价格、图像生成、API Key 管理、文档和按量计费服务，适合把现有 OpenAI SDK、AI 工具、自动化脚本和业务应用迁移到统一入口，并持续比较模型能力、调用权限与成本。",
		Keywords:           "极速蹬, AI API Gateway, OpenAI 兼容 API, AI 模型接口, DeepSeek API, Qwen API, Kimi API, GLM API, Claude API, Gemini API, 图像生成 API, API Key, 模型价格",
		CanonicalPath:      "/",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "WebSite",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "x-default", Path: "/en/"},
		},
	},
	"/models": {
		Title:              "极速蹬模型价格与 API 目录 - 多模型公开计费与调用指南",
		Description:        "查看极速蹬公开模型目录、模型平台、用途分类与 USD / 1M tokens 计费参考，覆盖 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，登录后可查看分组有效价格与调用权限，帮助开发者快速评估成本。",
		TwitterTitle:       "极速蹬模型价格与 API 目录 - DeepSeek、Qwen、Kimi、GLM、Claude 多模型公开计费",
		TwitterDescription: "查看极速蹬公开模型目录、模型平台、用途分类、USD / 1M tokens 计费参考和分组有效价格，覆盖 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等多模型 API 调用，帮助开发者快速评估成本、调用权限、模型能力与接入路径，并在登录后核对账号实际可用价格表。",
		Keywords:           "极速蹬模型价格, AI 模型目录, API 计费, DeepSeek API 价格, Qwen API 价格, Kimi API 价格, GLM API 价格, Claude API, Gemini API, OpenAI 兼容接口",
		CanonicalPath:      "/models",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/models"},
			{Hreflang: "en", Path: "/en/models"},
			{Hreflang: "x-default", Path: "/en/models"},
		},
	},
	"/docs": {
		Title:              "极速蹬 API 文档 - OpenAI兼容接口、模型调用与计费指南",
		Description:        "阅读极速蹬 API Key、OpenAI 兼容接口、模型选择、图片生成、异步任务、Batch Image、工具接入和计费说明，快速完成从注册到生产调用的配置。文档覆盖常见 SDK、命令行工具、环境安装与排障，适合开发者、团队和 AI 工具用户查阅。",
		TwitterTitle:       "极速蹬 API 文档 - OpenAI兼容接口、模型调用、图像生成、Batch Image 与计费指南",
		TwitterDescription: "阅读极速蹬 API 文档，完成 API Key、OpenAI 兼容接口、模型调用、图片生成、异步任务、Batch Image、工具接入、计费说明、SDK 配置和生产排障，帮助团队从注册、创建 Key、切换 base URL 到上线调用都能快速查到步骤、示例、权限说明、排障路径、上线检查和常见问题答案。",
		Keywords:           "极速蹬文档, API 接入指南, OpenAI 兼容 SDK, API Key 设置, 图片生成 API, Batch Image, 异步图片任务, Claude Code, Codex CLI, Gemini CLI",
		CanonicalPath:      "/docs",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "article",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/docs"},
			{Hreflang: "en", Path: "/en/docs"},
			{Hreflang: "x-default", Path: "/en/docs"},
		},
	},
	"/download/android": {
		Title:              "JisudengChat Android 下载 - 极速蹬 AI 客户端与移动模型调用入口",
		Description:        "下载 JisudengChat Android APK，使用极速蹬账号登录并同步余额、分组、API Key 和可用模型，在手机上查看账户状态、接入文档、模型调用入口和更新信息。页面提供版本号、安装包校验、下载说明与故障提示，适合已注册用户快速安装并开始移动端使用。",
		TwitterTitle:       "JisudengChat Android 下载 - 极速蹬 AI 客户端、API Key 与模型调用入口",
		TwitterDescription: "下载 JisudengChat Android APK，使用极速蹬账号登录并同步余额、分组、API Key、可用模型、接入文档、账户状态和更新信息。页面提供版本号、安装包校验、下载说明、更新提示和移动端入口，帮助已注册用户在手机上快速进入 AI 模型调用、账户查看、文档查询、移动测试与日常使用工作流。",
		Keywords:           "JisudengChat Android, 极速蹬 APP, Android APK 下载, AI 客户端, API Key, 模型调用, 移动端 AI 工具",
		CanonicalPath:      "/download/android",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/download/android"},
			{Hreflang: "x-default", Path: "/download/android"},
		},
	},
	"/about": {
		Title:              "关于极速蹬 - OpenAI兼容 API 网关、模型目录与提示词库",
		Description:        "了解极速蹬如何为开发者、团队和 AI 工具用户提供 OpenAI 兼容 API 网关、模型目录、公开价格、接入文档、图像生成、API Key 管理和提示词库，统一接入 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型，帮助快速评估能力、成本和上线路径。",
		TwitterTitle:       "关于极速蹬 - OpenAI兼容 API 网关、模型价格、图像生成、API 文档与提示词库服务入口指南",
		TwitterDescription: "了解极速蹬如何统一 DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型入口，提供 OpenAI 兼容 API、公开价格、API Key 管理、接入文档、图像生成和提示词库，帮助开发者、团队和 AI 工具用户更快完成模型选择、成本评估、测试接入、生产迁移与日常调用。",
		Keywords:           "关于极速蹬, AI API 网关, OpenAI 兼容 API, 多模型服务, 模型价格, API 文档, 图像生成, 提示词库, DeepSeek API, Qwen API, Kimi API, GLM API",
		CanonicalPath:      "/about",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "AboutPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/about"},
			{Hreflang: "x-default", Path: "/about"},
		},
	},
	"/contact": {
		Title:              "联系极速蹬客服 - API、模型调用、充值、账号与接入支持入口",
		Description:        "联系极速蹬客服获取登录注册、API Key、模型调用、充值支付、余额、分组权限、文档接入、图像生成、账号安全和故障排查支持。我们会帮助开发者和团队确认 OpenAI 兼容 API 接入路径、模型可用性、价格说明、调用示例、SDK 配置和上线问题。",
		TwitterTitle:       "联系极速蹬客服 - API Key、模型调用、充值、账号、图像生成、API 文档与开发者接入支持入口",
		TwitterDescription: "通过极速蹬客服入口获取登录注册、API Key、模型调用、充值支付、余额、分组权限、文档接入、图像生成、账号安全和故障排查支持。我们会围绕 OpenAI 兼容 API、DeepSeek、Qwen、Kimi、GLM、GPT、Claude、Gemini 等模型的可用性、价格说明、接入配置和上线问题提供帮助。",
		Keywords:           "联系极速蹬, 极速蹬客服, API Key 支持, 模型调用支持, 充值支付支持, OpenAI 兼容 API 接入, 图像生成支持, 开发者支持",
		CanonicalPath:      "/contact",
		Lang:               "zh-CN",
		OGLocale:           "zh_CN",
		OGType:             "website",
		SiteName:           "极速蹬",
		StructuredType:     "ContactPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/contact"},
			{Hreflang: "x-default", Path: "/contact"},
		},
	},
	"/en": {
		Title:              "Jisudeng: One OpenAI-Compatible API for Frontier AI Models",
		Description:        "Access DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through one OpenAI-compatible API with unified keys, public pricing, image APIs, billing, docs.",
		TwitterDescription: "Jisudeng unifies DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more behind one OpenAI-compatible API, with public pricing, API docs, image generation, usage controls, and billing.",
		Keywords:           "Jisudeng, OpenAI-compatible API, AI API gateway, DeepSeek API, Qwen API, Kimi API, GLM API, Claude API, Gemini API, model pricing, image generation API, API key",
		CanonicalPath:      "/en/",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "WebSite",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "x-default", Path: "/en/"},
		},
	},
	"/en/models": {
		Title:              "DeepSeek, Qwen, Kimi, GLM, Claude API Pricing | Jisudeng",
		Description:        "Compare model access, public API rates, and usage-based pricing for DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through Jisudeng.",
		TwitterTitle:       "DeepSeek, Qwen, Kimi, GLM, GPT, Claude API Pricing | Jisudeng",
		TwitterDescription: "Compare model access, public API rates, and usage-based pricing for DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through Jisudeng, with docs and API key setup guidance.",
		Keywords:           "AI model API pricing, DeepSeek API pricing, Qwen API pricing, Kimi API pricing, GLM API pricing, Claude API, Gemini API, OpenAI-compatible models, usage-based billing",
		CanonicalPath:      "/en/models",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "website",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/models"},
			{Hreflang: "zh-CN", Path: "/models"},
			{Hreflang: "x-default", Path: "/en/models"},
		},
	},
	"/en/docs": {
		Title:              "Jisudeng API Docs: OpenAI-Compatible Gateway, Models, Images",
		Description:        "Use Jisudeng with your existing OpenAI SDK. Change only the base URL and API key to access AI models, image APIs, tool setup guides, billing notes, and docs.",
		TwitterDescription: "Use Jisudeng with your existing OpenAI SDK. Change only the base URL and API key to access AI models, image APIs, tool setup guides, billing notes, and production docs.",
		Keywords:           "Jisudeng API docs, OpenAI-compatible SDK, API key setup, AI model API docs, image generation API, Batch Image API, Claude Code setup, Codex CLI setup, Gemini CLI setup",
		CanonicalPath:      "/en/docs",
		Lang:               "en",
		OGLocale:           "en_US",
		OGType:             "article",
		SiteName:           "Jisudeng",
		StructuredType:     "CollectionPage",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/docs"},
			{Hreflang: "zh-CN", Path: "/docs"},
			{Hreflang: "x-default", Path: "/en/docs"},
		},
	},
}

func normalizePublicRouteSEOPath(path string) string {
	clean := strings.TrimSpace(path)
	if clean == "" {
		return "/"
	}
	if i := strings.IndexAny(clean, "?#"); i >= 0 {
		clean = clean[:i]
	}
	if clean == "/" {
		return "/"
	}
	return strings.TrimRight(clean, "/")
}

func resolveRouteSEO(path string) (routeSEO, bool) {
	seo, ok := publicRouteSEO[normalizePublicRouteSEOPath(path)]
	return seo, ok
}

func routeSEOETag(baseETag, path string) string {
	if _, ok := resolveRouteSEO(path); !ok {
		return baseETag
	}
	base := strings.Trim(baseETag, `"`)
	suffix := strings.Trim(strings.ReplaceAll(normalizePublicRouteSEOPath(path), "/", "-"), "-")
	if suffix == "" {
		suffix = "root"
	}
	return `"` + base + "-seo-" + suffix + `"`
}

func injectRouteSEO(html []byte, path string) []byte {
	seo, ok := resolveRouteSEO(path)
	if !ok {
		return html
	}
	twitterTitle := seo.TwitterTitle
	if strings.TrimSpace(twitterTitle) == "" {
		twitterTitle = seo.Title
	}
	twitterDescription := seo.TwitterDescription
	if strings.TrimSpace(twitterDescription) == "" {
		twitterDescription = seo.Description
	}
	ogType := seo.OGType
	if strings.TrimSpace(ogType) == "" {
		ogType = "website"
	}
	siteName := seo.SiteName
	if strings.TrimSpace(siteName) == "" {
		siteName = routeSEOAuthor
	}

	result := setHTMLLang(html, seo.Lang)
	result = replaceTitleTag(result, seo.Title)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "description")
	}, `<meta name="description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "keywords")
	}, `<meta name="keywords" content="`+htmlpkg.EscapeString(seo.Keywords)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "author")
	}, `<meta name="author" content="`+htmlpkg.EscapeString(routeSEOAuthor)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "format-detection")
	}, `<meta name="format-detection" content="`+htmlpkg.EscapeString(routeSEOFormatDetection)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:type")
	}, `<meta property="og:type" content="`+htmlpkg.EscapeString(ogType)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:site_name")
	}, `<meta property="og:site_name" content="`+htmlpkg.EscapeString(siteName)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:title")
	}, `<meta property="og:title" content="`+htmlpkg.EscapeString(seo.Title)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:description")
	}, `<meta property="og:description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:url")
	}, `<meta property="og:url" content="`+htmlpkg.EscapeString(absoluteRouteSEOURL(seo.CanonicalPath))+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:locale")
	}, `<meta property="og:locale" content="`+htmlpkg.EscapeString(seo.OGLocale)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:image")
	}, `<meta property="og:image" content="`+htmlpkg.EscapeString(routeSEOImage)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:image:alt")
	}, `<meta property="og:image:alt" content="`+htmlpkg.EscapeString(routeSEOImageAlt)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:card")
	}, `<meta name="twitter:card" content="`+htmlpkg.EscapeString(routeSEOTwitterCard)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:site")
	}, `<meta name="twitter:site" content="`+htmlpkg.EscapeString(routeSEOTwitterHandle)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:creator")
	}, `<meta name="twitter:creator" content="`+htmlpkg.EscapeString(routeSEOTwitterHandle)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:title")
	}, `<meta name="twitter:title" content="`+htmlpkg.EscapeString(twitterTitle)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:description")
	}, `<meta name="twitter:description" content="`+htmlpkg.EscapeString(twitterDescription)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:image")
	}, `<meta name="twitter:image" content="`+htmlpkg.EscapeString(routeSEOImage)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:image:alt")
	}, `<meta name="twitter:image:alt" content="`+htmlpkg.EscapeString(routeSEOImageAlt)+`" />`)
	result = upsertHeadTag(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "canonical")
	}, `<link rel="canonical" href="`+htmlpkg.EscapeString(absoluteRouteSEOURL(seo.CanonicalPath))+`" />`)

	result = removeMatchingTags(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "alternate") && strings.Contains(tag, "hreflang")
	})
	for _, alternate := range seo.Alternates {
		result = injectBeforeHeadClose(result, []byte(fmt.Sprintf(
			`<link rel="alternate" hreflang="%s" href="%s" />`,
			htmlpkg.EscapeString(alternate.Hreflang),
			htmlpkg.EscapeString(absoluteRouteSEOURL(alternate.Path)),
		)))
	}
	result = upsertRouteSEOStructuredData(result, seo)
	return result
}

func upsertRouteSEOStructuredData(html []byte, seo routeSEO) []byte {
	result := removeRouteSEOStructuredData(html)
	return injectBeforeHeadClose(result, []byte(`<script type="application/ld+json" data-jisudeng-route-seo="true">`+buildRouteSEOJSONLD(seo)+`</script>`))
}

func buildRouteSEOJSONLD(seo routeSEO) string {
	structuredType := seo.StructuredType
	if strings.TrimSpace(structuredType) == "" {
		structuredType = "WebPage"
	}
	siteName := seo.SiteName
	if strings.TrimSpace(siteName) == "" {
		siteName = routeSEOAuthor
	}
	canonical := absoluteRouteSEOURL(seo.CanonicalPath)
	structuredName := seo.Title
	if structuredType == "WebSite" {
		structuredName = siteName
	}
	graph := map[string]any{
		"@context":    "https://schema.org",
		"@type":       structuredType,
		"name":        structuredName,
		"headline":    seo.Title,
		"description": seo.Description,
		"url":         canonical,
		"inLanguage":  seo.Lang,
		"isPartOf": map[string]any{
			"@type": "WebSite",
			"name":  "Jisudeng",
			"url":   routeSEOOrigin + "/",
		},
		"publisher": map[string]any{
			"@type": "Organization",
			"name":  siteName,
			"url":   routeSEOOrigin + "/",
			"logo": map[string]any{
				"@type": "ImageObject",
				"url":   routeSEOImage,
			},
		},
	}
	if structuredType == "WebSite" {
		if seo.Lang == "zh-CN" {
			graph["alternateName"] = []string{"极速蹬", "Jisudeng"}
		} else {
			graph["alternateName"] = []string{"Jisudeng"}
		}
		graph["mainEntity"] = map[string]any{
			"@type":               "SoftwareApplication",
			"name":                "Jisudeng",
			"applicationCategory": "DeveloperApplication",
			"operatingSystem":     "Web",
			"description":         seo.Description,
			"url":                 canonical,
		}
	}
	payload, err := json.Marshal(graph)
	if err != nil {
		return "{}"
	}
	return string(payload)
}

func absoluteRouteSEOURL(path string) string {
	return routeSEOOrigin + path
}

func setHTMLLang(html []byte, lang string) []byte {
	return replaceFirstTag(html, "html", func(string) bool { return true }, func(tag string) string {
		return setTagAttr(tag, "lang", lang)
	})
}

func replaceTitleTag(html []byte, title string) []byte {
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return injectBeforeHeadClose(html, []byte("<title>"+htmlpkg.EscapeString(title)+"</title>"))
	}
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.WriteString("<title>")
	buf.WriteString(htmlpkg.EscapeString(title))
	buf.WriteString("</title>")
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func upsertHeadTag(html []byte, tagName string, match func(string) bool, replacement string) []byte {
	replaced := false
	result := replaceFirstTag(html, tagName, match, func(string) string {
		replaced = true
		return replacement
	})
	if replaced {
		return result
	}
	return injectBeforeHeadClose(html, []byte(replacement))
}

func replaceFirstTag(html []byte, tagName string, match func(string) bool, replacement func(string) string) []byte {
	token := []byte("<" + tagName)
	for offset := 0; offset < len(html); {
		idxOffset := bytes.Index(bytes.ToLower(html[offset:]), token)
		if idxOffset == -1 {
			return html
		}
		idx := offset + idxOffset
		endOffset := bytes.IndexByte(html[idx:], '>')
		if endOffset == -1 {
			return html
		}
		end := idx + endOffset + 1
		tag := string(html[idx:end])
		if match(strings.ToLower(tag)) {
			var buf bytes.Buffer
			buf.Write(html[:idx])
			buf.WriteString(replacement(tag))
			buf.Write(html[end:])
			return buf.Bytes()
		}
		offset = end
	}
	return html
}

func removeMatchingTags(html []byte, tagName string, match func(string) bool) []byte {
	token := []byte("<" + tagName)
	var buf bytes.Buffer
	cursor := 0
	for cursor < len(html) {
		idxOffset := bytes.Index(bytes.ToLower(html[cursor:]), token)
		if idxOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		idx := cursor + idxOffset
		endOffset := bytes.IndexByte(html[idx:], '>')
		if endOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		end := idx + endOffset + 1
		tag := strings.ToLower(string(html[idx:end]))
		if match(tag) {
			buf.Write(html[cursor:idx])
		} else {
			buf.Write(html[cursor:end])
		}
		cursor = end
	}
	return buf.Bytes()
}

func removeRouteSEOStructuredData(html []byte) []byte {
	token := []byte("<script")
	closeToken := []byte("</script>")
	var buf bytes.Buffer
	cursor := 0
	for cursor < len(html) {
		idxOffset := bytes.Index(bytes.ToLower(html[cursor:]), token)
		if idxOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		idx := cursor + idxOffset
		openEndOffset := bytes.IndexByte(html[idx:], '>')
		if openEndOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		openEnd := idx + openEndOffset + 1
		tag := strings.ToLower(string(html[idx:openEnd]))
		closeOffset := bytes.Index(bytes.ToLower(html[openEnd:]), closeToken)
		if closeOffset == -1 {
			buf.Write(html[cursor:openEnd])
			cursor = openEnd
			continue
		}
		blockEnd := openEnd + closeOffset + len(closeToken)
		if tagHasAttr(tag, "type", "application/ld+json") && tagHasAttr(tag, "data-jisudeng-route-seo", "true") {
			buf.Write(html[cursor:idx])
			cursor = blockEnd
			continue
		}
		buf.Write(html[cursor:blockEnd])
		cursor = blockEnd
	}
	return buf.Bytes()
}

func injectBeforeHeadClose(html, tag []byte) []byte {
	headClose := []byte("</head>")
	idx := bytes.Index(bytes.ToLower(html), headClose)
	if idx == -1 {
		return html
	}
	var buf bytes.Buffer
	buf.Write(html[:idx])
	buf.Write(tag)
	buf.WriteByte('\n')
	buf.Write(html[idx:])
	return buf.Bytes()
}

func tagHasAttr(tag, attr, value string) bool {
	return strings.Contains(tag, attr+`="`+strings.ToLower(value)+`"`) ||
		strings.Contains(tag, attr+`='`+strings.ToLower(value)+`'`)
}

func setTagAttr(tag, attr, value string) string {
	escaped := htmlpkg.EscapeString(value)
	lower := strings.ToLower(tag)
	for _, quote := range []byte{'"', '\''} {
		prefix := attr + "=" + string(quote)
		start := strings.Index(lower, prefix)
		if start == -1 {
			continue
		}
		valueStart := start + len(prefix)
		valueEndOffset := strings.IndexByte(tag[valueStart:], quote)
		if valueEndOffset == -1 {
			return tag
		}
		valueEnd := valueStart + valueEndOffset
		return tag[:valueStart] + escaped + tag[valueEnd:]
	}
	insertAt := len(tag) - 1
	if insertAt < 0 {
		return tag
	}
	return tag[:insertAt] + ` ` + attr + `="` + escaped + `"` + tag[insertAt:]
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontendRequest(c.Request) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if cleanPath != "index.html" && tryServeOverrideFile(c, overrideDir, cleanPath) {
			return
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		if isEmbeddedAssetRequest(cleanPath) {
			serveMissingEmbeddedAsset(c)
			return
		}

		serveIndexHTML(c, distFS)
	}
}

func isEmbeddedAssetRequest(cleanPath string) bool {
	return strings.HasPrefix(cleanPath, "assets/")
}

func serveMissingEmbeddedAsset(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	c.String(http.StatusNotFound, "static asset not found")
	c.Abort()
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/robots.txt" ||
		trimmed == "/sitemap.xml" ||
		trimmed == "/llms.txt" ||
		trimmed == "/models" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		strings.HasPrefix(trimmed, "/images/") ||
		strings.HasPrefix(trimmed, "/videos/")
}

func shouldBypassEmbeddedFrontendRequest(r *http.Request) bool {
	if r == nil {
		return true
	}
	if strings.TrimSpace(r.URL.Path) == "/models" && isFrontendHTMLNavigation(r) {
		return false
	}
	return shouldBypassEmbeddedFrontend(r.URL.Path)
}

func isFrontendHTMLNavigation(r *http.Request) bool {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		return false
	}
	if r.Header.Get("Authorization") != "" ||
		r.Header.Get("x-api-key") != "" ||
		r.Header.Get("x-goog-api-key") != "" {
		return false
	}
	return strings.Contains(strings.ToLower(r.Header.Get("Accept")), "text/html")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	content = injectRouteSEO(content, c.Request.URL.Path)
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
