//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
	seoTitleSuffix       = "AI API Gateway 与中文提示词库"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontendRequest(c.Request) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" {
			s.serveIndexHTML(c)
			return
		}
		if s.tryServeOverride(c, cleanPath) {
			return
		}
		if !s.fileExists(cleanPath) {
			if isEmbeddedAssetRequest(cleanPath) {
				serveMissingEmbeddedAsset(c)
				return
			}
			s.serveIndexHTML(c)
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	path := c.Request.URL.Path
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		etag := routeSEOETag(cached.ETag, path)
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == etag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)
		content = injectRouteSEO(content, path)

		c.Header("ETag", etag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", injectRouteSEO(s.baseHTML, path))
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", injectRouteSEO(s.baseHTML, path))
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)
	content = injectRouteSEO(content, path)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", routeSEOETag(cached.ETag, path))
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteTitle(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)

	return result
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// injectSiteTitle replaces the static <title> in HTML with the configured site title.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}
	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(buildSiteTitle(siteName)) + "</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func buildSiteTitle(siteName string) string {
	return strings.TrimSpace(siteName) + " - " + seoTitleSuffix
}

type routeSEOAlternate struct {
	Hreflang string
	Path     string
}

type routeSEO struct {
	Title         string
	Description   string
	CanonicalPath string
	Lang          string
	OGLocale      string
	Alternates    []routeSEOAlternate
}

const routeSEOOrigin = "https://www.jisudeng.com"

var publicRouteSEO = map[string]routeSEO{
	"/": {
		Title:         "极速蹬 - AI API Gateway 与中文提示词库",
		Description:   "极速蹬是面向开发者、团队和 AI 工具用户的 AI API Gateway，提供模型接口、中文提示词库、图像工作室和统一计费服务。",
		CanonicalPath: "/",
		Lang:          "zh-CN",
		OGLocale:      "zh_CN",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "x-default", Path: "/en/"},
		},
	},
	"/home": {
		Title:         "极速蹬 - AI API Gateway 与中文提示词库",
		Description:   "极速蹬是面向开发者、团队和 AI 工具用户的 AI API Gateway，提供模型接口、中文提示词库、图像工作室和统一计费服务。",
		CanonicalPath: "/",
		Lang:          "zh-CN",
		OGLocale:      "zh_CN",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "x-default", Path: "/en/"},
		},
	},
	"/models": {
		Title:         "极速蹬模型与价格 - AI API Gateway",
		Description:   "查看极速蹬公开模型目录、模型平台、用途分类与 USD / 1M tokens 计费参考，登录后可查看分组有效价格。",
		CanonicalPath: "/models",
		Lang:          "zh-CN",
		OGLocale:      "zh_CN",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/models"},
			{Hreflang: "en", Path: "/en/models"},
			{Hreflang: "x-default", Path: "/en/models"},
		},
	},
	"/docs": {
		Title:         "极速蹬使用文档 - API 接入指南",
		Description:   "阅读极速蹬 API Key、OpenAI 兼容接口、图片生成、异步任务、Batch Image 与计费说明。",
		CanonicalPath: "/docs",
		Lang:          "zh-CN",
		OGLocale:      "zh_CN",
		Alternates: []routeSEOAlternate{
			{Hreflang: "zh-CN", Path: "/docs"},
			{Hreflang: "en", Path: "/en/docs"},
			{Hreflang: "x-default", Path: "/en/docs"},
		},
	},
	"/en": {
		Title:         "Jisudeng: One OpenAI-Compatible API for Frontier AI Models",
		Description:   "Access DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through one OpenAI-compatible API.",
		CanonicalPath: "/en/",
		Lang:          "en",
		OGLocale:      "en_US",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/"},
			{Hreflang: "zh-CN", Path: "/"},
			{Hreflang: "x-default", Path: "/en/"},
		},
	},
	"/en/models": {
		Title:         "AI Models API: DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini | Jisudeng",
		Description:   "Compare model access and usage-based API rates for DeepSeek, Qwen, Kimi, GLM, GPT, Claude, Gemini and more through Jisudeng.",
		CanonicalPath: "/en/models",
		Lang:          "en",
		OGLocale:      "en_US",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/models"},
			{Hreflang: "zh-CN", Path: "/models"},
			{Hreflang: "x-default", Path: "/en/models"},
		},
	},
	"/en/docs": {
		Title:         "Jisudeng API Docs - OpenAI-Compatible Gateway Quickstart",
		Description:   "Use Jisudeng with your existing OpenAI SDK. Change only your base URL and API key to access multiple frontier AI models.",
		CanonicalPath: "/en/docs",
		Lang:          "en",
		OGLocale:      "en_US",
		Alternates: []routeSEOAlternate{
			{Hreflang: "en", Path: "/en/docs"},
			{Hreflang: "zh-CN", Path: "/docs"},
			{Hreflang: "x-default", Path: "/en/docs"},
		},
	},
}

func normalizePublicRouteSEOPath(path string) string {
	clean := strings.TrimSpace(path)
	if clean == "" {
		return "/"
	}
	if i := strings.IndexAny(clean, "?#"); i >= 0 {
		clean = clean[:i]
	}
	if clean == "/" {
		return "/"
	}
	return strings.TrimRight(clean, "/")
}

func resolveRouteSEO(path string) (routeSEO, bool) {
	seo, ok := publicRouteSEO[normalizePublicRouteSEOPath(path)]
	return seo, ok
}

func routeSEOETag(baseETag, path string) string {
	if _, ok := resolveRouteSEO(path); !ok {
		return baseETag
	}
	base := strings.Trim(baseETag, `"`)
	suffix := strings.Trim(strings.ReplaceAll(normalizePublicRouteSEOPath(path), "/", "-"), "-")
	if suffix == "" {
		suffix = "root"
	}
	return `"` + base + "-seo-" + suffix + `"`
}

func injectRouteSEO(html []byte, path string) []byte {
	seo, ok := resolveRouteSEO(path)
	if !ok {
		return html
	}

	result := setHTMLLang(html, seo.Lang)
	result = replaceTitleTag(result, seo.Title)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "description")
	}, `<meta name="description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:title")
	}, `<meta property="og:title" content="`+htmlpkg.EscapeString(seo.Title)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:description")
	}, `<meta property="og:description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:url")
	}, `<meta property="og:url" content="`+htmlpkg.EscapeString(absoluteRouteSEOURL(seo.CanonicalPath))+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "property", "og:locale")
	}, `<meta property="og:locale" content="`+htmlpkg.EscapeString(seo.OGLocale)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:title")
	}, `<meta name="twitter:title" content="`+htmlpkg.EscapeString(seo.Title)+`" />`)
	result = upsertHeadTag(result, "meta", func(tag string) bool {
		return tagHasAttr(tag, "name", "twitter:description")
	}, `<meta name="twitter:description" content="`+htmlpkg.EscapeString(seo.Description)+`" />`)
	result = upsertHeadTag(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "canonical")
	}, `<link rel="canonical" href="`+htmlpkg.EscapeString(absoluteRouteSEOURL(seo.CanonicalPath))+`" />`)

	result = removeMatchingTags(result, "link", func(tag string) bool {
		return tagHasAttr(tag, "rel", "alternate") && strings.Contains(tag, "hreflang")
	})
	for _, alternate := range seo.Alternates {
		result = injectBeforeHeadClose(result, []byte(fmt.Sprintf(
			`<link rel="alternate" hreflang="%s" href="%s" />`,
			htmlpkg.EscapeString(alternate.Hreflang),
			htmlpkg.EscapeString(absoluteRouteSEOURL(alternate.Path)),
		)))
	}
	return result
}

func absoluteRouteSEOURL(path string) string {
	return routeSEOOrigin + path
}

func setHTMLLang(html []byte, lang string) []byte {
	return replaceFirstTag(html, "html", func(string) bool { return true }, func(tag string) string {
		return setTagAttr(tag, "lang", lang)
	})
}

func replaceTitleTag(html []byte, title string) []byte {
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return injectBeforeHeadClose(html, []byte("<title>"+htmlpkg.EscapeString(title)+"</title>"))
	}
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.WriteString("<title>")
	buf.WriteString(htmlpkg.EscapeString(title))
	buf.WriteString("</title>")
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

func upsertHeadTag(html []byte, tagName string, match func(string) bool, replacement string) []byte {
	replaced := false
	result := replaceFirstTag(html, tagName, match, func(string) string {
		replaced = true
		return replacement
	})
	if replaced {
		return result
	}
	return injectBeforeHeadClose(html, []byte(replacement))
}

func replaceFirstTag(html []byte, tagName string, match func(string) bool, replacement func(string) string) []byte {
	token := []byte("<" + tagName)
	for offset := 0; offset < len(html); {
		idxOffset := bytes.Index(bytes.ToLower(html[offset:]), token)
		if idxOffset == -1 {
			return html
		}
		idx := offset + idxOffset
		endOffset := bytes.IndexByte(html[idx:], '>')
		if endOffset == -1 {
			return html
		}
		end := idx + endOffset + 1
		tag := string(html[idx:end])
		if match(strings.ToLower(tag)) {
			var buf bytes.Buffer
			buf.Write(html[:idx])
			buf.WriteString(replacement(tag))
			buf.Write(html[end:])
			return buf.Bytes()
		}
		offset = end
	}
	return html
}

func removeMatchingTags(html []byte, tagName string, match func(string) bool) []byte {
	token := []byte("<" + tagName)
	var buf bytes.Buffer
	cursor := 0
	for cursor < len(html) {
		idxOffset := bytes.Index(bytes.ToLower(html[cursor:]), token)
		if idxOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		idx := cursor + idxOffset
		endOffset := bytes.IndexByte(html[idx:], '>')
		if endOffset == -1 {
			buf.Write(html[cursor:])
			break
		}
		end := idx + endOffset + 1
		tag := strings.ToLower(string(html[idx:end]))
		if match(tag) {
			buf.Write(html[cursor:idx])
		} else {
			buf.Write(html[cursor:end])
		}
		cursor = end
	}
	return buf.Bytes()
}

func injectBeforeHeadClose(html, tag []byte) []byte {
	headClose := []byte("</head>")
	idx := bytes.Index(bytes.ToLower(html), headClose)
	if idx == -1 {
		return html
	}
	var buf bytes.Buffer
	buf.Write(html[:idx])
	buf.Write(tag)
	buf.WriteByte('\n')
	buf.Write(html[idx:])
	return buf.Bytes()
}

func tagHasAttr(tag, attr, value string) bool {
	return strings.Contains(tag, attr+`="`+strings.ToLower(value)+`"`) ||
		strings.Contains(tag, attr+`='`+strings.ToLower(value)+`'`)
}

func setTagAttr(tag, attr, value string) string {
	escaped := htmlpkg.EscapeString(value)
	lower := strings.ToLower(tag)
	for _, quote := range []byte{'"', '\''} {
		prefix := attr + "=" + string(quote)
		start := strings.Index(lower, prefix)
		if start == -1 {
			continue
		}
		valueStart := start + len(prefix)
		valueEndOffset := strings.IndexByte(tag[valueStart:], quote)
		if valueEndOffset == -1 {
			return tag
		}
		valueEnd := valueStart + valueEndOffset
		return tag[:valueStart] + escaped + tag[valueEnd:]
	}
	insertAt := len(tag) - 1
	if insertAt < 0 {
		return tag
	}
	return tag[:insertAt] + ` ` + attr + `="` + escaped + `"` + tag[insertAt:]
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontendRequest(c.Request) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if cleanPath != "index.html" && tryServeOverrideFile(c, overrideDir, cleanPath) {
			return
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		if isEmbeddedAssetRequest(cleanPath) {
			serveMissingEmbeddedAsset(c)
			return
		}

		serveIndexHTML(c, distFS)
	}
}

func isEmbeddedAssetRequest(cleanPath string) bool {
	return strings.HasPrefix(cleanPath, "assets/")
}

func serveMissingEmbeddedAsset(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	c.String(http.StatusNotFound, "static asset not found")
	c.Abort()
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/robots.txt" ||
		trimmed == "/sitemap.xml" ||
		trimmed == "/models" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		strings.HasPrefix(trimmed, "/images/") ||
		strings.HasPrefix(trimmed, "/videos/")
}

func shouldBypassEmbeddedFrontendRequest(r *http.Request) bool {
	if r == nil {
		return true
	}
	if strings.TrimSpace(r.URL.Path) == "/models" && isFrontendHTMLNavigation(r) {
		return false
	}
	return shouldBypassEmbeddedFrontend(r.URL.Path)
}

func isFrontendHTMLNavigation(r *http.Request) bool {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		return false
	}
	if r.Header.Get("Authorization") != "" ||
		r.Header.Get("x-api-key") != "" ||
		r.Header.Get("x-goog-api-key") != "" {
		return false
	}
	return strings.Contains(strings.ToLower(r.Header.Get("Accept")), "text/html")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	content = injectRouteSEO(content, c.Request.URL.Path)
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
